### ISSUE TITLE
Feature request: improved citation and reference completion

### ISSUE THREAD

**Issue by tbdcit** [latex-lsp/texlab#1]
Firstly, thanks for creating this project!

It would be great to extend the completion support for references and citations to support the following things:

- completion support for equation references `\eqref`,
- support for parsing citations from a bibliography added with `\bibliography{path/to/bib}` ,
- setting the details/documentation property of citation completions to include the author(s) and the title. It would be great if whenever the user types `\cite{` the completion window contains not just the cite key but the author and title (I am not sure but I thought this could be done by setting the either  the detaill property or the documentation property of the completion),
- hover support for references and citations: when the user hovers over a reference show the definition, when a the user hovers over a citation show author and title (and possibly other details).

Personally I would find these features particularly useful, all of my citation keys are some unique identifier that are not very instructive as to what is being cited (most of the citation keys I use are the same as used on mathsci.net).

**Comment by efoerster** [comment]
Thanks for your great feedback 👍
We have deployed a new version including most of these features. However, we still have some questions:

2) It should work with relative paths. Did you try it with absolute paths? They are not supported yet.
4) What do you mean with the definition of a reference? (\label{foo} ?)

**Comment by tbdcit** [comment]
Thanks for the quick response!

I have just built and tested some of the more recent features and can confirm that the following are working as expected:

 - completion of `\eqref`
 - completion of `\cite` with additional dialog showing extra information about the citation (hover support working also)

As for included bib files, I find that none of the following work

```
\bibliography{/home/user/work/bibliography/bibliography}
\bibliography{../../bibliography/bibliography}
\addbibresource{../../bibliography/bibliography.bib}
```

where as the following do work as expected
```
\bibliography{/home/user/work/bibliography/bibliography.bib}
\addbibresource{/home/user/work/bibliography/bibliography.bib}
```
(note that the first example should not work i.e. latex won't find the bibliography when compiling the file).


> > hover support for references and citations: when the user hovers over a reference show the definition
>
> What do you mean with the definition of a reference? (\label{foo} ?)

Yes - when the user hovers over a `\ref{my-label}` it would be useful to  see a dialog containing the text in the document where `\label{my-label}`  appears (for example you could just include the line containing `\label{my-label}` but this wouldn't be very useful for equation references where instead it might be better to show the line containing `\label{my-label}` and the line that follows it). There is an excellent plugin for org mode in emacs called org-ref that provides such features for both latex and org mode files which might be worth looking at.

**Comment by efoerster** [comment]
> As for included bib files, I find that none of the following work [...]

Including files that are not part of the current workspace should now work correctly.

> Yes - when the user hovers over a \ref{my-label} it would be useful to see a dialog containing the text in the document [...]

This can already be done with the "Peek Definition" or "Go To Definition" feature, which most editors provide.

**Comment by clason** [comment]
Regarding the last comment: One useful possibility that doesn't duplicate existing functionality would be if hover over a reference previewed the *formatted* reference, i.e.,
* `(3.1)` for `\eqref{eq:iteration-definition}`,
* `2.4` for `\ref{sec:convergence}`
* `Theorem 4.1` for `\cref{thm:error-estimates}`

(I do find this useful, since sometimes I can remember the tex label, other times only the formatted label when looking for something -- especially in longer projects like books.)
