### ISSUE TITLE
GetSystemTimePreciseAsFileTime error on Windows 7

### ISSUE THREAD

**Issue by augustjanse** [latex-lsp/texlab#101]
The language support doesn't work. I run the server for Vim with autozimu/LanguageClient-neovim on Windows 7. When I open a tex file, I get this message:

> The procedure entry point GetSystemTimePreciseAsFileTime could not be located in the dynamic link library KERNEL32.dll.

When I googled the problem, I found grijjy/DelphiDuktape#1 which seems to imply that this function is not available on Windows 7, but I guess the server calls it somehow. The [docs](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) confirm that it's not supported.

Am I correct? If so, I wish you would support Windows 7. If other users have got this running on Windows 7, I would appreciate some help figuring out what I did wrong.

**Comment by efoerster** [comment]
This should be fixed by https://github.com/latex-lsp/texlab/commit/08775b97af706218a75ed8e449a5e17ae6de0576. Can you try out the latest commit?

**Comment by augustjanse** [comment]
That worked, thanks!
