### ISSUE TITLE
News: AUCTeX changes major mode names which breaks emacs-lsp / latex-lsp / texlab

### ISSUE THREAD

**Issue by vitaminace33** [latex-lsp/texlab#1015]
I had informed AUCTeX develop that AUCTeX 14.0.0 breaks TexLab 5.12.3. It turns out that changes in the major update break Emacs lsp-mode. In turn they have informed Emacs LSP of the changes.

https://github.com/emacs-lsp/lsp-mode/issues/4332

This "issue" is just to let know AUCTeX / TexLab users that a solution is on the way.

**Comment by eli-tziperman** [comment]
just to add that while texlab does work now, lsp-grammarly does not work under auctex for me...

**Comment by rromoli** [comment]
my texlab still not work... texlab v5.14.1, AucTeX 14.0.4. Get this: `LSP :: The following servers support current file but do not have automatic installation: texlab2`

**Comment by vitaminace33** [comment]
Everything is fine with me: Emacs 29.2 (Manjaro) and 30.0.50 (Ubuntu), Spacemacs develop, texlab 5.14.1, and AUCTeX 14.0.4.

**Comment by rromoli** [comment]
I found a solution and I posted here:
https://github.com/emacs-lsp/lsp-mode/issues/4332#issuecomment-2034838346

**Comment by vitaminace33** [comment]
Taken care of "upstream". Might need some more time 'til other AUCTeX related packages consider the changes in AUCTeX itself.
