### ISSUE TITLE
cargo install fails on beta but cargo build works

### ISSUE THREAD

**Issue by TheZoq2** [latex-lsp/texlab#102]
I'm trying to install this project from source by using `cargo install --path .` which gives me the following error:

```rust
error[E0277]: the `?` operator can only be applied to values that implement `std::ops::Try`
  --> src/tex.rs:54:5
   |
54 | /     Command::new(format.executable())
55 | |         .args(&["--interaction=batchmode", "-shell-escape", file_name])
56 | |         .current_dir(&directory)
57 | |         .stdout(Stdio::null())
58 | |         .stderr(Stdio::null())
59 | |         .status()
60 | |         .map_err(|_| CompileError::LatexNotInstalled)?
   | |______________________________________________________^ the `?` operator cannot be applied to type `futures_util::try_future::map_err::MapErr<impl core::future::future::Future, [closure@src/tex.rs:60:18: 60:53]>`
   |
   = help: the trait `std::ops::Try` is not implemented for `futures_util::try_future::map_err::MapErr<impl core::future::future::Future, [closure@src/tex.rs:60:18: 60:53]>`
   = note: required by `std::ops::Try::into_result
```

This happens with a freshly installed beta (`rustup update beta`), `nightly-2019-10-04` and the nightly version specified in the CI files here.

However, `cargo build --release` seems to work, which is a bit weird since I was under the impression that install just runs `cargo build --release`.

I tried both the current master, and the `1.6.0` tag

**Comment by efoerster** [comment]
I think the issue was caused by the fact that `cargo install` ignores the lockfile, see https://github.com/rust-lang/cargo/issues/6983. You should use the `--locked` flag. However, this particular error should be fixed now by https://github.com/latex-lsp/texlab/commit/2d5bdffcb4cfc65f2fbf798fd93b1194f0670f4d.

**Comment by TheZoq2** [comment]
Oh, that's not the behaviour I would expect :P

It does look like 2d5bdff fixed it though, thanks!
