### ISSUE TITLE
Error when there are parentheses in label

### ISSUE THREAD

**Issue by firubat** [latex-lsp/texlab#1021]
If I have `(` or `)` in a label, texlab displays an error 
```
Expecting a curly bracket: "}"
```
It appears both at the label definition, and when referring to it with `\ref`.
No problem in compilation, no errors or warnings are displayed, and the references work fine.

texlab 5.12.3 in Neovim 0.9.5

**Comment by pfoerster** [comment]
@firubat This is already fixed by https://github.com/latex-lsp/texlab/pull/1017 (will be part of `v5.12.4`).

**Comment by firubat** [comment]
Great, thanks!
