### ISSUE TITLE
Inlay hints config in Wiki missing

### ISSUE THREAD

**Issue by jdujava** [latex-lsp/texlab#1023]
It took me some time to realize I should CamelCase the `inlay_hints` options when passing them to `TexLab` LSP, something like
```lua
inlayHints = {
  labelDefinitions = false,
  labelReferences = false,
}
```
Just a heads up, if anyone else struggles with the configuration. Updating the Wiki https://github.com/latex-lsp/texlab/wiki/Configuration would be probably the best, since I noticed `InlayHints` options are missing. Thanks!

**Comment by pfoerster** [comment]
Thanks, I have updated the Wiki page 👍
