### ISSUE TITLE
Slowdown in lsp-mode because the sever reports errors on TinyTex LaTeX distribution instead of only in the current project

### ISSUE THREAD

**Issue by maikol-solis** [latex-lsp/texlab#1028]
The whole description and logs about this issue are here (https://github.com/emacs-lsp/lsp-mode/issues/4356). 

The problem is that the server is sending a lot of calls for loaded packages and their TeX files, like 

```
[Trace - 04:35:01 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [],
  "uri": "file:///Users/maikol/Library/TinyTeX/texmf-dist/tex/latex/base/ltluatex.tex"
}
```

The issue was fixed by this commit (https://github.com/latex-lsp/texlab/commit/1a2ad9e7ba00b6037ec5e66e640acd556cf49ba3), but my best guess is that this line also requires an additional filter for "tex" files. 

https://github.com/latex-lsp/texlab/blob/1a2ad9e7ba00b6037ec5e66e640acd556cf49ba3/crates/base-db/src/graph.rs#L80

WDYT?

Best.

**Comment by pfoerster** [comment]
@maikol-solis 

> but my best guess is that this line also requires an additional filter for "tex" files.

We cannot add this here because it would break discovering the project (e. g. `\include{foo}` would not find `foo.tex`).

I think the better solution is to never send diagnostics for files that are part of the TeX distro.

**Comment by maikol-solis** [comment]
> I think the better solution is to never send diagnostics for files that are part of the TeX distro.

Yes, this will solve the issue completely.
