### ISSUE TITLE
Could we have a warning for unused bibtex entries?

### ISSUE THREAD

**Issue by towagner** [latex-lsp/texlab#103]
Hello,
it would be an awesome feature if unused bibtex entries are marked with a warning in order that I can delete them to keep my bibtex file clean.

**Comment by clason** [comment]
Do you know about `bibexport`/`biber --bibtool`?

**Comment by efoerster** [comment]
I do not know if this behavior is good for all use cases. Some users like to reuse their databases for multiple papers. In that case such warnings could be annoying. Any thoughts on this? `biber` seems to be a good solution already.
