### ISSUE TITLE
Update the preview instructions for Skim

### ISSUE THREAD

**Issue by heymhm** [latex-lsp/texlab#1031]
Hi, I am using texlab with Helix and Skim, and the config suggested in the texlab-wiki are causing issues when previewing the doc after rebuild on save.

The current instructions in the wiki suggest enabling the "Reload automatically" setting in Skim preferences, however, that is discouraged in the [Skim-wiki](https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/) for this reason:
> Note: The auto-reload functionality will not work properly when you have to run a latex process more than once, for example to support references generated by bibtex, because Skim will be trying to reload the document when the second latex process is busy.

Instead, as suggested in the Skim-wiki, `-r` argument should be passed to the `displayline` command, and "Reload automatically" setting should be disabled. This would change the texlab config to:
```json
{
  "texlab.forwardSearch.executable": "/Applications/Skim.app/Contents/SharedSupport/displayline",
  "texlab.forwardSearch.args": ["-r", "%l", "%p", "%f"]
}
```

The previews work smoothly for me after the above modifications.

**Comment by pfoerster** [comment]
Thanks @heymhm, I have updated the wiki page 👍.
