### ISSUE TITLE
Complete on my macro definitions (e.g., as if they were a \ref)

### ISSUE THREAD

**Issue by rdiaz02** [latex-lsp/texlab#1032]
This is a question, not a bug. But I am not sure if this is even possible (I am new to using LSP).

I have some macros that texlab sees (I followed https://github.com/latex-lsp/texlab/issues/100), and the macros themselves are completed. 

For example, I have this:

```
\newcommand*{\qref}[1]{\hyperref[{#1}]{\textit{``\nameref*{#1}'' (section \ref*{#1})}}}
```

I would like that, after inserting `\qref{}` and when inside the `{}`, I was offered completions (e.g., for `sec:`, `eq:`, etc) as I am offered when I write `\ref`. Much like it happens, for example, with `eqref` . 

The more general question is: is there a way to tell texlab to issue completions for a macro as if it were something else it already gives completions for?

(In case it matters, I am using Emacs with lsp-mode and lsp-latex).

And apologies if this is a stupid question. This is the sort of thing I can do with `company-reftex` (Emacs) by modifying the `company-reftex-labels-regexp` variable, so it now also completes after `qref`, for example. But I might be completely confused here.

**Comment by pfoerster** [comment]
> The more general question is: is there a way to tell texlab to issue completions for a macro as if it were something else it already gives completions for?

For some commands, it is already possible (see `texlab.experimental.citationCommands` for example). For `\ref`-like commands, it will be possible with #1033.

> And apologies if this is a stupid question.

Definitely not a stupid question ^^

**Comment by rdiaz02** [comment]
Thanks a lot for your answer!!  I'll keep an eye in the PR then, and annotation that I can do that with citations already.

**Comment by ROCKTAKEY** [comment]
@pfoerster Hi, thanks for your maintenance.
Could you please write document about "texlab.experimental.labelReferenceCommands"?
I would like to solve https://github.com/ROCKTAKEY/lsp-latex/issues/46 but I don't know about this feature.

**Comment by pfoerster** [comment]
@ROCKTAKEY Sure: https://github.com/latex-lsp/texlab/wiki/Configuration#texlabexperimentallabelreferencecommands

It behaves like `texlab.experimental.citationCommands` except that it operates on `\label` instead of BibTeX entries.

**Comment by ROCKTAKEY** [comment]
Thanks!
