### ISSUE TITLE
Errors persist after fixing what caused them in BBEdit (Texlab 5.13.0)

### ISSUE THREAD

**Issue by ArttuLai** [latex-lsp/texlab#1042]
I'm using BBEdit (15.0.1) on macOS Ventura (14.4) as text editor, where I'm compiling .tex files via Tectonic, and using Texlab as language server provider via BBEdit's LSP support. The earlier versions, (like 5.12.4) used to work just fine, but I'm noticing that with 5.13.0, the errors won't go away from BBEdit's UI after I fix them.

E.g. if I type an extra curly brace, there will be a red highlight showing I have error in that line, and there's also another counter that shows the total amount of errors in the active document. But after I remove the brace and fix the error, the error counter still says I have errors, and in general the feature started behaving bit oddly. The .tex file compiles just fine; it just shows the old error, and only way I can get rid of it to relaunch BBEdit.

Going back to 5.12.4 makes it work normally again.

Is there more info I can provide to troubleshoot this further?

Here's a [screen recording](https://github.com/latex-lsp/texlab/assets/42007282/fc8b6889-f93f-4c05-be70-94de410c7e4e) of the issue.

Edit: here's a second [screen recording of Texlab 5.12.4](https://github.com/latex-lsp/texlab/assets/42007282/7ebe070f-4f8d-49de-87a5-ea932bccd629) showing how it's supposed to work.

**Comment by samuelqp** [comment]
I am having the same issue using neovim with  v5.13.0. Using the command "LspRestart" seems to hide the error message, as well as closing and re-opening the file.

**Comment by mathjiajia** [comment]
The same issue,
I have downgraded to 5.12
