### ISSUE TITLE
`-pvc` flag should be mentioned in docs about previewing

### ISSUE THREAD

**Issue by n8xm** [latex-lsp/texlab#105]
On the [documentation page about previewing](https://texlab.netlify.com/docs/installation/previewing), it mentions that we should pass the `-pv` flag to the `latex.build.args` setting. 

I think the documentation should mention that one should pass the `-pvc` flag if one does not want to launch a new instance of the PDF viewer after every build. (At least [one other person strongly recommends -pvc with texlab](https://github.com/latex-lsp/texlab/issues/40#issuecomment-511935547)).

EDIT: Suggested documentation should read as follows: 

> With latexmk, you can enable the preview feature by adding the `-pv` flag to the latex.build.args setting. **Alternatively, use the `-pvc` flag to tell the previewer to continuously check for updates, instead of opening a new window each time a build completes.**

**Comment by n8xm** [comment]
I just edited my original post with a suggested sentence to add to the [original documentation](https://texlab.netlify.com/docs/installation/previewing).

**Comment by pfoerster** [comment]
Thanks, I have updated the [website](https://texlab.netlify.com/docs/installation/previewing).
