### ISSUE TITLE
[Feature proposal] Is it possible to make LaTeX LSP work for other file types like html or markdown?

### ISSUE THREAD

**Issue by ktrNozomi** [latex-lsp/texlab#1052]
If possible, how can I configure with vscode? Thanks a lot for any ideas.

**Comment by DasNaCl** [comment]
To my understanding, this is not possible without major extensions to the codebase.

**Comment by clason** [comment]
Also, what would be the point? There are dedicated language servers that implement the LSP for those file types (after all, that's the whole point of the protocol).

**Comment by ktrNozomi** [comment]
@clason @DasNaCl Thanks a lot for your replying! There may be some cases that one needs to write some complex latex in markdown environments (there are some alternatives like [Markdown-All-in-One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) available), or in raw HTML math environments, or in any better formats in the future. After reviewing my question, I find that it may be a problem about **mixing multiple LSPs in a single file with specific language syntax context**, I'm sorry to post the issue in wrong place. So it seems that it is not possible to achieve that goal in current LSP architecture. Thanks a lot for your replying again!

**Comment by clason** [comment]
> I find that it may be a problem about mixing multiple LSPs in a single file with specific language syntax context

That is correct, and that is something the LSP specification does not address -- and apparently [does not want to](https://github.com/microsoft/language-server-protocol/issues/505). It's a glaring omission, but what can you do.
