### ISSUE TITLE
Regression? finding project root

### ISSUE THREAD

**Issue by martinra** [latex-lsp/texlab#1061]
The following simple setup is not recognized correctly: Two files, an empty `packages.tex` and a file `main.tex` with content
```
\documentclass{amsart}

\input{packages}

\begin{document}
\end{document}
```

Auxiliary and log files are created in the home directory (on Linux), and the log implies that the project root passed is indeed my home folder, while the files that are created are in a folder `~/tmp`.

When creating a git repository in the folder `~/tmp`, the project root is detected correctly.

I suspect this arises from the re-implemented project detection, since in Winter this worked without problem.

**Comment by martinra** [comment]
I do. I also pulled #1062 and the project root is now detected correctly. Thanks a lot the quick solution!

**Comment by pfoerster** [comment]
@pitkling How are you checking the project root? Compiling the project, looking at the dependency graph or something else? How does the wrong project root show itself?

**Comment by pitkling** [comment]
@pfoerster I used `:LspInfo` of neovim/nvim-lspconfig and also double checked via the log file created bis `texlab --log-file <file>`. Is this reproducible on your end or is it specific to my setup? Let me know if I can provide any further info to debug this.

**Comment by pfoerster** [comment]
@pitkling 

> Is this reproducible on your end or is it specific to my setup?

With VSCode, I am not able to reproduce it. Is the working directory of the editor (and thus the server) set to `~` or `~/tmp`. If it is `~`, then https://github.com/latex-lsp/texlab/pull/1098 should have fixed this issue.

**Comment by pitkling** [comment]
The working directory of Neovim seems not to matter. I tested it by starting Neovim from `~/`, from `~/tmp/`, and from a different subdirectory of `~/`. Neovim's `:LspInfo` still reports `~/` as the root directory if `~/tmp/.latexmkrc` is not present. Again, other indicator files (`~/tmp/{texlabroot,.texlabroot,.git}`) do not help either.

I also made sure to disable any other unrelated Neovim configuration/plugins and only load `texlab` via `Neovim/nvim-lspconfig`.

**Comment by pitkling** [comment]
@pfoerster In case it helps, [here](https://gist.github.com/pitkling/d7565986eef44d908c2ef36d303348d8) is `texlab`'s log file (maximum verbosity) when opening `~/tmp/main.tex` in a minimal Neovim configuration. I had all the project root indicator files `~/tmp/{texlabroot,.texlabroot,.git,latexmkrc}` present. As the log file indicates, `texlab` sets `~/` as the project root.

**Comment by clason** [comment]
This is an nvim-lspconfig issue (root directory detection is part of the client configuration shipped by this plugin); please open the issue there.

**Comment by pitkling** [comment]
Ok, thanks for the pointer, I thought `nvim-lspconfig` takes the root directly from `texlab`.
