### ISSUE TITLE
Autocomplete in \ref{} is empty when using colon in Neovim.

### ISSUE THREAD

**Issue by adamheins** [latex-lsp/texlab#1064]
I'm experiencing a similar issue to the one previously described in #599, with the following setup:

OS: Ubuntu 20.04
texlive: 2019
texlab: 5.14.1
neovim: 0.9.5

For example, with a latex label of `sec:intro`, if I then type `\ref{se`, I would get `sec:intro` as an autocomplete suggestion, among others. But as soon as I get to typing the colon, `\ref{sec:`, then no suggestions are provided at all, no matter how long I wait. As soon as I'm past it, say `\ref{sec:i`, then the suggestions return as expected.

My OS and texlive version are old, but texlab and neovim are recent. Any idea what's going on here?

**Comment by clason** [comment]
Almost certainly a Neovim issue with how `iskeyword` and trigger characters are handled. (Or, since autocompletion is not built in, with your plugin. Works fine for me.)

**Comment by adamheins** [comment]
You're right, it's an issue with [nvim-cmp](https://github.com/hrsh7th/nvim-cmp). For reference, it appears to be fixed by adding the following to my nvim-cmp configuration (see [here](https://github.com/hrsh7th/nvim-cmp/issues/808)):
```lua
cmp.setup {
  completion = {
    keyword_pattern = [[\k\+]]
  }
}
```
