### ISSUE TITLE
Thmtool's \declaretheorem should also accept list of environment names

### ISSUE THREAD

**Issue by jdujava** [latex-lsp/texlab#1075]
The command `\declaretheorem` should accept comma separated list of environment names, see end of page 3 of the `thmtools` documentation https://mirrors.nic.cz/tex-archive/macros/latex/contrib/thmtools/doc/thmtools-manual.pdf#page=3.

As of now, for example a following code snippet
```
\declaretheorem[sibling=table, style=thmbox]{definition, theorem, lemma, corollary, proposition}
```
results in errors `Expecting a curly bracket: "}"` and `Unexpected "}"`.

Also, the `treesitter` isn't handling it properly, should I raise a separate issue, or is this enough?

**Comment by pfoerster** [comment]
> Also, the treesitter isn't handling it properly, should I raise a separate issue, or is this enough?

`tree-sitter-latex` is now up to date: https://github.com/latex-lsp/tree-sitter-latex/pull/121
