### ISSUE TITLE
ConcealLevel Support?

### ISSUE THREAD

**Issue by Jaehaks** [latex-lsp/texlab#1077]
If I use texlab. `set conceallevel=2` does not work unlike vimtex. 
Can texlab supports conceallevel?

**Comment by clason** [comment]
This has _nothing_ to do with texlab. (You may want to look at nvim-treesitter with the tree-sitter-latex parser, which _does_ have conceal, but nothing nearly as extensive as VimTeX -- and this is intentional. So if you want serious conceal, you _need_ VimTeX.

**Comment by pfoerster** [comment]
@Jaehaks `texlab` is a language server and does not really know much of the editor besides the name, version and supported LSP features. Currently, there is no way to provide this feature within the LSP spec.
