### ISSUE TITLE
Disabling individual warnings

### ISSUE THREAD

**Issue by helq** [latex-lsp/texlab#1092]
I am getting an erroneous "undefined reference" warning from this newcommand definition

```latex
\newcommand{\mycitep}[1]{\cite{#1}}
```

I've been looking in the wiki, and it might be that I am bad at looking, but I haven't found a simple way to disable the warning for that single line. I would expect something like:

```latex
\newcommand{\mycitep}[1]{\cite{#1}} % texlab: disable warning

% or

% texlab: disable warning
\newcommand{\mycitep}[1]{\cite{#1}}

% or

\newcommand{\mycitep}[1]{\cite{#1}}
% ^ texlab: disable warning
```

Is there a way to disable individual warnings?
Thank you!

**Comment by pfoerster** [comment]
@helq Currently, you only disable the entire warning (for all occurrences) and not individual occurences.

Nevertheless, the false-positive produced by your example will be fixed with the next release.
