### ISSUE TITLE
Theorem definitions are not picked up from class file

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#110]
I have custom document classes that define standard environments using `amsthm` (theorem, proposition, lemma, definition) etc. These are not picked up by texlab for the purpose of setting LocationLinks for PeekDefinition (i.e., popup shows just the label, not the whole environment).

In other words, texlab should consider `.cls` files just like `.tex` and `.sty` files for environment definitions.

(related to #29)

**Comment by clason** [comment]
This class file is in the current directory, but it might be shadowed by the same file in my `TEXMFHOME`, so this might indeed be a consequence of #100.

**Comment by clason** [comment]
Hmm, might indeed be a bug; my class file is apparently only added to the project tree when I open it in the editor. (Your example works, though.)

**Comment by pfoerster** [comment]
Does it work if you open the class file before calling peek definition? If so, then I have found the problem. It should be fairly easy to fix.

**Comment by clason** [comment]
I've pared my example down to the following:
```latex
%test.tex
\documentclass{test}

\begin{document}

\begin{lemma} \label{lemma}
    A lemma.
\end{lemma}

\end{document}
```

```latex
%test.cls
\newtheorem{lemma}{Lemma}
```
I don't really see a difference to yours, though...

**Comment by clason** [comment]
Yes, that fixes it -- thank you very much! :heart:
