### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#111]
It would be helpful when debugging clients if the errors in error messages were deserialized (either `data` or `message`).

In addition, it might be helpful to use `window/showMessage` or `window/logMessage` for actual errors or logging?

_(Oh, and texlab is the model language server for the recently merged LSP functionality in core neovim: https://github.com/norcalli/nvim-common-lsp 👍 )_

**Comment by pfoerster** [comment]
> It would be helpful when debugging clients if the errors in error messages were deserialized (either data or message).

fac129313dd14915f0ac15e73c8d75375888498e should be what you are looking for. Before TexLab sends a response that represents an error, the error gets deserialized and is written to `stderr`.

> In addition, it might be helpful to use window/showMessage or window/logMessage for actual errors or logging?

Actually, VSCode already does this so I think it would be annoying if the notification happens twice. However, we could wait until client identification support lands and add it then.

> (Oh, and texlab is the model language server for the recently merged LSP functionality in core neovim: https://github.com/norcalli/nvim-common-lsp 👍 )

🚀

**Comment by clason** [comment]
> fac1293 should be what you are looking for. Before TexLab sends a response that represents an error, the error gets deserialized and is written to stderr.

Great, thank you!

> Actually, VSCode already does this so I think it would be annoying if the notification happens twice. However, we could wait until client identification support lands and add it then.

To be honest, I'm not fully certain about this either -- many things that are properly warnings (in particular, "aux/log file not found") are expected here, and I don't want to see them all the time... (While for someone debugging a client or the connection, this could be helpful.)

This requires some thinking about configurability etc; feel free to close this issue in the meantime since the main request for deserialized error messages is now implemented.
