### ISSUE TITLE
Bib reference error for subimports

### ISSUE THREAD

**Issue by brunotvs** [latex-lsp/texlab#1145]
The LSP displays an ‘undefined reference’ error in files imported with the import package.

**Comment by brunotvs** [comment]
Actually, I found two behaviors that I consider undesirable:

1. When I define a new command using `import` or `subimport`, TexLab appears to be unable to build the document tree.

```tex
\newcommand{\structure}[1]{
	\subimport{#1/}{document.tex}
}
```

2. If I `subimport` `file1.tex` and, in `file1.tex`, I input `file2.tex`, TexLab does not seem to consider `file2.tex` as part of the same project as `file1.tex`.

**Comment by brunotvs** [comment]
Created this repo showing the errors:
https://github.com/brunotvs/texlab_issue

**Comment by pfoerster** [comment]
@brunotvs Currently, this is to be expected because the server does not implement the same logic as the TeX engine so in this case, it does not know that `\structure{foo}` resolves to `\subimport{foo}{document.tex}`. There two ways to solve this issue:

1. Hard-code this case similar to `texlab.experimental.labelDefinitionCommands` (difficult to draw the line here on what is useful enough to be hard-coded into the server)
2. Implement a (rudimentary) macro expansion engine in the server (very hard)

**Comment by brunotvs** [comment]
@pfoerster Okay, but what about nested subimports?

**Comment by brunotvs** [comment]
@pfoerster, in addition, can the .fls file be utilized?

**Comment by pfoerster** [comment]
> @pfoerster Okay, but what about nested subimports?

If they just use the plain `\subimport` command, they should work.

> @pfoerster, in addition, can the .fls file be utilized?

Sure, #1160 adds a the `.fls` as an additional source for the project detection. With this changeset, your example will work now after compiling the document once.

**Comment by brunotvs** [comment]
> If they just use the plain `\subimport` command, they should work.

If you refer to the [repo I created](https://github.com/brunotvs/texlab_issue) and navigate to problem2/subproblem2/document.tex, you will see reference errors that should not be present. I'm using neovim 0.10.0, wsl ubuntu and a mason installation of texlab

> Sure, https://github.com/latex-lsp/texlab/pull/1160 adds a the .fls as an additional source for the project detection.

Awesome, sounds great.

**Comment by pfoerster** [comment]
> @pfoerster I found that if I add a latexmkrc file, citation and refs from nested submimports stop working as per this [repo](https://github.com/brunotvs/texlab_issue)

Thanks for the example. With #1161, your example should work as intended.
