### ISSUE TITLE
Bibtex parsing for DOIs

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#117]
👍 to removing the node dependency for citeproc! (I'll see about updating the homebrew PR -- if it's still not merged...)

I (only) noticed one regression: DOIs are no longer parsed but appear in the hover preview as, e.g.,
```
https://doi.org/[10.1007/978\-94\-007\-2247\-7](10.1007/978-
94-007-2247-7)
```

**Comment by pfoerster** [comment]
Can you try 086712d83aa0b98609c6a5fd51e081f06ee847f3, please? This commit should fix the regression although this does seem to look like an issue with `citeproc-rs`. I am going to look into this matter.

**Comment by clason** [comment]
Hmm, that shows 
```
retrieved from [https://doi.org/10.1051/m2an/
2016012](https://doi.org/10.1051/m2an/2016012)
```
which I personally like even less ;) But it's a correct URL now, so no longer a bug!

If that can be hacked, my preference would be
```
 [https://doi.org/10.1051/m2an/
2016012](doi:10.1051/m2an/2016012)
```
(no "retrieved from"; shortened printed doi).

**Comment by pfoerster** [comment]
Can you try 02cd699d5c13eaa58a29b4572c3413866c5721ff, please? It should implement your preference.

**Comment by clason** [comment]
So it does, even with the markdown corrected ;) Thank you!
