### ISSUE TITLE
False undefined reference error with thebibliography

### ISSUE THREAD

**Issue by bilichboris** [latex-lsp/texlab#1171]
Texlab marks every \cite{} as an undefined reference, although they correspond to entries in "\begin{thebibliography}". For a particular example, one can run texlab on the attached latex source code.
[arXiv-2106.04884v2.gz](https://github.com/user-attachments/files/16324848/arXiv-2106.04884v2.gz)

**Comment by gi1242** [comment]
I have the same issue (texlab 5.17.0, on arch linux, neovim v0.10.1). Here's a minimal example to reproduce:

```tex
\documentclass{article}
See~\cite{ref1}

\begin{thebibliography}
  \bibitem{ref1} Reference 1
\end{thebibliography}
\end{document}
```

It complies cleanly without errors (using latexmk); however, texlab shows `Undefined reference error` on `ref1`.

Please let me know if there's anything I can do to help you reproduce this problem.

Thanks,

GI
