### ISSUE TITLE
Support "Go to definition" for starred variants of commands

### ISSUE THREAD

**Issue by jdujava** [latex-lsp/texlab#1197]
Consider the following:
```latex
\NewDocumentCommand{\foo}{s m}{%
    \IfBooleanTF{#1}{\textbf{#2}}{#2}%
}

\foo{bar}
\foo{barr}
\foo*{barrr}
```
"Go to definition" works properly only for the non-starred calls, similarly "Go to references".
I think it would be appropriate to include also starred variants.

**Comment by nolanking90** [comment]
In the goto_definition function, line 30, appending a `.replace("*", "")` to strip the star fixes this specific case. 
I'm unsure if this would break some other commands. Are any starred variants of latex commands ever defined explicitly, like '\NewCommand{\foo*}'? Can a starred variant of a command ever be defined in a different location than the unstarred variant?

**Comment by jdujava** [comment]
As far as I know, there is no way to define starred variants explicitely, see ["the old way"](https://tex.stackexchange.com/a/4389) and ["the new way"](https://tex.stackexchange.com/a/4399). It thus seems that just removing the trailing star would be satisfactory solution.
