### ISSUE TITLE
Building multiple files with included `begin{document}`

### ISSUE THREAD

**Issue by kwon-young** [latex-lsp/texlab#122]
I noticed that texlab is failing to build a multiple file latex project where the `begin{document}` is not in the root latex file but included using a `\input{other.tex}` command.

Here is a minimal 2 file latex project to reproduce the issue:
```
% main.tex
\documentclass{article}
    % General document formatting
    \usepackage[margin=0.7in]{geometry}
    \usepackage[parfill]{parskip}
    \usepackage[utf8]{inputenc}
    
    % Related to math
    \usepackage{amsmath,amssymb,amsfonts,amsthm}

\input{content.tex}

\end{document}
```
```
% content.tex
\begin{document}


Name, date, Exercise X

\section*{Part a}

Put your answer to part a here

tooto

\section*{Part b}

etc
```
Here is the texlab backtrace log:
```
WARN - Could not open file: /tmp/test_latex/main.aux
WARN - Could not open file: /tmp/test_latex/content.aux
thread 'tokio-runtime-worker-0' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0:     0x555c658d2abc - <unknown>
   1:     0x555c6572bebc - <unknown>
   2:     0x555c658d2316 - <unknown>
   3:     0x555c658d1f80 - <unknown>
   4:     0x555c658d171f - <unknown>
   5:     0x555c658d124f - <unknown>
   6:     0x555c658e4726 - <unknown>
   7:     0x555c65729359 - <unknown>
   8:     0x555c657297f8 - <unknown>
   9:     0x555c65696a70 - <unknown>
  10:     0x555c65684054 - <unknown>
  11:     0x555c656a049d - <unknown>
  12:     0x555c65695582 - <unknown>
  13:     0x555c6568fcc3 - <unknown>
  14:     0x555c65a6d598 - <unknown>
  15:     0x555c65a68f5e - <unknown>
  16:     0x555c65a65990 - <unknown>
  17:     0x555c65a6348a - <unknown>
  18:     0x555c65a744b3 - <unknown>
  19:     0x555c65a6cfe1 - <unknown>
  20:     0x555c658e3b4f - <unknown>
  21:     0x555c658e595c - <unknown>
  22:     0x7f51cbf8a4cf - start_thread
  23:     0x7f51cbe9f2d3 - clone
  24:                0x0 - <unknown>
WARN - Could not open file: /tmp/test_latex/main.aux
WARN - Could not open file: /tmp/test_latex/content.aux
```

My configuration:

* os: Manjaro
* editor: nvim v0.4.0
* lsp plugin: LanguageClient-Neovim v0.1.155
* texlab: 
```
$ pacman -Si texlab            
Repository      : community
Name            : texlab
Version         : 1.6.0-2
Description     : A cross-platform implementation of the Language Server Protocol for LaTeX.
Architecture    : x86_64
URL             : https://texlab.netlify.com
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : gcc-libs
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 7,81 MiB
Installed Size  : 30,57 MiB
Packager        : Konstantin Gizdov <arch@kge.pw>
Build Date      : mer. 23 oct. 2019 17:52:10 CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

I know this is quite a peculiar way to split a latex project into multiple files but this is a template not made by me that I have use to write my thesis, but I consider this a bug since latexmk can perfectly build this project.
In any case I hope this will help squeeze out another bug.

**Comment by pfoerster** [comment]
Thanks for the very detailed report. 2a050ce46d014a4fc0c60bb8e087d3b9cdd68f9c should fix the issue. Note that you should call the build command from `main.tex` instead of `content.tex` because of your setup. In this case, TexLab cannot reliably detect which file is the main file.

**Comment by kwon-young** [comment]
Thanks for the quick fix!
> Note that you should call the build command from main.tex instead of content.tex because of your setup.
Ah, I forgot to show the code for calling the build command using LanguageClient-Neovim but yes, I am calling it using `main.tex`.
Unfortunately, I can't test your change right away since I use texlab packaged by the archlinux repo.
This is not really critical for me so I'll test it when it hits the archlinux repo.

**Comment by kwon-young** [comment]
I've verified that the new version of texlab works!

Thank you for your help!
