### ISSUE TITLE
The Project Detection wiki entry is out-of-date

### ISSUE THREAD

**Issue by anwaralameddin** [latex-lsp/texlab#1264]
The [Project Detection](https://github.com/latex-lsp/texlab/wiki/Project-Detection) wiki entry is out-of-date and does not reflect the current criteria used in [<code>ProjectRoot::walk_and_find</code>](https://github.com/latex-lsp/texlab/tree/75efe5c4502527f8cbf28e4b93ae881333d46301/crates/base-db/src/deps/root.rs#L18-L43), [<code>Semantics::process_root</code>](https://github.com/latex-lsp/texlab/blob/75efe5c4502527f8cbf28e4b93ae881333d46301/crates/base-db/src/semantics/tex.rs#L45-L68) and [<code>Semantics::process_environment</code>](https://github.com/latex-lsp/texlab/blob/75efe5c4502527f8cbf28e4b93ae881333d46301/crates/base-db/src/semantics/tex.rs#L309-L321).

The Root directory section could be updated to reflect that:

-   <code>texlab.rootDirectory</code> was removed in <code>5.16.1</code>
-   <code>.latexmkrc</code> and <code>latexmkrc</code> are also used to detect the root directory, and
-   the <code>document</code> environment is used to detect documents that can be root.

The Algorithm section could be updated to refer to both the file system root and the user's home directory.

**Comment by pfoerster** [comment]
@anwaralameddin Thanks, I have updated the wiki page :)
