### ISSUE TITLE
[bug] texlab considers links containing `%` in `\href` as a comment

### ISSUE THREAD

**Issue by marcfranquesa** [latex-lsp/texlab#1279]
Links to files containing spaces contain `%`, and `\href` allows you to insert the link as is. texlab seems to understand it as a comment and considers the `{` from `\href` to not be closed, therefore giving an error expecting a `}`.

Reproducible example:
```
\documentclass[12pt]{article}

\usepackage{hyperref}

\begin{document}

\href{https://github.com/latex-lsp/texlab/example%20file.pdf}{URL with \%}.

\end{document}
```

Thanks!

**Comment by nolanking90** [comment]
You can escape the `%` as `\%`,
```
\href{https://github.com/latex-lsp/texlab/example\%20file.pdf}{URL with \%}.
```
Alternatively, you can use a space instead of `%20`, 
```
\href{https://github.com/latex-lsp/texlab/example file.pdf}{URL with \%}.
```
Both of these produce the desired result without the diagnostic.

The hyperref documentation says: 
> The special characters # and % do not need to be escaped in any way (unless
the command is used in the argument of another command).

I read this to mean that hyperref does not care if you escape the `%` or not.

**Comment by marcfranquesa** [comment]
Alright, thanks. I assume there is no intention to support having these characters as is (without escaping them) then?

**Comment by nolanking90** [comment]
I’m open to working on it if you have a suggestion for how to do it. I thought about it for a bit and it’s not obvious to me how to do it without some complicated look ahead while walking the tree. @pfoerster thoughts?

**Comment by marcfranquesa** [comment]
Great, thanks a lot! I am very new to LSPs, I'll let you know if I come up with something.

**Comment by pfoerster** [comment]
> I’m open to working on it if you have a suggestion for how to do it. I thought about it for a bit and it’s not obvious to me how to do it without some complicated look ahead while walking the tree. @pfoerster thoughts?

I think you need to do this at the parser/lexer level and introduce a `PATH` token. Walking the tree would be difficult because you have to split and tokenize the `COMMENT` token again.

**Comment by nolanking90** [comment]
I think I have this working now, and I've added one unit test for this command:
```
\href{https://www.test.com/url%20%with%20space}{A test URL}
```

I could use suggestions for other test cases to check before I push a PR.

**Comment by marcfranquesa** [comment]
also maybe adding support for `\url{}`?

and, not sure how much of use it would be, but what about a unit test such as,

```
% \href{https://www.test.com/url%20%with%20space}{A test URL}
```
