### ISSUE TITLE
Support of Texlive inside docker container

### ISSUE THREAD

**Issue by arwtyxouymz** [latex-lsp/texlab#138]
Hi,

I use this language server with neovim by `coc.nvim` and `coc-texlab`.
I'm trying to use this with `texlive` inside docker container.
If I correctly set the executable configuration like 
```json
"latex.build.executable": "docker run -it --rm -v $PWD:/workdir -v $PWD/.latexmkrc:/root/.latexmkrc paperist/alpine-texlive-ja:latest latexmk"
```
,`texlab` responds 
```
Your Tex distribution could not be detected. Please make sure that your distribution is in Your PATH
```

I checked your code and found [these lines](https://github.com/latex-lsp/texlab/blob/7faf67aefa8e217e8e1ceb28d12bfbfec629dc49/crates/texlab_distro/src/lib.rs#L30-L55) are the cause of this problem.
You call `latex` command directly.

I think some people want to use `latexmk` inside docker container including me.
So this language server should support texlive inside docker.

How do you think about this?

**Comment by pfoerster** [comment]
> I think some people want to use latexmk inside docker container including me.
So this language server should support texlive inside docker.

Actually, most of the features of TexLab do not require a TeX distribution.
These things won't work:
- Previewing equations (we are working on this one)
- Detecting and scanning packages that are not part of TexLive.
  You probably won't use a Docker container for this purpose.

Regarding the warning message at the startup: we should add
an option to disable the warning for Docker users.

**Comment by pfoerster** [comment]
With texlab `3.0` and upwards, this warning no longer occurs. Instead, it is only a log message.
