### ISSUE TITLE
How to preview PDF in subfolder

### ISSUE THREAD

**Issue by Neur1n** [latex-lsp/texlab#147]
So I pass `-outdir=build` to latexmk during building, and all the output files including the PDF will go into the `build` folder under the project folder.

I'm using SumatraPDF and have configured forward search according to the [previewing](https://texlab.netlify.com/docs/installation/previewing) page. I can preview the PDF if it is in the same folder as the tex file, but I don't know how to configure it to preview the PDF inside the `build` folder.

Please provide some advice. Thanks a lot.

**Comment by pfoerster** [comment]
Thanks for the report. I have trouble reproducing this issue. Can you post your configuration for `latex.build.args`, please? I am using the following settings and preview seems to be working just fine:
```json
{
  "latex.build.args": [
    "-pdf",
    "-interaction=nonstopmode",
    "-synctex=1",
    "-outdir=build",
    "-pv"
  ]
}
```

**Comment by Neur1n** [comment]
After some tests, I've found that:
1. I was not using the `-pv` option with which I can preview the PDF right after building.
2. I'm using the [coc-texlab](https://github.com/fannheyward/coc-texlab) plugin to work with texlab, and I configured the forward search arguments as `['-reuse-instance', '%p', '-forward-search', '%f', '%l']` according to texlab's previewing guide. But I still cannot manually trigger previewing via calling forward search command. Any suggestions on the arguments? Otherwise I think I should open an issue on coc-texlab's repo.

Thanks.

**Comment by pfoerster** [comment]
> But I still cannot manually trigger previewing via calling forward search command. Any suggestions on the arguments?

Our current implementation of forward search assumes that the auxillary files are located in the same directory as the TeX file. In addition to that, this also concerns the scanning of log/aux files. We will probably add a setting where you can set the build directory so TexLab knows where to look for the auxillary files.

**Comment by pfoerster** [comment]
With the latest commit on the master branch, we have added a new setting `latex.build.outputDirectory` where you can optionally specify the directory containing the build artifacts. In your case, the setting needs to be `build`. Note that you *cannot* omit the `-outdir=build` flag from the `latex.build.args` setting. We will publish a new release soon.

**Comment by pfoerster** [comment]
Can you try the latest release ([v1.10.0](https://github.com/latex-lsp/texlab/releases/tag/v1.10.0)), please?

**Comment by Neur1n** [comment]
It worked! Thanks for your effort!
