### ISSUE TITLE
Goto definition for commands

### ISSUE THREAD

**Issue by frank-emrich** [latex-lsp/texlab#15]
Hi,
first of all, thanks a lot for this project. This looks like a great improvement for my latex workflow. Code completion works nicely for me :)

On https://texlab.netlify.com/, it says that texlab supports the go to definition feature, but I can't get it to work. I've tried the following minimal document in both emacs' `lsp-mode` and a vanilla VS Code installation + the texlab extension:

```
\documentclass{article}
\begin{document}
\newcommand{\test}{test}
hello \test{}  
\end{document}
```

In both editors, going to the definition of `\test` does not work.

**Comment by efoerster** [comment]
Thanks for the report. This is not implemented yet, but it is on our roadmap. The "Go To Definition" feature currently only works for labels and citations.

**Comment by frank-emrich** [comment]
ah, thanks clarifying.

**Comment by pfoerster** [comment]
This feature is now implemented on the master branch. We will publish a new release soon.
