### ISSUE TITLE
[Request] Use latexindent to provide formatting for LaTeX

### ISSUE THREAD

**Issue by wbthomason** [latex-lsp/texlab#151]
As the title suggests, it would be nice if `texlab` could provide formatting for LaTeX (as well as Bibtex). One way to do this could be by outsourcing to `latexindent`.

**Comment by pfoerster** [comment]
The latest release of `texlab` now provides formatting for LaTeX and BibTeX files using `latexindent`. The built-in BibTeX formatter is still available.
