### ISSUE TITLE
Easy install via cargo

### ISSUE THREAD

**Issue by jounathaen** [latex-lsp/texlab#152]
IMHO the simples method of installing this tool (from source) is via this cargo one-liner:

```bash
cargo install --git https://github.com/latex-lsp/texlab.git
```
Maybe this helps other users.

(If this tool would be a crate on crates.io, one could simply install and update it via `cargo install texlab`. :wink:)

**Comment by pfoerster** [comment]
Thanks for the report. I was not aware that you can install `git` repositories via `cargo`. I added the one-liner to the README. Publishing the crate on crates.io is not an easy task as this would involve publishing a lot of other crates like the `jsonrpc` and `jsonrpc-derive` crates, which we don't think, are ready yet for use cases other than `texlab`.

**Comment by pfoerster** [comment]
Closing this one in favor of #399.
