### ISSUE TITLE
Change pdf previewer in arguments

### ISSUE THREAD

**Issue by mvcouwen** [latex-lsp/texlab#158]
I would like to change the pdf previewer by giving the following argument to latexmk.
```sh
-e '$pdf_previewer=q/Open -a Skim/'
```
However the following does not seem te work.
```vim
'latex.build.args': ["-pdf","-pv","-e '$pdf_previewer=q/Open -a Skim/'","-synctex=1"]
```
Escaping some of the characters did not work either.

I prefer not to change the pdf previewer in `.latexmkrc` since I do not want Skim to be the default pdf previewer when I run `latexmk` from terminal.

How do I obtain a log of what goes wrong? I am running the texlab server on MacOS through coc.nvim with its extension coc-texlab.

**Comment by pfoerster** [comment]
Thanks for the report. Have you tried using the following?
```json
"latex.build.args": ["-pdf", "-pv", "-e", "$pdf_previewer=q/Open -a Skim/", "-synctex=1"]
```
The `-e` flag and the value need to be separated.

> How do I obtain a log of what goes wrong? I am running the texlab server on MacOS through coc.nvim with its extension coc-texlab.

You can try looking at the `stderr` output of `texlab`. Unfortunately, I do not know how you can access  the output from `coc-texlab`.

**Comment by mvcouwen** [comment]
This seems te work. Perhaps a good idea to mention this in the documentation? It might be easier for some people to do this rather than making/adjusting a `.latexmkrc` file?

I am closing this issue although the solution might not be perfect (the two arguments clearly belong together but are listed separately, in particular the order matters).

Keep up the great work with `texlab`!

**Comment by pfoerster** [comment]
> This seems te work. Perhaps a good idea to mention this in the documentation?

I have updated the website: https://texlab.netlify.com/docs/reference/configuration#latexbuildargs
