### ISSUE TITLE
[Feature request] Preview pdf in background

### ISSUE THREAD

**Issue by mvcouwen** [latex-lsp/texlab#159]
Adding the argument `-pv` to `latexmk` previews the pdf after building. However, the focus also changes on the pdf viewer. The same happens when doing a forward search.

Would it be possible to keep the pdf viewer in the background but still do a preview or forwards search. This would keep the focus on the text editor which allows to continue working on the document.

This feature is implemented in [lervag/vimtex](https://github.com/lervag/vimtex).

**Comment by mvcouwen** [comment]
This can be solved on MacOS by adding the argument `-g` to the `open` command and the `displayline` command from `Skim`. Probably something else exists for the `start` command?

Depending on whether this solution suffices, this issue can be closed. Maybe we can add some instructions to the documentation? Or add a boolean variable that sets this automatically?

**Comment by pfoerster** [comment]
I want to avoid handling specific PDF viewers in our code base and keep the previewing feature generic. So, I guess this is more of a documentation issue. I will add some instructions to the website to achieve previewing in the background. How exactly does your `latex.build` and `latex.forwardSearch` config with the workaround look like? Unfortunately, I do not have a macOS machine available for testing at the moment.

**Comment by mvcouwen** [comment]
I have
```json
'latex.build.args': ["-pdf","-pv","-e","$pdf_previewer=q/Open -g -a Skim/","-synctex=1","-interaction=nonstopmode"]
```
and
```json
'latex.forwardSearch.args': ["-g","%l", "%p", "%f"]
```
This seems to work perfectly fine.

**Comment by pfoerster** [comment]
Thanks, I added some additional instructions to the website:
https://texlab.netlify.com/docs/installation/previewing#skim

**Comment by MohamedIrfanAM** [comment]
@pfoerster How can I get the same behaviour with Zathura?

**Comment by pfoerster** [comment]
> How can I get the same behaviour with Zathura?

I think you can try adding the `--fork` flag to the forward search arguments.
For the rest: Do not use the `-pv` or `-pvc` flag. Instead, use the "build on save" feature along with `texlab.build.forwardSearchAfter`.
