### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by pleroux0** [latex-lsp/texlab#18]
Hi

When trying to build, I get the following exception:

```
> Task :discoverMainScriptsExtensions
e: /home/pleroux/Repositories/texlab/src/main/kotlin/texlab/LatexLanguageServer.kt: (4, 33): Symbol is declared in module 'java.naming' which does not export package 'com.sun.jndi.toolkit.url'
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
2 actionable tasks: 2 executed
```

I'm using ArchLinux with OpenJDK 11.0.3. Any help to get it up and running will be much appreciated.

**Comment by efoerster** [comment]
Thanks for the report. 
It seems that you are on an outdated commit. This was fixed with https://github.com/latex-lsp/texlab/commit/0d1575f371b622878c11b648fdafb0039cfb6e19.

**Comment by pleroux0** [comment]
Hi. Sorry for taking so long to respond.

Updating to the tip of the master branch fixed the issue.

The completions and stuff are at least working for me using [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim). The "textDocument/build" doesn't seem to work for me, but I suspect it's my fault. I'll open up another issue if I can't sort it out by myself.

Thank you very much.
