### ISSUE TITLE
Can't get completion right & Test faild at ``diagnostics_latex''

### ISSUE THREAD

**Issue by liushihao456** [latex-lsp/texlab#191]
Hi! I use Emacs, and I tried installing texlab either through Homebrew or build it from source. But in both cases, I got weird completions. At first one or two inputs, the completions seem fine, but with a third input character the list became like ``! @...''. Please see the pictures below.
<img width="305" alt="屏幕快照 2020-03-19 22 24 41" src="https://user-images.githubusercontent.com/28855328/77077842-bff99200-6a30-11ea-9856-7bfdb1a62dde.png">
<img width="225" alt="屏幕快照 2020-03-19 22 24 48" src="https://user-images.githubusercontent.com/28855328/77077860-c7b93680-6a30-11ea-902c-7b709bb030d3.png">

And I also ran the tests after building from source. It gave 3 errors when running ``diagnostics_latex''.
```
     Running target/debug/deps/diagnostics_latex-9b5da709c3f73cae

running 4 tests
test disabled ... ok
test on_open ... FAILED
test on_save ... FAILED
test on_change ... FAILED

failures:

---- on_open stdout ----
thread 'on_open' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', tests/diagnostics_latex.rs:53:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- on_save stdout ----
thread 'on_save' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', tests/diagnostics_latex.rs:107:17

---- on_change stdout ----
thread 'on_change' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', tests/diagnostics_latex.rs:152:17


failures:
    on_change
    on_open
    on_save

test result: FAILED. 1 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p texlab --test diagnostics_latex'
```

My installed TeX distribution is Basic Tex, via Homebrew.

**Comment by liushihao456** [comment]
Installing full MacTex bundle instead of BasicTex doesn't help either.. The problem still exsits.

**Comment by liushihao456** [comment]
It seems like an issue of emacs lsp-mode. If I use eglot-mode, the completions work fine

**Comment by pfoerster** [comment]
Thanks for the report. Can you share a (small) reproducing example that triggers the faulty completion? Maybe there is something wrong on the side of `texlab`. In addition to that, you can get extra logging if you pass `-vvvv` to `texlab`.

> And I also ran the tests after building from source. It gave 3 errors when running ``diagnostics_latex''.

This is because `texlab` falsely assumes that `BasicTeX` contains `ChkTeX`. I will fix this soon. Note that this test failure should not impact the behavior of the `texlab` executable.

**Comment by liushihao456** [comment]
Of course. My system is macOS Mojave.
1. Install texlab via Homebrew.
2. Install ```lsp-mode``` and ```company-mode``` via ```melpa```. ```lsp-mode``` has already configured ```texlab``` so we don't need to do any configurations ourselves.
3. Open a new ```.tex``` file and run ```M-x lsp```. Then start typing something like ```\cite```.
