### ISSUE TITLE
CTAN and Arch badges are broken in README

### ISSUE THREAD

**Issue by jrwrigh** [latex-lsp/texlab#195]

**Comment by jrwrigh** [comment]
Now it's also the GitHub release and Homebrew badges as well.
![image](https://user-images.githubusercontent.com/20801821/78379437-99d70480-758f-11ea-81d5-b7806c0fd86c.png)

If I just type in the link to the ioshileds url, it works, so I'm not sure if it's GitHub or maybe my browser/internet for some reason?

**Comment by pfoerster** [comment]
I think it has to be related to GitHub. I am seeing it on other repositories, too: https://github.com/badges/shields

![image](https://user-images.githubusercontent.com/13584622/78379846-4be3f000-75d3-11ea-8525-2793729e146b.png)

**Comment by efoerster** [comment]
Related shields.io issue: https://github.com/badges/shields/issues/4878

**Comment by efoerster** [comment]
As of https://github.com/badges/shields/issues/4878#issuecomment-622665018 this should be fixed now.
