### ISSUE TITLE
texlab hangs

### ISSUE THREAD

**Issue by jrwrigh** [latex-lsp/texlab#196]
I've noticed that texlab hangs when using the VSCode extension (and possibly also the coc-nvim extension as well). The process will continue indefinitely, even after I shut down vscode. It takes up 100% CPU usage while it is hung as well.

I would attach logs, but I can't find a way to do so.

OS: Manjaro 19.0.2
VSCode Version: 1.43.2
TexLab extension version: 1.10.0

**Comment by pfoerster** [comment]
Thanks for the report. You can do the following to obtain logs:
1. Checkout the `texlab` and `texlab-vscode` repository.
2. Create a debug build of `texlab` with `cargo build`.
3. Put the `texlab/target/debug` directory temporarily in your `PATH`.
4. Open the `texlab-vscode` repository in VSCode and press F5.`
5. The log can be found in the `LaTeX` channel of the output panel.

**Comment by jrwrigh** [comment]
When I run the VSCode extension, I get the following error:
```
Activating extension 'efoerster.texlab' failed: Cannot find module '/home/jrwrigh/temp/texlab-vscode/dist/extension.js' 
Require stack: - /usr/lib/code/out/vs/loader.js - 
/usr/lib/code/out/bootstrap-amd.js - 
/usr/lib/code/out/bootstrap-fork.js.
```

**Comment by pfoerster** [comment]
Did you run `npm install` before pressing F5? I forgot to mention that. If it still does not work, you may need to run `npm run dist`, too.

**Comment by jrwrigh** [comment]
`npm install` fixed it. I'm writing up a paper due tonight, so I'll probably end up running into the hang issue. I'll post the log files when I do.

**Comment by jrwrigh** [comment]
So I can get it to start maxing out CPU usage fairly quickly, but I can't get it to continue running after I quit VSCode like I was reporting before. Here are the most recent contents from the log before it started using up CPU:

https://pastebin.com/k94ic7wx

**Comment by jrwrigh** [comment]
Also note that I'm not seeing the same behavior from the coc-texlab extension for neovim.

**Comment by efoerster** [comment]
It seems to be related to #212. This could be potentially fixed now with 58b7fb2ccd7a6edb123f98a75a9dc55915746f3. Can you try the latest commit?

**Comment by yadayadaydadaa** [comment]
Maybe related, but sometimes the extension simply stops responding: F5 or the build item from the command palette do nothing. After reloading the VSCode window builds start working again.

**Comment by jrwrigh** [comment]
I've been using the latest version of the vscode plugin which includes the above mentioned fix for a day and haven't run into any issues.

Additionally, the file I was using that sparked the problems had several `\newcommand` specified at the beginning, which may be similar enough to #212 to be the same exact root cause.
