### ISSUE TITLE
how to install the standalone version and use it with vim

### ISSUE THREAD

**Issue by rudrab** [latex-lsp/texlab#20]
Hi,
I am not much used to with jar files. 
I am using texlab with vim and Coc. 
Can you please tell me how to install the file? ` java -jar texlab.jar ` is not doing any thing. Can I just place it in /usr/local/ and give the path to Coc?

Coc: https://github.com/neoclide/coc.nvim
CocLatex: https://github.com/neoclide/coc.nvim/wiki/Language-servers#latex

I am using vim8.

Thanks.

**Comment by efoerster** [comment]
You just need to configure Cog according to your second link and replace the path in the example config with the absolute path of the jar file.

**Comment by pfoerster** [comment]
This is no longer up-to-date.
We have rewritten the server in Rust, so there is no more JAR file that needs to be called.
Thus, you can place the executable in /usr/local or wherever you want and give the path to Coc.

**Comment by clason** [comment]
And just for the sake of completeness, here's how I use it with https://github.com/prabirshrestha/vim-lsp (using vim-plug and assuming the texlab binary is in the PATH):
```viml
call plug#begin('~/.vim/plugged')
    Plug 'prabirshrestha/async.vim'
    Plug 'prabirshrestha/vim-lsp'
 call plug#end()
 au User lsp_setup call lsp#register_server({
            \ 'name': 'texlab',   
            \ 'cmd': {server_info->['texlab']},
            \ 'whitelist': ['bib','tex'],
            \ })
nnoremap <silent> <leader>sd :LspDefinition<cr>
nnoremap <silent> <leader>sp :LspPeekDefinition<cr>
nnoremap <silent> <leader>sr :LspReferences<cr>
nnoremap <silent> <leader>sn :LspRename<cr>
nnoremap <silent> K :LspHover<cr>
```
(Of course, adjust mappings to taste; you can test if the server is running with `:LspStatus`.)
