### ISSUE TITLE
Update lsp-types

### ISSUE THREAD

**Issue by nzt** [latex-lsp/texlab#200]
Current version of lsp-types is 0.73.0 . As this project uses old version, it causes a problem.
In latest LSP, `$/progress` has three kinds of value: `begin`, `report` and `end` but it has `begin`, `report`, `done` in lsp-types 0.61.0 .

This problem effectes LSP clients follows latest LSP. Could you update that crate?

**Comment by pfoerster** [comment]
Thanks for the report. The latest release of `texlab` now uses `lsp-types 0.73.0`.

**Comment by nzt** [comment]
Awesome! Thank you so much.
