### ISSUE TITLE
Support for cleveref

### ISSUE THREAD

**Issue by wbthomason** [latex-lsp/texlab#21]
Related to #1: Could TexLab support packages like https://ctan.org/pkg/cleveref, which use different commands for inserting references (e.g. `\cref{}`)? More generally, it seems it would be useful for there to be an option to customize the commands that trigger a certain sort of completion, e.g. reference commands, citation commands, etc.

**Comment by pfoerster** [comment]
Support for cleveref has been added with the Rust version of the server.
We will publish a new release soon.
However, customizing the commands that trigger a certain sort of completion is not supported yet.
At the moment, we would rather have pull requests that add missing commands such that all users can benefit without having to modify the configuration of the server.
We plan on making the commands customizable once the way we parse LaTeX documents stabilizes.
