### ISSUE TITLE
Fine-grained warnings filtering.

### ISSUE THREAD

**Issue by iago-lito** [latex-lsp/texlab#219]
Hey, I can't find an option to filter out warnings with fine-grained control. Typically, the `overfull/underfull \hbox`, *etc.*

Is there a way to disallow them, or should it be done at the client level, or at the compiler level?

**Comment by pfoerster** [comment]
I think this is better done on the client side or the compiler level. VSCode for example already provides this feature. At the compiler level, you can use `\hfuzz=...pt` and `\vfuzz=...pt` to turn off bad box warnings. Other warnings and errors can be filtered out using the `silence` package.
