### ISSUE TITLE
\newcommand in class files messes up hover equation preview

### ISSUE THREAD

**Issue by yadayadaydadaa** [latex-lsp/texlab#228]
There seems to be something odd about the handling of `\newcommand` in class files: sometimes the contents get shown in the generated hover previews, for example `\newcommand{\myclass@foo}{bar}` gets rendered in the beginning of the hover preview as `foobar`. Changing the `\newcommand` to a `\def` avoids the rendering, but clearly the `\newcommand` shouldn't be rendered. 

(This in the VSCode version.)

**Comment by pfoerster** [comment]
Thanks for the report. This should be fixed with `texlab 2.2.0`.

**Comment by yadayadaydadaa** [comment]
Seems to work 👍, however after a symlink workaround to the failed server download reported in https://github.com/latex-lsp/texlab-vscode/issues/255.
