### ISSUE TITLE
Integration with grammar checkers?

### ISSUE THREAD

**Issue by H-M-H** [latex-lsp/texlab#234]
I am not sure if this in the scope of this project but what do you think about integration of a grammar checker like: https://github.com/languagetool-org/languagetool ? It is a bit painful to run it on plain LaTeX as there are many false positives and I thought as you parse LaTeX anyways it might be not too hard to just feed it the actual text and display the generated warnings.

**Comment by XVilka** [comment]
If only there were grammar checkers in Rust, or any other natively compiled language but not Java...

**Comment by LDAP** [comment]
> 
> 
> I am not sure if this in the scope of this project but what do you think about integration of a grammar checker like: https://github.com/languagetool-org/languagetool ? It is a bit painful to run it on plain LaTeX as there are many false positives and I thought as you parse LaTeX anyways it might be not too hard to just feed it the actual text and display the generated warnings.

Check out [valentjn/ltex-ls](https://github.com/valentjn/ltex-ls)

**Comment by pfoerster** [comment]
Closing this issue as [valentjn/ltex-ls](https://github.com/valentjn/ltex-ls) seems to work fine in combination with `texlab`
