### ISSUE TITLE
Rust branch: citeproc.js missing

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#24]
It may be a bit premature, but I wanted to test the new rust re-implementation. However, that branch fails to build: doing `cargo build --release` (with the latest rust nightly) yields the error 
```
error: couldn't read src/data/../../citeproc/dist/citeproc.js: No such file or directory (os error 2)
```
when compiling the texlab component. (That file indeed can't be found in the texlab tree -- or am I missing a step in building?)

**Comment by efoerster** [comment]
Thanks for the report. You are indeed missing a build step.
We pushed a README containing build instructions to the rust branch.

**Comment by clason** [comment]
Great, thank you very much! I managed to build now -- although the second step didn't work for me, `yarn dist --cwd ./citeproc` errored out with
```
yarn run v1.17.2
error Couldn't find a package.json file in "/scratch/build/texlab"
```
I had to manually cd into `./citeproc` and do `yard dist`.

**Comment by clason** [comment]
Works like a charm. Really excited about this, thanks for developing it!
