### ISSUE TITLE
Discussion: extend list of references

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#25]
This is actually two independent but related issues:

1. Let "list all references" work from a reference, not just the label (e.g., trigger from `\eqref{eq1}`, not just `\label{eq1}`).
2. If this is added, add the definition to the list as well.

But this might be annoying to some? In particular 2. may be redundant, since you can easily go directly to the definition.

**Comment by pfoerster** [comment]
> Let "list all references" work from a reference, not just the label (e.g., trigger from \eqref{eq1}, not just \label{eq1}).

This should be fixed now. "Find all References" now works from a reference in addition to the label.

> If this is added, add the definition to the list as well.

According to the LSP specification it is up to the client to decide whether to include the declaration.
We have changed the server to respect the user's choice.

**Comment by clason** [comment]
> This should be fixed now. "Find all References" now works from a reference in addition to the label.

Yes, can confirm, thank you!

> According to the LSP specification it is up to the client to decide whether to include the declaration.
We have changed the server to respect the user's choice.

That seems indeed the best way.
