### ISSUE TITLE
[Feature request: Completion] context-aware completion

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#26]
(This is the first feature request based on the completion offered by https://github.com/lervag/vimtex.)

In principle, the LSP client is responsible for filtering completion results, but an option that would make sense on the server side is when completing in `\eqref{`, only provide labels from math environments (`equation(*)`, `align(at)(*)`, `multline(*)`). 

(If this is actually feasible; otherwise just close the issue.)

**Comment by pfoerster** [comment]
`\eqref` now only provides completion results for labels that are defined inside a math environment.
