### ISSUE TITLE
Changing engine to xelatex.

### ISSUE THREAD

**Issue by Serenade600** [latex-lsp/texlab#263]
Hi all,
I'm new here. Where could I change the default engine to xelatex? I'm using vs code extension. I guess it's rather straightforward but I cannot find it.
Thanks~

**Comment by efoerster** [comment]
Hey,

TexLab uses `latexmk` as default build tool. To change the default engine to XeLaTeX you need to add the `-pdflatex=xelatex` flag to the `latex.build.args` setting:
```json
  "latex.build.args": [
    "-pdf",
    "-pdflatex=xelatex",
    "-interaction=nonstopmode",
    "-synctex=1",
    "%f"
  ]
```

**Comment by Serenade600** [comment]
That works all right. Thanks again for your help~
