### ISSUE TITLE
Set result.isIncomplete flag correctly

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#275]
I'm having issues with texlab's completion on neovim and `completion-nvim`: the latter recently implemented caching, which prevents texlab from sending the full list of completions on further keystrokes since it has a hard limit of 50 candidates and does not set the `result.isIncomplete` flag (which is used in `completion-nvim` to disable caching). From what I understand, this is due to bugs in/issues with VS Code (see https://github.com/latex-lsp/texlab/issues/227#issuecomment-629770183).

While I understand VS Code being a sort of _primus inter pares_ of LSP clients, it would be good if the texlab _server_ itself strictly followed the specification (which it mostly does! :+1:) here and workarounds needed for VS Code were moved to the corresponding _extension_ (assuming this is possible here?)

**Comment by pfoerster** [comment]
Moving the handling of the completion would be not that straight-forward as it would involve an additional setting. However, it is quite easy to check if VSCode is the current client with the new client identification mechanism in recent LSP versions. If I unterstood correctly, `texlab` needs to set `isIncomplete` to `false` if the completion list contains less than 50 candidates to enable cachinig. This should be done with 3b0db49e9fd9c63414aa65c8fec6453ca2ffd047.

**Comment by clason** [comment]
Yes, that works nicely (and is of course just as good)! As always, thank you very much for the fast help!
