### ISSUE TITLE
Build errors undetected

### ISSUE THREAD

**Issue by yadayadaydadaa** [latex-lsp/texlab#281]
I'm not sure if this is a bug in texlab or texlab-vscode, but I'll start reporting it here—feel free to reassign.

Trying to build the following file defining `\norm` via `\newcommand` results in no errors according to texlab-vscode, although the file is clearly broken. If `\norm` is defined via `\def`, the errors are correctly reported.

```latex
\documentclass{article}

\newcommand{\norm}[1]{\|#1\|}
% \def\norm#1{\|#1\|}

\begin{document}

this fails silently $\norm{a

\end{document}
```

For the record, the relevant parts of log file (for the `\newcommand` version) look as follows:

```
⋮
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <5> on input line 9.
)
Runaway argument?
{a \par \end {document} 
! File ended while scanning use of \norm.
<inserted text> 
                \par 
<*> test
        
I suspect you have forgotten a `}', causing me
to read past where you wanted me to stop.
I'll try to recover; but if the error is serious,
you'd better type `E' or `X' now and fix your file.

! Emergency stop.
<*> test
        
*** (job aborted, no legal \end found)
⋮
```

For the `\def` version, by contrast, the error is `! Paragraph ended before \norm was complete.` (instead of “File ended” as above).

**Comment by LiHRaM** [comment]
I did not have this issue in the old version of texlab, but with the latest (3.0.0), it seems to not work anymore.
Specifically, if using `mathit` outside of math mode, the log will emit:
```log
! LaTeX Error: \mathit allowed only in math mode.
```

But it will not appear in the problems pane.

**Comment by pfoerster** [comment]
> I did not have this issue in the old version of texlab, but with the latest (3.0.0), it seems to not work anymore.
Specifically, if using mathit outside of math mode, the log will emit:

It looks like a file watching issue to me. If you restart `texlab` or edit the document, does it fix the issue? If so, then, the latest commit on the master branch should fix the issue.

**Comment by LiHRaM** [comment]
The latest update fixes the issue. Thanks a lot!
