### ISSUE TITLE
Issue with texlab and jupyterlab-lsp

### ISSUE THREAD

**Issue by BrandenEsses** [latex-lsp/texlab#305]
Hi! I apologize if this is not the proper place. I am having some issues getting texlab to work with Jupyter Notebook. I am getting this right when I interact with a .tex file in Jupyter (jupyterlab-lsp attempts to highlight and give function signatures, etc.), and it seems to be on the texlab side rather than Jupyter:
```
thread 'main' panicked at 'Could not deserialize parameter object: Error("invalid type: null, expected struct InitializedParams", line: 0, column: 0)', /home/runner/work/texlab/texlab/crates/jsonrpc/src/server.rs:49:18
stack backtrace:
[I 2020-09-06 05:13:55.165 SingleUserNotebookApp log:174] 200 PATCH /user/besses/api/sessions/783b6479-10b0-487a-a94d-2c51d54f5084?1599390831441 (besses@::ffff:127.0.0.1) 1.87ms
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: <texlab::server::LatexLspServer<C> as jsonrpc::server::RequestHandler>::handle_notification::__handle_notification::{{closure}}
  15: <std::future::GenFuture<T> as core::future::future::Future>::poll
  16: texlab::main::{{closure}}
  17: std::thread::local::LocalKey<T>::with
  18: texlab::main
  19: std::rt::lang_start::{{closure}}
  20: main
  21: __libc_start_main
  22: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I noted that the file and path at the beginning `/home/runner/work/texlab/texlab/crates/jsonrpc/src/server.rs` does not exist. This only occurs once, and then over and over again the following appears:
```
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///path/main.tex","languageId":"latex","text":"\\documentclass TONS OF TEX\\end{document}\n\n","version":0}}}
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyter_lsp/stdio.py", line 161, in write
        await convert_yielded(self._write_one(response.encode("utf-8")))
      File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.8/dist-packages/jupyter_lsp/stdio.py", line 169, in _write_one
        self.stream.write(message)
    BrokenPipeError: [Errno 32] Broken pipe
[E 2020-09-06 05:13:55.304 SingleUserNotebookApp stdio:163] <LspStdIoWriter(parent=<LanguageServerSession(language_server=texlab, argv=['/usr/bin/texlab'])>)> couldn't write message: Content-Length: 15465
```

I do not know how to proceed. I would really like to take advantage of the `RUST_BACKTRACE=full` option, but I am not sure how seeing as the debug output in Jupyter does not tell me what command was run to produce the error.

I installed texlab from source using `cargo install --git https://github.com/latex-lsp/texlab.git`

Let me know if I can provide any more information!

**Comment by pfoerster** [comment]
> it seems to be on the texlab side rather than Jupyter:

The problem is that, `juptyer-lsp` uses a faulty protocol implementation. According to the LSP specificiation, the params of the `initialized` notification needs to have the type `InitializedParams` (which is the same as `{}` at the moment) and `juptyer-lsp` instead sends `null`, which our server rejects. It is a bit odd that `texlab` crashes completely when encountering this message. I will look into that but nevertheless, the problem is that `texlab` won't work without a well-formed `initialized` notification (because there is some import setup happening there). The other problem will fix itself once the initialized notification is handled correctly in `juptyper-lsp`. I recommend reporting an issue over at `juptyer-lsp` to get this fixed.

**Comment by BrandenEsses** [comment]
Thanks for your reply! I learned precisely what you explained above, and was able to resolve it through [this issue](https://github.com/krassowski/jupyterlab-lsp/issues/337) with the folks over at jupyter-lsp.
