### ISSUE TITLE
disable some chktex warnings

### ISSUE THREAD

**Issue by DunderBird** [latex-lsp/texlab#309]
How can I disable some chktex warnings? Can I pass args to chktex through some settings?
example:
I want to disable warning 3:
![chktex](https://user-images.githubusercontent.com/45700895/91923284-8973b300-ed02-11ea-8d0e-0c6ef4fb154a.PNG)
Thanks.

**Comment by pfoerster** [comment]
You can now disable ChkTeX warnings with a `chktexrc` file placed in the root folder with PR #408.

**Comment by ModProg** [comment]
We only support `chktexrc` on Linux `.chktexrc` is used instead: 
http://tug.ctan.org/systems/doc/chktex/ChkTeX.pdf Page 10
