### ISSUE TITLE
Thread main panicked quitting file

### ISSUE THREAD

**Issue by motorto** [latex-lsp/texlab#310]
Hi , I am using vim-lsc and texlab (the precompiled one,last version), on quitting files , I get this error.

https://imgur.com/a/mzanLLI

Sorry about the pic , but can't seem to copy and paste that ...

**Comment by pfoerster** [comment]
Thanks for the report. Can you try running `texlab` with `-vvvv --log-file texlab.log` in order to obtain a log file? From the panic message, it looks like `texlab` is receiving an invalid response or has trouble parsing a specific response.

**Comment by motorto** [comment]
Thanks for the reply! 

Here is it running with `-vvvv --log-file texlab.log` option

http://ix.io/2ybe

**Comment by pfoerster** [comment]
Thanks for the log. The issue is caused by a missing `params` property in the last `JSON-RPC 2.0` request. According to the JSON-RPC spec, a request *must* always have this property. The LSP spec on the other hand uses the `void` type for the `params`, which is pretty strange. I recommend opening an issue over at `vim-lsc` and fix the issue there since I am not aware of any client except `vim-lsc` that omits the `params`.

**Comment by motorto** [comment]
Thank you ! Opened the issue there .

**Comment by natebosch** [comment]
https://www.jsonrpc.org/specification#request_object

> **params**
> A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.

Which spec are you reading that states that it must be included?

**Comment by motorto** [comment]
@pfoerster  any intention to make the ```params``` optionally ?

**Comment by pfoerster** [comment]
@motorto Yes, I am currently working on texlab 3.0, which will fix this issue (and a lot of other ones).

**Comment by cansurmeli** [comment]
I'm having the same issue. Except in my case, my fans also go wild during a file edit and it may or may not crash my Vim session. But it definitely takes a long time to Exit Vim afterwards and it might still freeze during the exit.

So based on the above discussion, I guess texlab 3.0 will fix this issue but for the meantime, how can we handle this issue? Is it on texlab's side or vim-lsc's?

**Comment by motorto** [comment]
Hi,

The issue is on Texlab side, it assumes something that isn't on
protocol(that causes this issue , the fans spinning really hard also
happened with me but obly when exiting a file). 

At the moment I don't think that we can do something about it unfortunatly
I dont edit a lot of latex documents so I rarely use this language
server(ls).

If you happened to use latex a lot, and do really need a ls working ,I
think that temporarly using coc.nvim is a solution (assuming that you
dont want to move way from vim)

Best Regards,

**Comment by cansurmeli** [comment]
Hey,

Thanks for the suggestion.

Best.
