### ISSUE TITLE
Perl process leftover

### ISSUE THREAD

**Issue by liuhaowen478** [latex-lsp/texlab#315]
On windows, when I quit vs code or manually cancel build, the perl interpreter is not terminated and I have to manually end those processes. I'm not sure if this is an extension issue or a language server issue.

```
"latex.build.args": [
        "-pdf",
        "-interaction=nonstopmode",
        "-synctex=1",
        "%f",
        "-pvc"
    ]
````

**Comment by pfoerster** [comment]
Sorry for the late response. Using the `-pvc` flag is no longer recommended because `texlab` has its own rebuilding mechanism. See https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md#previewing for more information.
