### ISSUE TITLE
(Free)BSD support

### ISSUE THREAD

**Issue by JensHeinrich** [latex-lsp/texlab#320]
Add build and test of (Free)BSD as plattform

[16d96fa builds on FreeBSD and `cargo test` reports 111 passed]

**Comment by pfoerster** [comment]
It looks like `texlab` has been packaged for [FreeBSD](https://www.freshports.org/devel/texlab) and [NetBSD](https://pkgsrc.se/print/texlab) 🚀.

CC: @MuhammadMouradG
