### ISSUE TITLE
Build on save enabled by default?

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#33]
It seems that the language server by default builds the current TeX file on save. This conflicts with my `vimtex` plugin, which offers a similar function (but with more features such as call-backs which update the PDF viewer on success and opens an error list on failure).

Is there any way to disable this functionality (or make it opt-in)?

**Comment by pfoerster** [comment]
Building after save is now disabled by default. We never intended it to be enabled by default. One can opt-in/opt-out using the workspace/configuration request. Unfortunately, vim-lsp does not seem to support this request (yet). A list of all settings can be found on our [website](https://texlab.netlify.com/docs/reference/configuration).

**Comment by clason** [comment]
Thank you! I'll be happy to open an issue about that on vim-lsp.

(It seems that the promise of LSP interoperability quickly turns to dust once you leave the beaten path between VS Code and TypeScript servers...)

**Comment by clason** [comment]
Hmm... vim-lsp claims to support configuration: https://github.com/prabirshrestha/vim-lsp/blob/d542bbc5a3b0b2d78552a11f4edfee1c55fc3796/doc/vim-lsp.txt#L552

Is that not enough, or is that simply not working (properly)?

**Comment by pfoerster** [comment]
Hmm, I think they support the `initialziationOptions` field of the `InitializeParams` interface (see https://microsoft.github.io/language-server-protocol/specification#initialize). However, this is not the same as the [workspace/configuration](https://microsoft.github.io/language-server-protocol/specification#workspace_configuration) request. vim-lsp responds with a "method not found" error if TexLab sends this request (which it does not do anymore if the client does not support it).
The log from issue #22 shows that vim-lsp does not support this request:

```
Thu 27 Jun 2019 02:40:55 PM CEST:["--->", 5, "texlab", {"method": "textDocument/formatting", "on_notification": "---funcref---", "sync": 0, "params": {"options": {"insertSpaces": true, "tabSize": 8}, "textDocument": {"uri": "file:///home/clason/Dropbox/tex/NonsmoothBook/nonsmooth.bib"}}}]
Thu 27 Jun 2019 02:40:55 PM CEST:["<---", 5, {"method": "workspace/configuration", "jsonrpc": "2.0", "id": 1, "params": {"items": [{"section": "bibtex.formatting"}]}}]
Thu 27 Jun 2019 02:40:55 PM CEST:["--->", 5, "texlab", {"id": 1, "error": {"code": -32601, "message": "Method not found"}}]
Thu 27 Jun 2019 02:40:55 PM CEST:["<---(stderr)", 5, "texlab", ["TRACE - Received message:", "{\"id\": 2, \"jsonrpc\": \"2.0\", \"method\": \"textDocument/formatting\", \"params\": {\"options\": {\"insertSpaces\": true, \"tabSize\": 8}, \"textDocument\": {\"uri\": \"file:///home/clason/Dropbox/tex/NonsmoothBook/nonsmooth.bib\"}}}", "TRACE - Sent message:", "Content-Length: 112\r", "\r", "{\"jsonrpc\":\"2.0\",\"method\":\"workspace/configuration\",\"params\":{\"items\":[{\"section\":\"bibtex.formatting\"}]},\"id\":1}", ""]]
Thu 27 Jun 2019 02:40:55 PM CEST:["invalid response id. ignoring message", {"id": null, "jsonrpc": "2.0", "error": {"code": -32700, "message": "Could not parse the input"}}]
Thu 27 Jun 2019 02:40:55 PM CEST:["<---(stderr)", 5, "texlab", ["TRACE - Received message:", "{\"id\": 1, \"jsonrpc\": \"2.0\", \"error\": {\"code\": -32601, \"message\": \"Method not found\"}}", "TRACE - Sent message:", "Content-Length: 89\r", "\r", "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32700,\"message\":\"Could not parse the input\"},\"id\":null}", ""]]
```

**Comment by clason** [comment]
Thanks, reported up(down?)stream: https://github.com/prabirshrestha/vim-lsp/issues/426

**Comment by clason** [comment]
Is there some standardized way for client and server to announce the version of the protocol they are supporting? Looking at the changelog, the specification gets so much churn, I wonder how LSP is actually supposed to work in practice...

**Comment by pfoerster** [comment]
Both client and server send a list of capabilities they support when initializing the connection.
See the `ClientCapabilities` and `ServerCapabilities` interfaces for more information (https://microsoft.github.io/language-server-protocol/specification#initialize).

**Comment by clason** [comment]
Ah, ok, that makes sense! So this was not working because vim-lsp (still) does not send properly formatted json 2.0 messages.

**Comment by pfoerster** [comment]
Yeah, we falsely assumed that all clients support the workspace/configuration request.
After requesting the configuration, vim-lsp does not send a properly formatted JSONRPC-2.0 message, which in turn crashes our server.

**Comment by clason** [comment]
Well, if nothing else, texlab and vim-lsp are excellent stress tests for each other :grin:
