### ISSUE TITLE
Server install fails in wsl2 (Ubuntu-20.04)

### ISSUE THREAD

**Issue by hsmyers** [latex-lsp/texlab#332]
Claims that it is unable to determine what TeX distro I'm running…I'm running a TeX-Live with extensions, BTW.

**Comment by pfoerster** [comment]
Thanks for the report. I am assuming you are running `texlab` outside of WSL. In this case, we do not have implemented scanning the Tex Distro yet. However, this issue should not prevent you from using the language server, as detecting the TeX distro is only required for one feature, namely providing completion for locally-installed packages. If you are not using this feature, then `texlab` should work perfectly fine. Just ignore the message for now. In the next version, this will be a warning in the log, and not a message anymore. In addition to that, I will add support for detecting distributions inside WSL.

**Comment by pfoerster** [comment]
Closing this issue:
- `texlab` no longer reports this warning message
- Running language servers inside WSL has become quite easy so it is much simpler to run `texlab` inside WSL too
