### ISSUE TITLE
How to set up a previewer

### ISSUE THREAD

**Issue by onekk** [latex-lsp/texlab#333]
Hi, I've read the documentation, but for a not latexmk toolchain there is no information about setting up a toolchain for the previewer.

I'm using VSCODE (code-OSS) as editor.

I've set something in settings.json

`"latex.build.executable": "arara",
    "latex.build.args": [
        "-v",
        "%f"
    ],
    "latex.forwardSearch.executable": "zathura",
    "latex.forwardSearch.args": [
        "--synctex-forward", "%l:1:%f", "%p"
    ]`

But I've achieved only to open a zathura window with no content.

Regards

Carlo D.

**Comment by onekk** [comment]
I've managed to set the toolchain.

Arara is working with:

```
"latex.build.executable": "arara",
    "latex.build.args": [
        "-v",
        "%f"
    ],
    "latex.forwardSearch.executable": "zathura",
    "latex.forwardSearch.args": [
        "--synctex-forward", "%l:1:%f", "%p"
    ],
     "latex.build.forwardSearchAfter": true
```

Just in case someone is interested in thius setting.

Myse it will be a good thing to put it in documentation.

Some little drawback is the highlighting of the preview.

System: Linux
Distribution arch linux (artixlinux to be more precise).

Thanks and Regards

Carlo D.

**Comment by pfoerster** [comment]
> Myse it will be a good thing to put it in documentation.

With the latest version, `texlab` no longer relies on `latexmk` for previewing. Instead, one can use `texlab.build.forwardSearchAfter: true`, which is now covered in the documentation.
