### ISSUE TITLE
disable formatting for section

### ISSUE THREAD

**Issue by Louis9902** [latex-lsp/texlab#338]
Is there any way to tell texlab to not mess with formatting for a certain block like:
```tex
\beging{code}{c}
struct person {
}
typedef struct person person
\end{code}
```
If not something like a comment before and after the block would be nice like so:
```tex
% format:off
\beging{code}{c}
struct person {
}
typedef struct person person
\end{code}
% format:on
```

**Comment by pfoerster** [comment]
Thanks for the report. `texlab` uses `latexindent` for formatting. I think you can configure `latexindent` to ignore certain blocks like your `code` environment. Try adding
```yml
verbatimEnvironments:
    code: 1
```
to your `defaultSettings.yaml`.

**Comment by Louis9902** [comment]
okay, thank you very much, feel free to close the issue or keep it open if you consider adding support to texlab.
Keep up the amazing work.
