### ISSUE TITLE
neovim lsp: path problems with separate outputDirectory

### ISSUE THREAD

**Issue by matu3ba** [latex-lsp/texlab#345]
```lua
lua << EOF
local on_attach_vim = function()
  require'completion'.on_attach()
end
require'lspconfig'.texlab.setup {on_attach=on_attach_vim,
                      \   cmd = {'texlab'},
                      \   filetypes = {'tex', 'bib'},
                      \   settings = {
                      \     latex = {
                      \       build = {
                      \         args = { '-pdflatex=lualatex', '-pdf', '-interaction=nonstopmode', '-synctex=1', '%f'
                      \         },
                      \         executable = {'latexmk'},
                      \         outputDirectory = {'build'},
                      \       }
                      \     }
                      \   }
                      \ }
EOF
```
This option breaks completion suggestions and showing layout problems.
`:echo expand('%f')` results in the filepath as expected.

Removing %f makes the completion suggestions work, but not showing the layout problems.

Is this known to be broken for `lualatex`?

**Comment by pfoerster** [comment]
Thanks for the report. 

The documentation is a bit unclear on this matter but you need to set the `latexmk` output directory as well. The `outputDirectory` setting is only used to tell `texlab` where to look for aux files and log files. So you need to add the `-output-directory=build` flag to the `args`, too.

**Comment by matu3ba** [comment]
So
```lua
...
   settings = {
     latex = {
       build = {
         args = { '-pdflatex=lualatex', '-pdf', '-interaction=nonstopmode', '-synctex=1', '-output-directory=build', '%f'
         },
         executable = {'latexmk'},
         outputDirectory = {'build'},
       }
     }
   }
...
```
and
```vim
function! Latexmk()
  let l:cmd = "terminal latexmk -pdflatex=lualatex -pdf -outdir=build " .. expand("%") | tabnew | execute cmd
endfunction
```
are correct?

Code completion works, but I dont see layout warnings.

What should minimal test files (test.tex and text.bib) contain to check a correct setup? I cant find any files with ending .tex in the repo on github.

**Comment by matu3ba** [comment]
@pfoerster polite ping

**Comment by pfoerster** [comment]
Sorry for the late response. If code completion works, then there is no problem regarding the workspace layout. You can verify this by using the following test documents:

main.tex:
```
\usepackage{lipsum}
\input{child.tex}
```
child.tex:
```
\lipsu
```

Try to trigger the code completion in the second file and see if it suggests `lipsum`. If it ends up working, then there is nothing wrong regarding the workspace analysis. It may be due to #339, which I have already fixed in texlab 3.0. However, I need a bit more time to finish texlab 3.0, which will be powered by `tree-sitter`. As a workaround, you can try editing the document to see if it reports errors after typing a character (file watching is a bit broken in texlab 2.x). Another thing you can do is posting the log file here if it is possible for you. You can strip personal information if necessary. I can then try to find an error in the log file parser.

**Comment by pfoerster** [comment]
@matu3ba `texlab 3` has been released in the meantime, which should fix this problem. Please let me know if it works for you. Note that there some breaking changes regarding the options format. Please see [here](https://github.com/latex-lsp/texlab/blob/master/docs/options.md) for a detailed documentation.

**Comment by matu3ba** [comment]
@pfoerster Will test once I have the documents from the institute/my advisor to write my thesis.

**Comment by matu3ba** [comment]
Issue resolved.

**Comment by matu3ba** [comment]
@pfoerster Did you end up using `treesitter` ? The README does not mention it and I dont see an ARCHITECTURE.md or anything related.

**Comment by pfoerster** [comment]
@matu3ba No, I did not end up using `tree-sitter` after all. Two of the main reasons why I did not end up using it were performance and error handling.

**Comment by Neur1n** [comment]
I have similar issue when using texlab 3.2.0 with coc-texlab. I've set `texlab.auxDirectory` to `build` (also ./build, ./build/) and add `-output-directory=build` to `texlab.build.args`. The PDF and aux files are output to `build` directory in my workspace, but forward search didn't work (it worked if I copy the PDF to the directory of the tex file).

**Comment by pfoerster** [comment]
@Neur1n The issue should be fixed now on the latest master branch. It was related to the fact that `texlab` did not reanalyze all documents after receiving the initial configuration.

**Comment by SirLukeSchande** [comment]
For me this issue still persists. Am I the only one?

**Comment by matu3ba** [comment]
@SirLukeSchande Please file a new issue with the exact command instructions for the repl/shell and the lsp config of your editor. Probably you have an old `texlab --version` provided by your distribution or you have it installed locally.
