### ISSUE TITLE
Latest latex-lsp + texlab just freezes Emacs. Is texlab trying to ping home?

### ISSUE THREAD

**Issue by liar666** [latex-lsp/texlab#371]
Hi,

I'm trying to test `latex-lsp` (latest from gnu/melpa) + `texlab` (latest from repo).

When I open a `.tex` file (e.g. below) then move the cursor inside it, Emacs just freezes. What's strange is that most of the time (particularly when opening emacs with the file as argument on the command line) Emacs is stuck for "ever", but if I `pkill texlab` then answer "yes" when Emacs asks if I want to restart the lsp server (i.e. texlab), then it will freeze again as sonn as I move the cursor in the tex file buffer, but sometimes only for a few seconds...

FYI I'm behind corporate proxy, so would it be the case that texlab is trying to "ping" home and get stuck while waiting for the timeout because the proxy is not configured in Emacs?

The tex file is use:
```
\documentclass[11pt,french,a4paper,twoside,
xcolor={pdftex,svgnames}, % dvipsnames, dvipsnames*, svgnames, svgnames*, x11names
]{article}  % draft % report/book
\usepackage{hyperref}
\hypersetup{%
    pdftitle={...},%
    pdfauthor={...},%
    pdfsubject={...},%
    pdfkeywords={...}%
}

% Correct French/English indentation and splitting of words
\usepackage{babel}

% Correct management of accentuated chars in input file
% \usepackage[latin1]{inputenc}
\usepackage[utf8]{inputenc}

% Correct font for the generation of docs with accentuated chars
\usepackage[T1]{fontenc}      % Can handle hyphenation of words with accented characters
%%\usepackage[OT1]{fontenc}   % Might generated bad looking PDFs

% Access to many maths symbols
\usepackage{amsthm}
\usepackage{amsmath}
\usepackage{amsfonts}

% Insertion of images generated by external tools
\usepackage{graphicx}

% To generate pretty & scalable images directly in LaTeX
\usepackage{tikz}
% \draw[decorate,decoration={coil,amplitude=1.5cm, segment length=.4cm}] (5,5.5) -- (5,1.5) ;
\usetikzlibrary{decorations.text}
\usetikzlibrary{decorations.shapes}
\usetikzlibrary{decorations.pathmorphing,snakes}

% To print numbers correctly
\usepackage{numprint}

\usepackage{vmargin}
%\setpapersize{A4}
%\setmarginsrb{ leftmargin }{ topmargin }{ rightmargin }{ bottommargin }{ headheight }{ headsep }{ footheight }{ footskip }
%\setmargrb{ leftmargin }{ topmargin }{ rightmargin }{ bottommargin }%
%%\pagestyle{empty}

% Info for title page
\title[<short?>]{...}
\author[<short?>]{... \and ...}
\date[<short?>]{\today{}}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}

% The title page
\maketitle

% The TOC
\tableofcontents

\part{}

%\chapter{} %% For report/book
\section{}
\subsection{}
\subsubsection{}


\end{document}


%%% Local Variables:
%%% mode: latex
%%% TeX-master: t
%%% End:
```

**Comment by pfoerster** [comment]
Thanks for the report.
`texlab` used to connect to CTAN to obtain package documentation but we replaced this feature a long time ago in favor of pre-computing the entire documentation from a package index. Too me, it looks like `texlab` is stuck in an infinite loop when trying to analyze the workspace dependencies. In the past, we had an issue (or still have) with freezing related to weird document URIs in Emacs. I cannot reproduce this issue with VSCode, for example. There is no networking functionality in `texlab`. Can you try posting a log file here using `texlab -vvvv --log-file texlab.log`?

**Comment by swarnendubiswas** [comment]
I experience high CPU usage with `texlab` and Emacs v27.1. The profiler often indicates large overheads from automatic gc and to parse the `JSON` logs. I set `lsp-log-io` to `nil`.

**Comment by liar666** [comment]
Hi, thanks for the quick answer,

> -vvvv --log-file texlab.log
Unfortunately I can't find a way to add arguments to the texlab command launched from Emacs.
I've unsuccessfully tried:
- adding the following line in my `.emacs.d/config.org`:
`(setq lsp-clients-texlab-executable "~/Softs/TeXLab/texlab <arg>")`
but then Emacs does not succeed launching texlab
- creating an alias in bash, then run Emacs (without the above line in the config => Emacs automatically finds texlab in the path)

I can't find any help or customization related to "textlab" or "lsp-clients".

Any ideas?

**Comment by swarnendubiswas** [comment]
Try something like this.

```
(use-package lsp-latex
  :hook
  ((latex-mode LaTeX-mode) . (lambda()
                               (require 'lsp-latex)
                               (lsp-deferred)))
  :custom
  (lsp-latex-bibtex-formatting-formatter "latexindent")
  (lsp-latex-bibtex-formatting-line-length sb/fill-column)
  (lsp-latex-build-on-save t)
  (lsp-latex-lint-on-save t)
  :config
  (setq lsp-latex-texlab-executable-argument-list
        '("-vvvv" "--log-file" "texlab.log"))
  (add-to-list 'lsp-latex-build-args "-c")
  (add-to-list 'lsp-latex-build-args "-pvc"))
```

**Comment by liar666** [comment]
Thanks...
(Un)fortunately, the logs end up empty and Emacs/latex-lsp/texlab seem to be working now... So I won't be able to provide more info, thus I close the issue, but all of you gave enough info so that if it occurs again to me or someone else, s/he will be able to reopen the issue. 
Thanks again!
PS: Now it's jdee/lsp-java that freezes on "starting beanshell" when opening a `.java` file :{
