### ISSUE TITLE
Build is not working dispite successful signal

### ISSUE THREAD

**Issue by ROCKTAKEY** [latex-lsp/texlab#372]
Hi! Thanks for your maintenance!

After textDocument/build was sent from the Emacs lsp-latex, texlab executable returned status 0, even though latexmk compiled nothing. Log is below.
Please see line 6149 and 6212. Here is sent and recieved message about building.

https://github.com/ROCKTAKEY/lsp-latex/issues/23#issuecomment-778340207

cc @swarnendubiswas

**Comment by pfoerster** [comment]
Sorry for the late response. This should (hopefully) be fixed with `texlab 3.0.0`. It looks like it was an encoding issue which caused to `latexmk` to crash because `texlab` closed the `stdout` stream too early.

**Comment by ROCKTAKEY** [comment]
Thanks! 
@swarnendubiswas Is it works?

**Comment by swarnendubiswas** [comment]
Thanks for the update. 

Please give me some time, I have switched over to using AucTeX meanwhile.
