### ISSUE TITLE
Cannot detect user-defined package

### ISSUE THREAD

**Issue by Complex2-Liu** [latex-lsp/texlab#383]
os: `macOS Big Sur`
Editor: `neovim`

I create my own package(say `homework.sty`) and put it into the directory `~/Library/texmf/tex/latex/homework`. When I write `$\usepackage{homwo}$`, there is no candidate list of completion. ~~However, Fortunately, my custom command such as `\DeclarePairedDelimiter{\floor}{\lfloor}{\rfloor}` in `homework.sty` can be detected when I write `$\flo$` in some `.tex` file.~~

I wonder why my own package cannot be detected?

Edit: **My custom command cannot be detected as well!!**

Assume my working directory is `~/2021-work/`. If I put `homework.sty` and `main.tex` in the same folder(`2021-work`), then every command is fine. But otherwise every command(except built-in command) cannot be detected, for example `\qedhere`, a command provided in `amsthm`(I write `\usepackage{amsthm}` in my own package).

**Comment by pfoerster** [comment]
Thanks for the report.

It looks like there is something wrong with detecting the TeX distribution files.
Can you check if kpsewhich is part of the PATH variable? Texlab needs this executable to find the `texmf` directories. 
Does `kpsewhich homework.sty` find your custom package? If it works when the package and the other file are in the same directory, then there should be nothing wrong with the command detection part.

**Comment by Complex2-Liu** [comment]
I write `echo $PATH` and obtain `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin`, kpsewhich is located in `/Library/TeX/texbin`.

`kpsewhich homework.sty` successfully find my custom package in `/Users/complex2liu/Library/texmf/tex/latex/homework/homework.sty`

If I write `\usepackage{amsthm}` and my cursor is amid the word amsthm, then typing `gf` can go to the file `amsthm.sty`. However, when `amsthm` is replaced by my custom package `homework`, typing `gf` obatin `E447: Can't find file "homework" in path`. I have no idea what is going on.
