### ISSUE TITLE
\newcommand* does not work in equation preview

### ISSUE THREAD

**Issue by linwaytin** [latex-lsp/texlab#389]
Thanks for this nice language server. This is definitely a must-have for latex.

The equation preview function is great, but it seems it cannot take the `\newcommand*` defined in the preamble into account.
Is there a way to make it work, or it is not supported yet?
My `texlab` version is 2.2.2.

**Comment by pfoerster** [comment]
Thanks for the nice words. This is an easy fix, see b91a4541c136545eb4e3360b89531cb6231d344a. You can try it out by installing `texlab` using 
  `cargo install --git https://github.com/latex-lsp/texlab.git --locked`.

**Comment by linwaytin** [comment]
Thanks. This will be helpful.

I noticed that `\renewcommand` has no starred version.
I would suggest adding a starred version for completeness.

**Comment by pfoerster** [comment]
Previewing an equation is no longer a part of the server due to the reasons outlined in #501. Closing in favor of #501.
