### ISSUE TITLE
Linting on text edit?

### ISSUE THREAD

**Issue by oblitum** [latex-lsp/texlab#39]
I'm using texlab through [coc-texlab](https://github.com/fannheyward/coc-texlab) on [neo]vim, but I also use [ALE](https://github.com/w0rp/ale) (with `let g:ale_lint_on_insert_leave = 1` and `let g:ale_lint_on_text_changed = 'normal'` to avoid linting on every character input, but still have it after normal mode edits and when leaving insert mode). I'm currently getting diagnostics after text edits solely through ALE (it's picking it from `chktex`), not from texlab. texlab only provides diagnostics on file save. I wish I could get diagnostics on the fly, so I could disable ALE.

**Comment by oblitum** [comment]
FWIW, ALE pick linters available in PATH automatically, but I don't like `lacheck` because it gives too many false positives and doesn't provide a configuration file like `chktex` so I could disable those warnings, so I simple disable `lacheck` entirely with ALE.

**Comment by pfoerster** [comment]
I have added a new setting called `latex.lint.onChange`. Setting it to `true` will run the linter after a series of changes have been made to the document. Note that it is up to the client to decide how a series of changes is implemented. For example, VSCode sends the `textDocument/didChange` notification after every keystroke.  Vim might send a notification after leaving insert mode. However, I'm not sure about that. Does 8ced566f5208850ffc8fcb56064a027fa0d5a793 fulfill your needs?

**Comment by oblitum** [comment]
> Does 8ced566 fulfill your needs?

Yes thanks, I just built from master and it's now working like other coc.nvim extensions.

FWIW I've set this configuration from my `.vimrc`:

```vim
call coc#config('latex', {
\   'lint.onChange': v:true
\ })
```

Now, it would be nice to have a new feature release so that [coc-texlab](https://github.com/fannheyward/coc-texlab) picks it automatically.
