### ISSUE TITLE
Publishing on crates.io

### ISSUE THREAD

**Issue by carlosala** [latex-lsp/texlab#399]
Hi!
Would be great to have the package on [crates.io](https://crates.io). It's very easy to publish there, and would be easier to install `texlab`, just typing `cargo install texlab`.
I left you [here](https://doc.rust-lang.org/cargo/reference/publishing.html) the docs to publish on there!
Thanks!

**Comment by pfoerster** [comment]
`texlab 4.0.0` is now available on [crates.io](https://crates.io/crates/texlab) 🚀
