### ISSUE TITLE
How to set preview in nvim

### ISSUE THREAD

**Issue by jkunlin** [latex-lsp/texlab#40]
Does it possible to set up the previewing and build on save in nvim just like vimtex?
I see the document here https://texlab.netlify.com/docs/installation/previewing. But have no idea how to configure in nvim.

**Comment by jkunlin** [comment]
I am using coc as the LSP client in nvim

**Comment by pfoerster** [comment]
Building on save is turned off by default.
However, you can enable it by setting `latex.build.onSave` to `true`.
As far as I know, the language server can be configured using `:CocConfig` (see https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file#configuration-file-resolve). Then you can paste the following snippet:

```json
{
    "latex.build.onSave": true
}
```

and save the file. Now, TexLab should build your documents using `latexmk`
every time you save a document. `latexmk` is responsible for calling your PDF viewer.
See https://texlab.netlify.com/docs/installation/previewing for more instructions. Additional settings can be found on our [website](https://texlab.netlify.com/docs/reference/configuration).

**Comment by jkunlin** [comment]
I add the following line to my `~/.latexmkrc` file: ``$pdf_previewer = 'start okular --unique'; ``
And the coc-setting as follow
`
  "latex.build.args": [
    "-pdf",
    "-interaction=nonstopmode",
    "-synctex=1",
    "-pv"
  ],
  "latex.build.onSave": true,
  "latex.forwardSearch.executable": "okular",
  "latex.forwardSearch.args": [
    "--unique",
    "file:%p#src:%l%f"
  ],
`
But the forward search does not work.

**Comment by efoerster** [comment]
The problem is that forward search can be only implemented with a custom LSP request that the client has to implement. For Vim, there is the [coc-texlab](https://github.com/fannheyward/coc-texlab) extension that will hopefully implement it soon, see issue [#2](https://github.com/fannheyward/coc-texlab/issues/2) on their repo.

**Comment by oblitum** [comment]
No forward search yet but my current setup for preview with coc-texlab is:

`.vimrc`:
```vim
  call coc#config('latex', {
  \   'lint.onChange': v:true,
  \   'forwardSearch.executable': 'zathura',
  \   'forwardSearch.args': ['--synctex-forward', '%l:1:%f', '%p'],
  \   'build.args': ['-pdf', '-interaction=nonstopmode', '-synctex=1', '-pvc']
  \ })
```

Important flag with zathure is `-pvc`, as the example in the wiki uses `-pv`, which launches a new zathura instance on every build, `-pvc` will launch continuous build and just a single instance is launched and updated on write. Not sure about a way to stop though.

**Comment by fannheyward** [comment]
coc-texlab has added `latex.ForwardSearch`, give it a try.

**Comment by jkunlin** [comment]
Thanks very much! It works with okular.
