### ISSUE TITLE
VSCode extension does not recognise TeX distribution (MacTex) 

### ISSUE THREAD

**Issue by Starostka** [latex-lsp/texlab#404]
I have MacTex installed on my system and Tex seems to be recognized by my shell.

Ex. upon executing **which tex** : _/Library/TeX/texbin/tex_ 

Source: TexLab (Extension) in VisualStudio Code 
Error: _Your TeX distribution could not be detected. Please make sure that your distribution is in your PATH._

Does anyone know why TexLab is not able to detect my TeX distribution?

**Comment by pfoerster** [comment]
Thanks for the report. Can you try if `kpsewhich` is available in your path? `texlab` needs this executable to find out where to find the `texmf` directories. 

Note that this error is not really an error that prevents you from using `texlab`. In fact, this will become a log message in texlab 3.0 (#408). It is only required when you have installed custom packages that are not available in `texlive-full` and want completion for those packages.

**Comment by Starostka** [comment]
I used PowerShell Core 7.1.3 when I received this error. Not sure why but after switching back to Zsh, it no longer occurs.

**Comment by pfoerster** [comment]
Perhaps, the `kpsewhich` executable was not in your path when using PowerShell Core? Either way, the latest version of `texlab` no longer shows a warning message when starting the server.
