### ISSUE TITLE
[Neovim][master branch] Forward search: search unconfigured

### ISSUE THREAD

**Issue by tiagovla** [latex-lsp/texlab#422]
Forward search is not working anymore on Neovim using the master branch. It outputs ``Search Unconfigured``.

 This feature with the same settings works on v2.2.2 release.  Build still works. Were there any changes?

```lua
require("lspconfig").texlab.setup {
    cmd = {"/home/tiagovla/.cargo/bin/texlab"},
    settings = {
        latex = {
            build = {
                onSave = true,
            },
            forwardSearch = {
                args = {"--synctex-forward", "%l:1:%f", "%p"},
                executable = "zathura",
                onSave = false,
            },
            lint = {onChange = true},
        },
    },
}
```

**Comment by clason** [comment]
You jumped the gun. The settings changed (see the new docs); I'll make a PR to the nvim-lspconfig repo once the release percolates through the repos.

**Comment by clason** [comment]
Also, when you upgrade to new major release, make sure to read the changelog ;)

**Comment by tiagovla** [comment]
> Also, when you upgrade to new major release, make sure to read the changelog ;)

Oooh! I checked the **options.md** but I didn't pay enough attention, it changed from ``latex`` to ``texlab``. I will check the changelog next time, thank you!

**Comment by clason** [comment]
No worries, you just beat me. I submitted a PR with the changed options to nvim-lspconfig: https://github.com/neovim/nvim-lspconfig/pull/909
