### ISSUE TITLE
VSCode extension broken after texlab server update

### ISSUE THREAD

**Issue by coxackie** [latex-lsp/texlab#425]
I am using the VSCode extension with the local texlab server, and after the update to 3.0.0, the extension crashes. I guess this is to be expected; I will downgrade for the time being, but it will be nice to have the extension play nicely with the latest server.

**Comment by clason** [comment]
Isn't this rather an issue with https://github.com/latex-lsp/texlab-vscode?

**Comment by coxackie** [comment]
@clason indeed, I was a bit lazy here, seeing as the dev is the same. I did open the same issue (https://github.com/latex-lsp/texlab-vscode/issues/425) - @pfoerster feel free to close this (duplicate) one.
