### ISSUE TITLE
Logs not parsed for warnings?

### ISSUE THREAD

**Issue by coxackie** [latex-lsp/texlab#426]
I opened https://github.com/latex-lsp/texlab-vscode/issues/426, but on second thoughts I am not sure whether it is an issue with the extension or the server. Maybe someone can take a look at other implementations (like neovim lsp). In short:
Using 3.0.0 versions with settings
```
    "texlab.build.args": [
        "-lualatex",
        "-interaction=nonstopmode",
        "-synctex=1",
        "%f"
    ],
    "texlab.forwardSearch.executable": "zathura",
    "texlab.forwardSearch.args": [
        "--synctex-forward",
        "%l:1:%f",
        "%p"
    ],
    "texlab.chktex.onOpenAndSave": false,
```
Note that I am using `lualatex`. Here is a minimal tex file:
```
\documentclass{article}

\begin{document}

\begin{equation}\label{eq:one}
  a=b
\end{equation}
Equation (\ref{eq:ones}) gives that $a=b$.
    
\end{document}
```
Notice the mistake in using `eq:ones` instead of `eq:one`. When I build, everything seems OK, and there are no warnings. If I go to the log file, there is a clear
```
LaTeX Warning: Reference `eq:ones' on page 1 undefined on input line 9.

[1

{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./Test.aux)

LaTeX Warning: There were undefined references.

)
```
It appears that the parser is missing this from the log file.

**Comment by quid256** [comment]
I'm not a maintainer, but I'm seeing the same issue while using neovim. I tried to hook into the `publishDiagnostics` messages coming from texlab and it appears that they continue sending warning diagnostics to my editor even after those warnings are no longer valid, as well as having the behavior that you mention (i.e. not sending warnings when a new warning is introduced)

**Comment by wrvsrx** [comment]
It seems that this happens after updating texlab to 3.0.0.

**Comment by quid256** [comment]
I tried compiling from source, and it seems that the changes in a7ea0d5f37548d resolved the issue for me.

Would be great if there could maybe be a bugfix release of some kind so that a somewhat stable version of texlab wouldn't have this issue?

**Comment by pfoerster** [comment]
`texlab 3.0.1` has been released now. Can you try it out to see if the problem was fixed?

**Comment by wrvsrx** [comment]
> `texlab 3.0.1` has been released now. Can you try it out to see if the problem was fixed?

Yes, Thank you!
