### ISSUE TITLE
\ref{} completion doesn't work when a line starting with unicode character

### ISSUE THREAD

**Issue by wrvsrx** [latex-lsp/texlab#428]
After defining a label `a`, and type `\ref{}` in vscode, texlab should pop up a completion window with the label `a` in it (see the figure below). 

![image](https://user-images.githubusercontent.com/42770726/119214461-9b4bef00-baf9-11eb-97b9-f9dc6b4cc6fd.png)

However,  after typing `\ref{}` in a line starting with three or more unicode characters, the completion window doesn't appear (see the figure below)
![image](https://user-images.githubusercontent.com/42770726/119214468-b159af80-baf9-11eb-906d-7ba1063d8e84.png)

It seems that this happens after upgrading to 3.0.0.

**Comment by clason** [comment]
Can confirm with standalone texlab (using neovim); even a single non-ASCII char is enough to throw off the completion: try typing
```
ö\ref{
```
and you get completion suggestions based on the `re` part! (Adding more `ö` "shifts" everything further until you get no completion anymore.)

**Comment by clason** [comment]
This looks fixed (for me) with https://github.com/latex-lsp/texlab/commit/e64a494e838e0d4926171eaf3ec24416850f9177

**Comment by wrvsrx** [comment]
It has been fixed in release v3.0.1. Thank you, developers.
