### ISSUE TITLE
Viewer not launched

### ISSUE THREAD

**Issue by ghost** [latex-lsp/texlab#432]
On MacOS, the latest update (3.0.1) stopped launching the viewer (Skim). This happens neither when a build is done or not.  `latexmk -pdf -pv` from the command line has no problem.

**Comment by pfoerster** [comment]
To help fix the issue, I need more info. Can you please share the relevant parts of your `texlab` configuration from VSCode and your `.latexmkrc` file? How does the layout of your project look like? Is everything inside a single folder or is there some nesting?
