### ISSUE TITLE
How to disable automatic compilation after saving in 3.0

### ISSUE THREAD

**Issue by islercn** [latex-lsp/texlab#435]
latex.build.onSave setting has been removed according to https://github.com/latex-lsp/texlab/blob/v3.0.0/CHANGELOG.md

but how can i disable automatic compilation?

**Comment by pfoerster** [comment]
Indeed, `latex.build.onSave` has been removed from the server so there should be no automatic compilation. How did you install the server? Was it bundled with the editor extension? If so, can you please verify, that you do have indeed version 3.0.1 installed (`texlab --version`)? In addition to that, can you share your config, please? Before `texlab 3.0` automatic compilation, was an opt-in feature and not a default.

**Comment by islercn** [comment]
i use texlab 3.0.1, sublime 4, and [https://github.com/sublimelsp/LSP-TexLab](LSP-TexLab), the modified tex file is automatically compiled when i save the changes

**Comment by pfoerster** [comment]
> i use texlab 3.0.1, sublime 4, and https://github.com/sublimelsp/LSP-TexLab, the modified tex file is automatically compiled when i save the changes

I tried reproducing the problem using a fresh Sublime 4 install but I was unable to reproduce the issue. Can you please post your config of `texlab` and relevant parts of your Sublime config? In addition to that, can you create a log file using `texlab -vvvv --log-file texlab.log`, please? As I have already said, the only way `texlab 3.x` compiles your document at the moment is if you trigger the (custom) build request so we need to find out why this request gets sent to `texlab`.
