### ISSUE TITLE
The latest TexLab (v3.0.1) cannot run on Ubuntu 18.04 due to an incompatible GLIBC version.

### ISSUE THREAD

**Issue by linmajia** [latex-lsp/texlab#439]
The latest TexLab requires GLIBC 2.29, however Ubuntu 18.04's version is 2.27.

**Comment by pfoerster** [comment]
It looks like `ubuntu-latest` has been updated between `texlab 2.x` and `texlab 3.0`. I changed the operating system of the CI runner b ack to ubuntu-18.04, which fixes this issue once a new release is made. I will publish a new patch release once #437 is fixed. For now, you can try compiling from source using `rustup`.

CC: @fannheyward

**Comment by linmajia** [comment]
@pfoerster , thank you very much!
