### ISSUE TITLE
Failed to twice-complete in LaTeX eqution environment and trigger the mathematics symbols completion only in equation environments.

### ISSUE THREAD

**Issue by hongyi-zhao** [latex-lsp/texlab#448]
On Ubuntu 20.04, I use the following configuration based on auctex, lsp-mode, company, lsp-latex, and texlab as my tex document preparation environment:

```emacs-lisp
(straight-use-package
 `(auctex :type git :host nil :repo "https://git.savannah.gnu.org/git/auctex.git"
    :pre-build ,(pcase system-type
                (`berkeley-unix '("gmake"))
                (_ '(
                    `("bash" "-c" "cd" ,(straight--repos-dir "auctex"))
                    ("./autogen.sh")
                    ("./configure" "--without-texmf-dir" "--with-lispdir=.") 
                    ("make")
                    )))))

     (setq TeX-data-directory (straight--repos-dir "auctex")
           TeX-lisp-directory TeX-data-directory)                   
    
; Or set the following variable via custom-set-variables in the opened buffer by the following command.
; M-x describe-variable RET preview-TeX-style-dir RET
;`(preview-TeX-style-dir ,(concat ".:" (straight--repos-dir "auctex") "latex:"))
(setq preview-TeX-style-dir (concat ".:" (straight--repos-dir "auctex") "latex:"))

(load "auctex.el" nil t t) 
(load "preview-latex.el" nil t t)

(setq TeX-auto-save t)
(setq TeX-parse-self t)
(setq-default TeX-master nil)


(use-package company)
(setq company-idle-delay 0) 
(setq company-minimum-prefix-length 1)

(use-package lsp-mode)
(require 'lsp-mode)

(use-package lsp-latex
  :straight (:host github :repo "ROCKTAKEY/lsp-latex"))

(require 'lsp-latex)

(add-hook 'TeX-mode-hook 'lsp)
(add-hook 'TeX-mode-hook #'company-mode)
```
Though it works, but I still meet some strange problems as described below, which I've discussed originally [here](https://github.com/ROCKTAKEY/lsp-latex/issues/29#issuecomment-866841133).

 If I try to use the completion in mathematical environment, i.e, between `$$`, the first time it will be completed successfully: 

![image](https://user-images.githubusercontent.com/11155854/123103661-d038c200-d468-11eb-968d-f92765e290dc.png)

If I delete the already entered result with backspace between the `$$`, and then re-enter the same or other mathematical symbols, the completion won't be done again, as shown below:

![image](https://user-images.githubusercontent.com/11155854/123104072-332a5900-d469-11eb-8da1-37446e5584be.png)

But if I am not in mathematics/equation environments, the problem will only appear rarely. 

In addition, I only want to trigger the mathematics symbols completion in equation environments, and other LaTeX commands in normal writing environments. Is this possible? At the same time, I want to have the `ispell` based (on-the-fly) spell checker.

How to solve these problems / achieve these goals?

Regards,
HY

**Comment by clason** [comment]
I can reproduce something similar in neovim with a bit easier steps:
1. type `$$`
2. put the cursor between the `$`
3. type `\` (which is a trigger character that triggers autocompletion for me

Result: I only get `$ $, built-in` as a completion candidate.

I suspect that the (valid) combination `\$` is used to filter the completions, even though you didn't actually type `$`.

Not sure how `texlab` is to fix that; this seems like an issue with the autocompletion.

(This is not specific to `$`, of course: if you have `|alp` -- with `|` denoting the cursor -- and type `\`, completion will be prefiltered to `\alp` as well.)

**Comment by clason** [comment]
(And the other questions are independent and should be asked in separate issues. But spellchecking is the job of the  editor and has nothing to do with the texlab LSP.)

**Comment by pfoerster** [comment]
> I suspect that the (valid) combination \$ is used to filter the completions, even though you didn't actually type $.

Thanks @clason. That was exactly the problem. I added a simple check that should fix this problem (see the latest commit on the master branch). Please let me know if it works for you.

> In addition, I only want to trigger the mathematics symbols completion in equation environments, and other LaTeX commands in normal writing environments. Is this possible?

At the moment, this is not possible and I imagine that it is very difficult to achieve. Detecting whether you are inside math mode is quite easy but checking if a command can be used inside math-mode or not requires a call of the TeX engine, which is very expensive. We can try to pre-compute this information in the completion data script but this will never work accurately for custom commands.

> At the same time, I want to have the ispell based (on-the-fly) spell checker.

Just like @clason said, `texlab` currently does not provide spell-checking because:
1. There are no good cross-platform libraries that are easy to use from Rust (for example LanguageTool is way too big and not easy to use)
2. It is quite difficult to not produce a lot of false positives

This may change in the future but at the moment, `texlab` does not provide this feature and it would definitely be an opt-in feature.

**Comment by hongyi-zhao** [comment]
> > In addition, I only want to trigger the mathematics symbols completion in equation environments, and other LaTeX commands in normal writing environments. Is this possible?
> 
> At the moment, this is not possible and I imagine that it is very difficult to achieve.

Based on my tries, it seems that the configuration of [doom-emacs](https://github.com/hlissner/doom-emacs) can complete this.

**Comment by hongyi-zhao** [comment]
> > I suspect that the (valid) combination $ is used to filter the completions, even though you didn't actually type $.
> 
> Thanks @clason. That was exactly the problem. I added a simple check that should fix this problem (see the latest commit on the master branch). Please let me know if it works for you.
> 
> >

Accurate analysis and great fix, I confirm that it does the trick.
