### ISSUE TITLE
Client 1 quit with exit code 101 and signal 0

### ISSUE THREAD

**Issue by yochem** [latex-lsp/texlab#450]
Dear maintainers,

I'm currently using texlab in neovim nightly with their lspconfig. Since texlab version 3.0, it quits whenever I start typing and it starts autocompleting. This happens with no configuration.

The exit code is 101 and the signal is 0. I tried finding logs somewhere on my system but I was not able to find them.

**Comment by clason** [comment]
Can you add more details of your config?

I've been using texlab from neovim without any problems for months...

**Comment by yochem** [comment]
I found this in the lsp.log file from nvim:

```
[ ERROR ] 2021-06-27T16:16:13+0200 ] ...im/HEAD-a9b8c78_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"texlab"	"stderr"	"thread 'main' panicked at 'Invalid request\nMethod: textDocument/hover\n error: invalid value: integer `-2`, expected u32"
[ ERROR ] 2021-06-27T16:16:13+0200 ] ...im/HEAD-a9b8c78_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"texlab"	"stderr"	"', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.5.1/src/msg.rs:190:17\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

Formatted:
```
"thread 'main' panicked at 'Invalid request
Method: textDocument/hover
 error: invalid value: integer `-2`, expected u32"
```
```
"', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.5.1/src/msg.rs:190:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
"
```

**Comment by yochem** [comment]
Sure!

wait a sec

**Comment by clason** [comment]
Might be a broken `texlab` installation. How did you install it? What's your platform?

**Comment by yochem** [comment]
Can conform this still is the problem with on the latest commit of neovim, latest commit of lspconfig and texlab reinstalled

**Comment by yochem** [comment]
Here's a screencast:


https://user-images.githubusercontent.com/23235841/123548464-28bbd800-d765-11eb-88f8-fb65aff407e4.mov

**Comment by clason** [comment]
Sorry, cannot reproduce here. It might be an issue with your autocomplete plugin that is sending non-compliant requests (e.g., for documentation) -- `texlab` is a pretty by-the-spec server...

**Comment by clason** [comment]
So this
> "thread 'main' panicked at 'Invalid request
Method: textDocument/hover
 error: invalid value: integer `-2`, expected u32"

should _definitely_ not be happening.

**Comment by pfoerster** [comment]
Yeah, this looks like a violation of the spec to me.  Position values definitely should never be negative. Can you try to create a log file of texlab using `texlab -vvvv --log-file texlab.log` and post it here? Maybe we can identify the faulty hover request this way.

**Comment by clason** [comment]
First, see if you can reproduce this with only `nvim-lspconfig` (`:set omnifunc=v:lua.vim.lsp.omnifunc` instead of autocomplete). Which autocomplete plugin are you using? `nvim-compe`?

**Comment by yochem** [comment]
Okay, some more details about my configuration which I forgot to mention:

I also used the package [nvim-lua/completion-nvim](github.com/nvim-lua/completion-nvim).  It was configured like this:

```lua
-- default configuration
lsp.util.default_config = vim.tbl_extend("force", lsp.util.default_config, {
    on_attach = function(client) require'completion'.on_attach() end
})
```

I have changed this in the following from the readme of lspconfig: 
```lua
-- default configuration
lsp.util.default_config = vim.tbl_extend("force", lsp.util.default_config, {
    on_attach = function(client, bufnr)
        local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end
        buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')
    end
})
```

That seems to work just fine. I think the problem is in the completion-nvim package then. Sorry for reporting it here, it only happened with the texlab lsp so I thought it would be a texlab issue.

**Comment by yochem** [comment]
Thank you for your time!

**Comment by pfoerster** [comment]
>  Sorry for reporting it here, it only happened with the texlab lsp so I thought it would be a texlab issue.

No problem, I think it should happen with `rust-analyzer` as well. It uses the same crates for the LSP layer and the LSP typings are pretty strict in this case (unsigned instead of signed data types).

**Comment by yochem** [comment]
Yeah I don't use rust so have not experienced it. I am going to report it on completion-nvim, anything particular that I should mention? That it requests negative positions?

**Comment by clason** [comment]
(I'm also using `completion-nvim`, by the way, without any problems...)

But your config looks fishy, you should just do 
```lua
require'lspconfig'.texlab.setup(
  {on_attach = require'completion'.on_attach}
)
```

**Comment by yochem** [comment]
Hm weird... I'll look further into it before reporting

**Comment by pfoerster** [comment]
If it still happens after updating your config, you can also include a `texlab` log (`texlab` logs every request and response) and mention that the position inside a hover request should never contain negative values. According to the LSP spec, special values like `-1` are not allowed. See here: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#position

**Comment by yochem** [comment]
How can I manually attach to the texlab lsp from nvim?

**Comment by yochem** [comment]
https://gist.github.com/yochem/7504cee4cb31d79365afbc60b3454054 Here's a gist of the output in texlab.log, do you maybe find something odd?

**Comment by pfoerster** [comment]
Thanks for the log. This incoming hover request is the cause of the problem:

DEBUG - < {"method": "textDocument/hover", "jsonrpc": "2.0", "id": 6, "params": {"textDocument": {"uri": "file:///Users/yochem/Documents/thesis/paper/discussion.tex"}, "position": {"character": -2, "line": 14}}}

`character` is not allowed to be `-2`.
