### ISSUE TITLE
Does texlab support incremental sync?

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#460]
This is mostly a question because I couldn't (quickly) find the answer in previous issues or the code. Does (or can) texlab support [`textDocumentSync`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_synchronization) `Incremental`?

**Comment by pfoerster** [comment]
`texlab` uses `Full` (as seen [here](https://github.com/latex-lsp/texlab/blob/master/src/server.rs#L95)). We could support `Incremental` but there is not much benefit to it because `texlab` does not do incremental parsing at the moment.

**Comment by clason** [comment]
Gotcha, thank you (I guess I forgot to use wildcards with Github search as it didn't pick this up) ;)

If it's not much work, that would be good -- `texlab` may not profit, but the _client_ could. (I just had a situation recently with autocompletion where the repeated `json` encoding of the full file blocked the editor -- it was a deliberate stress test, so it's not crucial to change it, but might reduce some load.)

**Comment by pfoerster** [comment]
Yeah, this sounds reasonable and should not be too hard to implement 👍

**Comment by clason** [comment]
Great, thank you! Absolutely no priority, though!

**Comment by clason** [comment]
Looks like this was implemented in https://github.com/latex-lsp/texlab/commit/544c96ac17f0e2489d2911ab69771017db8093c5? Should this issue be closed?

**Comment by pfoerster** [comment]
> Looks like this was implemented in 544c96a? Should this issue be closed?

Thanks for reminding me 👍 
Yes, this feature was implemented in 544c96a. I will make a new release this weekend together with all the small fixes that have accumulated since 3.2.0.

**Comment by clason** [comment]
Nice; I checked in the meantime and confirmed that it's in fact working!
