### ISSUE TITLE
Lost on configuration with (spac)macs.

### ISSUE THREAD

**Issue by paxperscientiam** [latex-lsp/texlab#461]
Hi, I'm trying to adapt my spacemacs config to use texlab as the latex [LSP backend](https://develop.spacemacs.org/layers/+lang/latex/README.html); however, I've run into some trouble.

There is a command called `lsp-latex-build`, which "builds current tex file with latexmk, through texlab." I can confirm that this does trigger latexmk and that my .latexmkrc is picked up by it; however, I have no idea what "through texlab" means. 

If I understand correctly, texlab should provide syntax checking, intellisense data, and document location info for a previewer. Is that accurate?

This is what the session graph looks like:
![Screen Shot 2021-07-24 at 12 18 11 AM](https://user-images.githubusercontent.com/7539871/126857058-962832c5-8856-4e0e-8b17-01eb55717166.png)

I see that there is a nice description of configuration options in the texlab docs; however, I haven't the foggiest idea how to make this work with emacs. I've scoured the internet. Halp?

**Comment by pfoerster** [comment]
Thanks for the report.

> There is a command called lsp-latex-build, which "builds current tex file with latexmk, through texlab." I can confirm that this does trigger latexmk and that my .latexmkrc is picked up by it; however, I have no idea what "through texlab" means.

Through `texlab` means that `latexmk` is called by `texlab` and not by the editor or the shell.
`texlab` has a little bit of extra information which allows it to detect which file should be builded if you have a multi-file project (`texlab` detects the root file automatically without magic comments).

> If I understand correctly, texlab should provide syntax checking, intellisense data, and document location info for a previewer. Is that accurate?

Yeah, basic syntax checking like unbalanced braces is provided by `texlab` directly, linting uses `chktex` under the hood and needs to be enabled. IntelliSense or auto completion is one of the main features of `texlab`. The previewer can be synchronized to the current cursor position after every build using SyncTeX, so you need to use a SyncTeX-compatible previewer. We have example configurations for most previewers in our documentation.

> This is what the session graph looks like:

The session graphs mostly shows you the capabilities of `texlab`, that is, the features of the language server. For example, you can see that texlab supports everything listed in the screenshot.

> I see that there is a nice description of configuration options in the texlab docs; however, I haven't the foggiest idea how to make this work with emacs. I've scoured the internet. Halp?

I am not an Emacs user myself, but I think, Spacemacs uses `lsp-mode` under the hood. I think in this case, you can use `lsp-register-custom-settings` to set your configuration. Alternatively (which is what I recommend), you can use https://github.com/ROCKTAKEY/lsp-latex, which provides a small wrapper around `lsp-mode` and exposes the options as simple variables. For example, to enable linting using ChkTeX, you can set `lsp-latex-lint-on-change` to true.

**Comment by paxperscientiam** [comment]
Thanks for the detailed reply; that definitely clears a lot up. I'll give ROCKTAKEY's wrapper a try and then report back with my findings.
