### ISSUE TITLE
lsp auto display "()" after functions , like \title(), but i surely want {}

### ISSUE THREAD

**Issue by flaviusbuffon** [latex-lsp/texlab#480]
![image](https://user-images.githubusercontent.com/44057232/132210020-ea15e8fc-6bde-4e43-9e55-49f63929347c.png)

**Comment by clason** [comment]
That must be some (auto-pairs? snippet?) plugin interfering. Texlab by default does _not_ add parenthesis.

Please add actual information to your issue, like what your editor is, what version of texlab, your (relevant) settings, etc.

**Comment by flaviusbuffon** [comment]
> That must be some (auto-pairs? snippet?) plugin interfering. Texlab by default does _not_ add parentheses.
> 
> Please add actual information to your issue, like what your editor is, what version of texlab, your (relevant) settings, etc.

i am using neovim, and for many plugins  in this config
https://github.com/ayamir/nvimdots#plugins

**Comment by clason** [comment]
> i am using neovim, and for many plugins in this config
https://github.com/ayamir/nvimdots#plugins

That's too many. Please try to whittle it down to a minimal config. You can use https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua as a basis.

**Comment by clason** [comment]
(In case it wasn't clear, I am also using Neovim and cannot reproduce your problem.)

**Comment by pfoerster** [comment]
I think, your `nvim-autopairs` config is the culprit. Looking at the source, it seems like it inserts parens whenever you complete a "function" (which is a LaTeX command in this case): https://github.com/ayamir/nvimdots/blob/main/lua/modules/completion/config.lua#L133

**Comment by flaviusbuffon** [comment]
you are the best! thanks for you work, i used to have doubt to this plugin hhh
!!!

**Comment by flaviusbuffon** [comment]
i also want to ask how to make this plugin  auto pair {} instead (), can you help me for solving this problem
