### ISSUE TITLE
Error when calling `:TexlabBuild` Neovim +0.5

### ISSUE THREAD

**Issue by riazufila** [latex-lsp/texlab#485]
The build is a success. However an error appears `Error executing vim.schedule lua callback: ...ack/packer/start/nvim-lspconfig/lua/lspconfig/texlab.lua:30: RPC[Error] code_name = MethodNotFo
und, message = "method not supported: textDocument/build` and then build complete successfully.

```
-- My texlab setup using lspconfig
lspconfig.texlab.setup({
        on_attach = on_attach,
	capabilities = capabilities,
	settings = {
		texlab = {
			build = {
				executable = "latexmk",
				args = { "-pdf", "-interaction=nonstopmode", "-synctex=1", "%f" },
				onSave = false,
				forwardSearchAfter = true,
			},
			chktex = {
				onOpenAndSave = true,
			},
			forwardSearch = {
				executable = "zathura",
				args = { "--synctex-forward", "%l:1:%f", "%p" },
			},
		},
	},
})
```

**Comment by clason** [comment]
Did you update to the latest `nvim-lspconfig`?

**Comment by riazufila** [comment]
Yes I did. I just tried disabling `efm` and the error went away.

```
-- This is my efm setup
lspconfig.efm.setup({
	on_attach = on_attach,
	capabilities = capabilities,
	init_options = {
		documentFormatting = true,
	},
	settings = {
		languages = {
			lua = { lua },
			python = { black, isort },
			javascript = { prettier },
			javascriptreact = { prettier },
			typescript = { prettier },
			typescriptreact = { prettier },
			json = { prettier },
			html = { prettier },
			css = { prettier },
			tex = { latexindent },
		},
	},
})
```

**Comment by clason** [comment]
This means that the `TexlabBuild` request is sent to both `texlab` and `efm`, the latter responding with that error. (Running multiple language servers in parallel is not officially supported, for exactly these reasons.)

In any case, this is not an issue with `texlab` and should instead be opened at the `nvim-lspconfig` repo.

**Comment by riazufila** [comment]
Sorry for the misunderstanding. And thank you for clarifying. Ill close this issue now.
