### ISSUE TITLE
Where are the compilation errors?

### ISSUE THREAD

**Issue by DrWaleedAYousef** [latex-lsp/texlab#491]
Thanks so much for the great project. 
![image](https://user-images.githubusercontent.com/12213197/135724376-835018d2-d88a-4182-a400-601956802cb8.png)

Attached is the image of my emacs session, trying to compile the simple code at the left, which has an unkown command that should produce an error. The right panel shows the texlab session. The bottom panel should show the erros of compilation; it does not.

Any advice?

**Comment by pfoerster** [comment]
Thanks for the kind words :).

> The bottom panel should show the erros of compilation; it does not.

How did you compile `main-paper.tex`? Did you change the output directory of the auxiliary files or is the log file inside the same directory as the TeX file? Can you paste or attach the log file here, please?

**Comment by DrWaleedAYousef** [comment]
Thanks for reply.

It seems that I had a `.cache` problem (since I am new to `spacemacs`). I solved aggressivley by removing the `.cache` directory. Now, other related problems merge.
1. texlab erros that should appear automatically in the `.tex` buffer do not show automatically after saveing or while editing. 
2. the bottom pannel does not update consistantly.

I wasted a lot of time trying configuing things, although `spacemacs` should run out of the box. For helping, I have this in my `.spacemacs` file:

```
  (setq lsp-latex-build-is-continuous t
        lsp-latex-chktex-on-edit t
        lsp-latex-forward-search-after t
        ;; lsp-latex-forward-search-args '("--eval" "(lsp-latex-forward-search-with-pdf-tools \"%f\" \"%p\" \"%l\")")
        ;; lsp-latex-forward-search-executable "emacsclient"
        ;; lsp-latex-build-args '("--shell-escape" "-preview_continuous_mode" "-pdf" "-interaction=nonstopmode" "-synctex=1" "%f")
        )

```

**Comment by pfoerster** [comment]
> texlab erros that should appear automatically in the .tex buffer do not show automatically after saveing or while editing.

`texlab` requires a recent build log to update the errors and warnings. To provide a list of diagnostics, a compilation is needed due to the nature of TeX and `texlab` is *not* a TeX engine so it has to let the actual TeX engine do the work. It should automatically update the diagnostics whenever the log changes.

Regarding your config: `lsp-latex-build-is-continuous t` is not needed anymore as this property has been made obsolete in 3.2.0. For the other properties, I recommend the following page: https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md
In particular, `-preview_continuous_mode` does not play nicely with forward search.

**Comment by DrWaleedAYousef** [comment]
Thanks so much; your answer raises some questions:

> > texlab erros that should appear automatically in the .tex buffer do not show automatically after saveing or while editing.
> 
> `texlab` requires a recent build log to update the errors and warnings. To provide a list of diagnostics, a compilation is needed due to the nature of TeX and `texlab` is _not_ a TeX engine so it has to let the actual TeX engine do the work. It should automatically update the diagnostics whenever the log changes.
> 

1. I agree; however, when I compile, the bottom panel does not refresh deterministically. I mean some times refreshes and sometimes it keeps empty. The behaviour is not deterministic! I wasted a lot of time trying solving that. BTW, I installed `texlab` via archlinux distro: `yay -S texlab`, and emacs shows that it calls `texlab2`. Is this relevant? 

> Regarding your config: `lsp-latex-build-is-continuous t` is not needed anymore as this property has been made obsolete in 3.2.0. For the other properties, I recommend the following page: https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md In particular, `-preview_continuous_mode` does not play nicely with forward search.

2. So, this seems to be a jet-lag between `texlab` and `lsp-latex`, which provides the `texlab` options to emacs in a handy `lsp` configuration. If I need directly to modify `texlab` options, which configuration file I should change? I did not find this in the help page.

3. AUCTEX, has the C-c C-a keybinding that compiles, opens the pdf for the first time, or refreshes it if already open. Now, after moving to `spacemacs`, `texlab`, `lsp`, and `latexmk` (which is a big story) I need to have the same behavior. Is it better to make it from:
a. `.latexmrc`, like this:
```
$lualatex = 'lualatex --synctex=1 -view=pdf -pv -recorder %O -shell-escape %S';
$pdf_previewer = 'start emacsclient';
```
b. `texlab` (which I do not know where to specifiy it, as I mentioned before)
c. or from `lsp-latex`, which is an interface to `texlab`, like at the end of [their page](https://github.com/ROCKTAKEY/lsp-latex)

none of them is succesfful in launching the pdf after the first compilation.

Thanks so much in advance
