### ISSUE TITLE
[Bug] Incorrect rule for import package

### ISSUE THREAD

**Issue by lambtho12** [latex-lsp/texlab#508]
I am using texlab with neovim built-in LSP.

In my tex documents, I often use the following preamble
``` latex
\newcommand{\incfig}[2]{
  \def\svgwidth{0.82\columnwidth}
  \import{figures/#1}{#2.pdf_tex}
}
```

the LSP server reports the following errors
- `Missing "'}" inserted` on line 3
- `Unexpected "}"`on line 4

If I put everything on a single line, it still says `Unexpected "}"`.

According to the import package documentation, this is the expected syntax. Also, the document compiles without any issue.

I tried, to replace the first set of curly braces with square braces and the LSP error vanishes, but then the import package throws an error and the document will no longer compile.

Note that when \import is directly used in the document, this error is no longer present. It appears to be only related to the preamble.

**Comment by pfoerster** [comment]
Thanks for the report. The problem are the macro parameters (`#1` and `#2`). `texlab` tries to parse these at the moment, but it does not do anything with them at the moment. As parsing them does more harm than good, I removed them in 79ab7bdcfb52812356437ee4a29fd342e21ec0e9. This commit should fix the issue. Please let me know if it works for you.
