### ISSUE TITLE
Build Request custom config

### ISSUE THREAD

**Issue by aspeddro** [latex-lsp/texlab#522]
It is possible to change the build executable through a request?

Example:

My default config use `latexmk`. I want to send a request using `tectonic`?

```lua
params = {
    buildConfig = { executable = 'tectonic' }
    textDocument = { uri = vim.uri_from_bufnr(bufnr) },
}
client.request('textDocument/build', params, handler_function, buffer)
```

**Comment by pfoerster** [comment]
You can use the [`workspace/didChangeConfiguration`](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration) notification to push a new set of options to the server. Note that you need to modify the capabilities so `texlab` does not call `workspace/configuration` before building the document. This also changes the global config for all future requests; there is no one-time setting.

Which LSP client for Vim do you use? Maybe, you can create a local config for a particular project/document which overrides the default config (similar to `.vscode/settings.json`).

**Comment by aspeddro** [comment]
I use LSP builtin Neovim

**Comment by pfoerster** [comment]
I think this page might be helpful: 

https://github.com/neovim/nvim-lspconfig/wiki/Project-local-settings

Basically, you can use `workspace/didChangeConfiguration` and send a new settings object which `texlab` will use for the next requests. Note that the object must not contain a `texlab` key (e. g. `{"build": {"executable": "tectonic", "args": ...}}`)
