### ISSUE TITLE
Use LocationLink for PeekDefinition?

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#53]
If I understand correctly, the LSP specification for "go to definition" allows including a `LocationLink` that contains a *range* for the target. Could this be used to make `PeekDefinition` on a label only show exactly the labelled environment (plus maybe one or two lines above, possibly configurable)?

~Alternatively (if this is even the responsibility of the server and not the client), could the shown preview be changed so that the targeted symbol is always at a fixed position from the top (first, second, third line, depending on the margin)?~

**Comment by pfoerster** [comment]
@clason The "Goto Definition" feature now uses the LocationLink struct if the client supports it.
Can you try out if it works with vim-lsp? For VScode, it does not seem to make a difference.

**Comment by clason** [comment]
Unfortunately, `vim-lsp` doesn't support LocationLink -- yet. If you cab give me an example of a server response (I didn't see one in my log files, presumably because vim-lsp doesn't advertise that capability) and whatever else a client should support, I'll open an issue about it.

**Comment by pfoerster** [comment]
@clason TexLab only sends `LocationLink`s if the client supports it. This can be signaled by setting the `ClientCapabilties.textDocument.definition.linkSupport` field to `true`. A typical response (see #27 for the example) looks like this:

```json
{"jsonrpc":"2.0","result":[{"originSelectionRange":{"end":{"character":11,"line":0},"start":{"character":6,"line":0}},"targetRange":{"end":{"character":13,"line":3},"start":{"character":0,"line":1}},"targetSelectionRange":{"end":{"character":38,"line":1},"start":{"character":33,"line":1}},"targetUri":"file:///D:/latex-lsp/texlab-dev/issue/test1.tex"}],"id":27}
````

**Comment by clason** [comment]
That's the example from https://github.com/latex-lsp/texlab/issues/27#issuecomment-513559839, right? And the definition target is the `sec:foo` label?

**Comment by pfoerster** [comment]
No, its the example from https://github.com/latex-lsp/texlab/issues/27#issuecomment-523502775. It is the result of `textDocument/definition` (using the reference `thm:1` in file `test2.tex`).

**Comment by clason** [comment]
Gotcha. Thanks!

**Comment by clason** [comment]
@pfoerster I've now implemented `locationLink` support in `vim-lsp`, and it works! The only "issue" I see is that for section labels, the `targetRange` only contains the label itself. In particular, something like
```tex
\section{First}
\label{sec:first}
```
gets an empty preview; I'd hope that at least both the section command and the label was included.

**Comment by pfoerster** [comment]
@clason Can you try if the latest commit on the master branch works for you? For section labels, `targetRange` now includes the full range of the labeled section.

**Comment by clason** [comment]
@pfoerster It doesn't seem to for me; here's the server response for 
```tex
\documentclass{article}
\begin{document}

\section{Test}
\label{sec:test}


\begin{equation}
    \label{eq1}
    \int_0^1 f(x)\,dx = F(1) - F(0)
\end{equation}

See \eqref{eq1} in Section \ref{sec:test}
\end{document}
```

```
Tue 10 Sep 2019 02:40:54 PM CEST:["<---", 5, "texlab", {"response": {"id": 19, "jsonrpc":  "2.0", "result": [{"originSelectionRange": {"end": {"character": 40, "line": 12}, "start": {"character": 32, "line": 12}}, "targetSelectionRange": {"end": {"character": 16, "line":  4}, "start": {"character": 0, "line": 4}}, "targetRange": {"end": {"character": 14,        "line": 3}, "start": {"character": 0, "line": 3}}, "targetUri": "file:///home/clason/test. tex"}]}, "request": {"id": 19, "jsonrpc": "2.0", "method": "textDocument/definition",      "params": {"textDocument": {"uri": "file:///home/clason/test.tex"}, "position":            {"character": 39, "line": 12}}}}]
```
Note that both `start` and `end` are on line 4 (containing the sectioning command only). 

But this is already an acceptable fix; now it always shows (only) the sectioning command, independent of the label position!

**Comment by pfoerster** [comment]
@clason Can you try b6ecca4edef77bfa4b04670c4927c8cf79a85a58? I think, I managed to fix the issue.

**Comment by clason** [comment]
Yes, it does! Small nitpick: The `targetRange` includes the beginning (first line) of the following section. If this is intended (to indicate that no text is lost), that's fine, though.

**Comment by clason** [comment]
> If this is intended (to indicate that no text is lost), that's fine, though.

Feel free to close this issue if this is the case, by the way! Apart from this, I'm very happy with the functionality now.

**Comment by pfoerster** [comment]
> Yes, it does! Small nitpick: The targetRange includes the beginning (first line) of the following section. If this is intended (to indicate that no text is lost), that's fine, though.

This is basically intended because of performance reasons and code complexity. Getting the last character of the line before the next section would involve traversing the whole document.

> I'm very happy with the functionality now.

Thanks!
