### ISSUE TITLE
Hover on citations not working on macOS

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#54]
As the title says, if I trigger hover on `\cite{X}` with the provided macOS build (1.2.0), I just get 
`No hover information found`. (Hover on other symbols works as expected; on Linux everything works as expected.)

The `stderr` output is simply
```
TRACE - Sent message:
Content-Length: 39^M
^M
{"jsonrpc":"2.0","result":null,"id":10}
```
Possibly the `citeproc` dependency is not correctly built on the macOS pipeline?

**EDIT** It works if I build texlab on that machine from source (master).

**EDIT2** Hover on equations isn't working on macOS either, also not if built from source, so there's another dependency issue. I didn't see any build errors or warnings, though.

**Comment by pfoerster** [comment]
Unfortunately, I cannot reproduce this issue on another macOS machine. It does not seem like a dependency issue to me. Instead, the build should fail if `citeproc` is missing. I will add some logging statements soon, which should help diagnose the issue.

**Comment by clason** [comment]
Maybe it depends on the version - I tested 10.14.6+?

On 26 Jul 2019 13:31, Patrick Förster <notifications@github.com> wrote:

Unfortunately, I cannot reproduce this issue on another macOS machine. It does not seem like a dependency issue to me. Instead, the build should fail if citeproc is missing. I will add some logging statements soon, which should help diagnose the issue.

**Comment by clason** [comment]
Thanks! Since it seems to make a difference whether I use the release or compile from source, do you plan on doing nightly builds?

**Comment by clason** [comment]
Another thought: Is `Node`a runtime dependency? Because that isn't installed on the failing machine.

**Comment by pfoerster** [comment]
`Node` is an optional runtime dependency. We use it to render citations. If `Node` is not installed, then we cannot render citations because we depend on the `citeproc-js` library. See also https://texlab.netlify.com/docs

**Comment by pfoerster** [comment]
In addition to that, we are planning to statically link against `Node` in order to avoid this optional runtime dependency.

**Comment by clason** [comment]
Well, there you go then, that's exactly it. 

I'd recommend mentioning runtime dependencies in the Github README as well; I didn't think to look into the docs since they looked to be more about the VS Code extension than the server directly.

(Also, maybe also mention the rust version that is needed? Took me a bit to find out what I had to do after the build failed with the -- at that time -- stable version. Also also, now that 1.37 is stable, is `nightly` still required in the rust-toolchain?)
