### ISSUE TITLE
Incorrect handling of `\subimport` for multi-file projects. 

### ISSUE THREAD

**Issue by anand-bala** [latex-lsp/texlab#540]
I am using Neovim's builtin LSP with `texlab` and I noticed that `textDocument/forwardSearch` isn't handled properly for when the project contains a sub-file included using `\subimport` from the [`import`](https://www.ctan.org/pkg/import) package. This can be reproduced with the following files:

`main.tex`:
```tex
\documentclass[11pt]{article}

\usepackage{import}
\usepackage{lipsum}

\title{Minimal Example}

\begin{document}
\maketitle

\section{Main file}

\lipsum[1]

\subimport{}{stuff}
\end{document}
```

`stuff.tex`:
```tex
\section{Imported file}

\lipsum[2]
```

Changing the `\subimport{}{stuff}` to `\input{stuff}` makes this work as expected.

There is potentially another problem also, but I will refer you to [neovim/nvim-lspconfig#1675](https://github.com/neovim/nvim-lspconfig/issues/1675) for more details.

**Comment by pfoerster** [comment]
Thanks for the detailed report! I was able to reproduce the problem on my machine. The fix itself is quite simple (9f778cc).
 
> There is potentially another problem also, but I will refer you to neovim/nvim-lspconfig#1675 for more details.

Thanks for the ping. 432a7d38acef557c986a258875a2129b2133757f should fix this problem.

Please let me know if one of the issues is still present.

**Comment by anand-bala** [comment]
Wow! Thank you for the really quick fix!

**Comment by anand-bala** [comment]
Looks like this is an issue with xelatex not generating the synctex correctly for `\subimport`. Thanks for the help!
