### ISSUE TITLE
Update configuration options in texlab.netlify.app

### ISSUE THREAD

**Issue by OliverLew** [latex-lsp/texlab#546]
I followed the configuration options here
https://texlab.netlify.app/docs/reference/configuration
only to find out they don't work because they have been changed.

**Comment by clason** [comment]
The website has been shuttered; the options are now documented here: https://github.com/latex-lsp/texlab/blob/master/docs/options.md

**Comment by pfoerster** [comment]
It is a bit surprising to me that it didn't redirect you to the GitHub page (it does for me). Besides that, I have just removed the old link from the side panel.

**Comment by OliverLew** [comment]
Yes, I had found the current options there. But I couldn't know the website is outdated from within the website. Being quite a noob, I was checking my setup thousands of times without realizing the options are never correct from the start.

**Comment by pfoerster** [comment]
That's a bit odd. Maybe the redirect is not working or it is a caching issue? 

```curl https://texlab.netlify.app/docs/reference/configuration```

outputs the following on my machine:

```
Redirecting to https://github.com/latex-lsp/texlab
```

**Comment by OliverLew** [comment]
> or it is a caching issue?

Must be it, I cleared site cache and the page is redirecting now.
