### ISSUE TITLE
Terminal title changes to included files with neovim's lsp

### ISSUE THREAD

**Issue by OliverLew** [latex-lsp/texlab#547]
If `title` option in neovim is set, and there is `\include` of `\input` command, the window(terminal) title will be changed to one of the included files. Occurs in neovim's lsp, but not vim + vim-lsp, other lsp client not tested.

Texlab version: v3.3.1

### MWE:
An empty test.tex, and main.tex as follows:
```tex
\documentclass{article}
\begin{document}
\include{test}
\end{document}
```
And a `test.vimrc`:
```vim
packadd nvim-lspconfig
filetype on
set title
lua require'lspconfig'.texlab.setup{}
```

### Reproduce
- Run `nvim -u test.vimrc main.tex`
- See terminal terminal title show `main.tex ...`
- A fraction of second after, terminal title changes to `test.tex ...`

If I change modes in vim, i.e., insert, normal, etc., the title also changes back and forth.

**Comment by clason** [comment]
That is not related to texlab but to Neovim (as you note yourself since it doesn't happen with other clients). Please report it there. (I'd assume that this is because the client opens all workspace files, so the last one to open sets the title.)

**Comment by OliverLew** [comment]
Thanks, I will open an issue there.
