### ISSUE TITLE
Option to check text with LanguageTool like [ltex-ls](https://github.com/valentjn/ltex-ls)

### ISSUE THREAD

**Issue by chrismit3s** [latex-lsp/texlab#554]
So at the moment I'm a bit torn between ltex-ls and texlab, because on the one hand I love the language server capabilities of texlab, but also need the grammar checking of ltex-ls. 

It would be awesome if texlab had the option to check text with LT. I might implement it myself in the next couple of months if I find the time.

**Comment by clason** [comment]
The two servers do completely different things, so you will have to run both at the same time. This is something that's not really covered in the spec, so results vary wildly. But it's certainly possible with a bit of care (e.g., with Neovim's built-in client, which is the one I'm familiar with).

**Comment by chrismit3s** [comment]
Wait, you can run two language servers simultaneously with nvim-lspconfig? That's nice, gonna give that a try then, thanks :)

**Comment by clason** [comment]
Yes, it's possible, but takes some fiddling to make sure the right server gets the proper requests (so you don't ask ltex-ls for completions, say). I think the best approach is to disable all capabilities for ltex-ls _but_ diagnostics (and possibly disable diagnostics for texlab).
