### ISSUE TITLE
\renewenvironment not treated the same as \newenvironment

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/texlab#556]
When creating a new environment I can separate begin and end in the arguments and it doesn't flag as error
![newenvironment](https://user-images.githubusercontent.com/40038251/153066098-0254f900-2f5a-4587-85f6-b2da0bf6f0d6.png)

But this doesn't happen when using \renewenvironment
![renewenvironment](https://user-images.githubusercontent.com/40038251/153066097-d6bbffff-d8bd-4e61-ad44-5a99f36b2ab8.png)

**Comment by pfoerster** [comment]
Thanks for the report. This is an easy fix: https://github.com/latex-lsp/texlab/commit/32d007e0a986f9e4ed4b2272b9b665a5be2a9b74
