### ISSUE TITLE
The command \color doesn't accept another command as an argument

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/texlab#557]
Sometimes I like to redefine a color depending on the environment, but use the same code, so I create a command to detect the current color, but the command \color understands that as a mistake.
![color](https://user-images.githubusercontent.com/40038251/153068928-c0cc5ef8-a310-4038-ade7-1d9242980013.png)

**Comment by pfoerster** [comment]
Thanks for the report. The bug should be fixed with d5b61d3.
