### ISSUE TITLE
\begin completion leading slash

### ISSUE THREAD

**Issue by tgray** [latex-lsp/texlab#558]
Using texlab (installed with homebrew on macOS) with BBEdit 14.1 for completions.  The `\begin` completion loses it's leading slash when inserted.  The insertion looks like the following, with the first `<# $1 #>` highlighted.

	begin{<# $1 #>}
	
	\end{<# $1 #>}

I contacted Barebones, the makers of BBEdit, and they think they are reading the replacement text correctly.  Looking at texlab's verbose logging output, I found the insert text coming from texlab does not have the leading slash

    2022-02-09 06:48:42.221: stderr output from server: DEBUG - >
    {"jsonrpc":"2.0","id":26,"result":{"isIncomplete":false,"items":[{"data":"
    commandSnippet","detail":"built-in","insertText":"begin{$1}\n\t$0\n\\end{$1}
    ","insertTextFormat":2,"kind":1,"label":"begin","preselect":false,"sortText"
    :"00"},
    
Barebones stated:

> Specifically, when requesting completion of a "\begin", BBEdit passes the
> location of the insertion point immediately before the backslash.

> The expectation is that the completion returned by the server will include (or
> account for) the text at (and following) that point. Thus, when the server
> returns the completion text (or sequence of edits, since the protocol supports
> either), BBEdit will replace the text from that point forward with the text
> returned by the server (or as a result of applying the specified edits,
> whichever is applicable.)

Any ideas?

**Comment by clason** [comment]
I think this is one of the many points where the specification is not as unambiguous as it should be: the question is whether the trigger character (in this case `\`) should be part of the replacement text.

For what it's worth, Neovim (which tries hard to implement the spec as written) handles this correctly, so my guess would be that BBEdit's approach of including the trigger character in the text to be replaced is if not incorrect, then certainly the "odd one out".

**Comment by pfoerster** [comment]
> For what it's worth, Neovim (which tries hard to implement the spec as written) handles this correctly, so my guess would be that BBEdit's approach of including the trigger character in the text to be replaced is if not incorrect, then certainly the "odd one out".

I think the main problem is that it is up to the client to decide what constitutes the word boundary. Most clients do not treat the backslash as a part of the word being completed. Simply adding the `\` would break the other clients.

Fortunately, the recent versions of the spec now allow `textEdit` in snippets so this should no longer be an issue.
I remember that we had this problem in the past with the old `label`-only items. However, at this time, it was not clear, if the spec allowed `textEdit` in snippets. Anyway, a483a45 updates the snippet to use a `textEdit`.

> Specifically, when requesting completion of a "\begin", BBEdit passes the
location of the insertion point immediately before the backslash.

This one sounds a bit odd. How are they sharing the "insertion point"? The completion request itself only has one `position` property which corresponds to the cursor position. This one cannot be located before the `\` (otherwise, you would not get any candidates). @tgray Can you share the log of the `textDocument/completion` request, too?

**Comment by tgray** [comment]
```
2022-02-09 18:34:47.988: stderr output from server: DEBUG - <
{"jsonrpc":"2.0","method":"textDocument\/didChange","params":{"contentChanges":[
{"range":{"start":{"line":49,"character":0},"end":{"line":49,"character":0}},"
text":"\\"},{"range":{"start":{"line":49,"character":1},"end":{"line":49,"
character":1}},"text":"b"},{"range":{"start":{"line":49,"character":2},"end":{"
line":49,"character":2}},"text":"e"},{"range":{"start":{"line":49,"character":3}
,"end":{"line":49,"character":3}},"text":"g"},{"range":{"start":{"line":49,"
character":4},"end":{"line":49,"character":4}},"text":"i"},{"range":{"start":{"
line":49,"character":5},"end":{"line":49,"character":5}},"text":"n"}],"
textDocument":{"uri":"file:\/\/\/Users\/tgray\/Documents\/Misc\/2022\/latex-test
\/latex-test.tex","version":169}}}

2022-02-09 18:34:47.989: stderr output from server: DEBUG - <
{"jsonrpc":"2.0","id":131,"method":"textDocument\/completion","params":{"context
":{"triggerKind":1},"position":{"line":49,"character":6},"textDocument":{"uri":"
file:\/\/\/Users\/tgray\/Documents\/Misc\/2022\/latex-test\/latex-test.tex"}}}
DEBUG - (Re)Loading document:
file:///Users/tgray/Documents/Misc/2022/latex-test/latex-test.tex

2022-02-09 18:34:47.989: stderr output from server: DEBUG - (Re)Loading
document: file:///Users/tgray/Documents/Misc/2022/latex-test/latex-test.tex

2022-02-09 18:34:47.990: stderr output from server: DEBUG - (Re)Loading
document: file:///Users/tgray/Documents/Misc/2022/latex-test/latex-test.tex

2022-02-09 18:34:47.990: stderr output from server: DEBUG - (Re)Loading
document: file:///Users/tgray/Documents/Misc/2022/latex-test/latex-test.tex

2022-02-09 18:34:47.990: stderr output from server: DEBUG - (Re)Loading
document: file:///Users/tgray/Documents/Misc/2022/latex-test/latex-test.tex

2022-02-09 18:34:47.991: stderr output from server: DEBUG - (Re)Loading
document: file:///Users/tgray/Documents/Misc/2022/latex-test/latex-test.tex

2022-02-09 18:34:47.991: stderr output from server: DEBUG - [Completion] Cursor:
Latex(BEGIN_ENVIRONMENT_NAME@1602..1608 "\\begin") DEBUG 2022-02-09
18:34:47.991: stderr output from server:  - >
{"jsonrpc":"2.0","id":130,"method":"workspace/configuration","params":{"items":[
{"section":"texlab"}]}}

2022-02-09 18:34:47.991: workspace/configuration request: { items =     ( {
section = texlab; } ); } 2022-02-09 18:34:47.992: stderr output from server:
DEBUG - < {"jsonrpc":"2.0","id":130,"result":[null]}

2022-02-09 18:34:47.992: stderr output from server: WARN - Invalid configuration
section "texlab": invalid type: null, expected struct Options

2022-02-09 18:34:47.992: stderr output from server: DEBUG - >
{"jsonrpc":"2.0","id":131,"result":{"isIncomplete":false,"items":[{"data":"
commandSnippet","detail":"built-in","insertText":"begin{$1}\n\t$0\n\\end{$1}","
insertTextFormat":2,"kind":1,"label":"begin","preselect":false,"sortText":"00"},
{"data":"command","detail":"built-in","kind":1,"label":"begingroup","preselect":
false,"sortText":"01","textEdit":{"newText":"begingroup","range":{"end":{"
character":6,"line":49},"start":{"character":1,"line":49}}}},{"data":"command","
detail":"built-in","kind":1,"label":"AtBeginDocument","preselect":false,"
sortText":"02","textEdit":{"newText":"AtBeginDocument","range":{"end":{"
character":6,"line":49},"start":{"character":1,"line":49}}}},{"data":"command","
detail":"built-in","kind":1,"label":"AtBeginDvi","preselect":false,"sortText":"
03","textEdit":{"newText":"AtBeginDvi","range":{"end":{"character":6,"line":49},
"start":{"character":1,"line":49}}}},{"data":"command","detail":"caption3.sty","
kind":1,"label":"AtBeginCaption","preselect":false,"sortText":"04","textEdit":{"
newText":"AtBeginCaption","range":{"end":{"character":6,"line":49},"start":{"
character":1,"line":49}}}}]}}
```

**Comment by tgray** [comment]
I can't speak to what Barebones is doing behind the scenes, but I can confirm that whatever change was made in https://github.com/latex-lsp/texlab/commit/a483a45d1c42a56256e75d19eed6c97e26ccec5d works now with BBEdit.  The leading slash is retained on insert of the completion.

**Comment by pfoerster** [comment]
`texlab` 3.3.2 now includes this change :rocket:
