### ISSUE TITLE
Optional argument in enviroment definition failed to parse

### ISSUE THREAD

**Issue by wangweixuan** [latex-lsp/texlab#570]
The following code defines environment `foo` with one optional argument:
```latex
\newenvironment{foo}[1][default]{begin}{end}
```

I expect the code to parse successfully, but two errors are reported: *Missing "}" inserted* and *Unexpected "}"*.

Related code:
https://github.com/latex-lsp/texlab/blob/4dd2518c7dbe54ba080cf31e3447e494a7d1adf5/src/syntax/latex/parser.rs#L1181

**Comment by pfoerster** [comment]
Thanks for the report. Can you try out 438c70a45636931ede3110694a35b6be67a28e1e, please?
