### ISSUE TITLE
Inverse search doesn't work with Skim.app

### ISSUE THREAD

**Issue by nalzok** [latex-lsp/texlab#583]
Hi there,

This is an amazing project! However, I encountered a problem when trying to do an inverse search with Skim.app Version 1.6.9 (139) on macOS 12.3 (21E230). Basically, I followed the instruction [here](https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md#inverse-search-5) and have the following configuration.

<img width="610" alt="Screen Shot 2022-03-21 at 13 23 35" src="https://user-images.githubusercontent.com/13443062/159339160-e734eda3-08e5-4dcc-a375-5ebc92cec1ba.png">

The relevant part of my `init.lua` looks like this

```lua
  elseif server.name == "texlab" then
      opts.settings = {
          texlab = {
              build = {
                  args = {"-X", "compile", "%f", "--synctex", "--keep-logs", "--keep-intermediates"},
                  executable = "tectonic",
                  forwardSearchAfter = true,
                  onSave = true,
              },
              chktex = {
                  onEdit = true,
                  onOpenAndSave = true,
              },
              forwardSearch = {
                  executable = "/Applications/Skim.app/Contents/SharedSupport/displayline",
                  args = {"%l", "%p", "%f"},
              }
          }
      }
  end
```

The forward search works perfectly, but the inverse search doesn't. When I `Shift+Command+Click` on the PDF document, I expect the neovim cursor to jump to the corresponding part in the tex source, but nothing happens. How do I debug this problem?

**Comment by clason** [comment]
If you use Neovim, you of course have to use a preset for it (not the one for VS Code)!

**Comment by nalzok** [comment]
> If you use Neovim, you of course have to use a preset for it (not the one for VS Code)!

Ah, that seems obvious in hindsight, but when reading the document I somehow just assumed the VS Code preset will magically work for any editors!

> If you have problems setting things up, you might want to look at https://github.com/f3fora/nvim-texlabconfig.

Thanks. This is extremely helpful. Perhaps add it to the document for Neovim users like me?

**Comment by nalzok** [comment]
I just realized that https://github.com/f3fora/nvim-texlabconfig configures things on the Neovim side, but how do I set Skim.app up? In other words, what should I put in these fields?

<img width="610" alt="Screen Shot 2022-03-21 at 13 47 18" src="https://user-images.githubusercontent.com/13443062/159342971-cd266194-4de6-4b32-ab49-8d27df7348d5.png">

**Comment by clason** [comment]
https://github.com/f3fora/nvim-texlabconfig#texlabinversesearch

**Comment by pfoerster** [comment]
I think it should work if you use `nvim` as the command and `--headless -c "TexlabInverseSearch '%file' %line"` (you may need to adapt the placeholders).

**Comment by clason** [comment]
yes, should be `%file` and `%line` in Skim (instead of `%f` and `%l`).

**Comment by pfoerster** [comment]
> Thanks. This is extremely helpful. Perhaps add it to the document for Neovim users like me?

Thanks for the suggestion! I have added a link to https://github.com/f3fora/nvim-texlabconfig to the [docs](https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md#previewing)

**Comment by nalzok** [comment]
> Thanks for the suggestion! I have added a link to https://github.com/f3fora/nvim-texlabconfig to the [docs](https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md#previewing)

Great. I appreciate it!

Not sure what's going on, but https://github.com/f3fora/nvim-texlabconfig doesn't work for me. I assume excuting the following command in Bash should move the cursor to the 8th line of the file `/tmp/test/main.tex`? Nothing happens in my case.

```bash
nvim --headless -c "TexlabInverseSearch '/tmp/test/main.tex' 8"
```

**Comment by nalzok** [comment]
It turns out that https://github.com/f3fora/nvim-texlabconfig requires Neovim 0.7+ but I was running 0.6.1. Closing.
