### ISSUE TITLE
Pros and cons compared to lervag/vimtex

### ISSUE THREAD

**Issue by nalzok** [latex-lsp/texlab#584]
What the strengths and weaknesses of the `texlab` LSP server compared to more traditional plugins like [lervag/vimtex](https://github.com/lervag/vimtex)? How should one make these two cooperate to get the best of both worlds?

**Comment by clason** [comment]
They don't conflict in any way, which is the important point. As far as strength and weaknesses, beyond comparing their respective documentation (which you can do yourself!), the answer is likely to be quite subjective and hence not a good fit for an issue tracker...

**Comment by nalzok** [comment]
> They don't conflict in any way, which is the important point.
> Why not just install both and, where they offer similar features like building/forward search, use the one that works better for you?

Indeed, I am a little confused by their similarity. Both offers feature like building, forward search, and inverse search, so which one should I use? I mean, there must be some tradeoff made by either tool, so I'd like to know a little about that before picking one. It feels like once you are settled for one of them, it would be hard to switch to the other because of muscle memory.

**Comment by clason** [comment]
You should use whichever works best _for you_. They both work well (and well together), so it really comes down to personal preference. 

In any case, both do things that the other doesn't, so neither is a full replacement for the other.

**Comment by nalzok** [comment]
Thanks. I will try out both and see which one works better with me!
