### ISSUE TITLE
Autocomplete filenames based on `graphicspath`

### ISSUE THREAD

**Issue by MarcelRobitaille** [latex-lsp/texlab#590]
It would be amazing if autocomplete suggestions could be recommended based on `graphicspath`. For example:

```tex
\graphicspath{{../figures/}}
\begin{document}
\includegraphics{_
```

If my cursor is the `_`, I would like to be prompted with the files present in `../figures` in addition to the files in the current folder. I think the `graphicspath` should take precedence since this is explicitly saying "here is where I want to store my figures.

**Comment by pfoerster** [comment]
Thanks for the suggestion! 68a901e now implements this feature 👍

**Comment by MarcelRobitaille** [comment]
Amazing. That's the second issue you've solved for me extremely quickly. Can I send a donation to you and/or this project to say thanks?

**Comment by pfoerster** [comment]
> Amazing. That's the second issue you've solved for me extremely quickly

You're welcome :)

> Can I send a donation to you and/or this project to say thanks?

Thanks for the generous offer! `texlab` has always been a part of my spare time and I would like to keep it as a hobby. The fact that there are people using this project for their work or studies is thanks enough for me :)

**Comment by MarcelRobitaille** [comment]
Suit yourself. Lots of open-source hobby projects take donations, though. I don't see any harm in that.

> The fact that there are people using this project for their work or studies is thanks enough for me :)

I am using it for my studies. I recently set up LSP and I have been loving texlab!
