### ISSUE TITLE
Building Texlab from source code 3.3.2. Dependencies error 

### ISSUE THREAD

**Issue by LuisMi1245** [latex-lsp/texlab#593]
[root@localhost` texlab-3.3.2]# cargo build --release

error: failed to get `citeproc` as a dependency of package `texlab v3.3.2 (/root/texlab-3.3.2)`

Caused by:
  failed to load source for dependency `citeproc`

Caused by:
  Unable to update https://github.com/cormacrelf/citeproc-rs?rev=2ab195a1e6f84f0ff284813ece61dc62096abbfe#2ab195a1

Caused by:
  the given reference name 'refs/remotes/origin/.l2s.HEAD.lock0001' is not valid; class=Reference (4)

**Comment by pfoerster** [comment]
Thanks for the report. That looks a bit like a `cargo` issue. The `citeproc-rs` repository has recently been moved to the `zotero` organization. Maybe this could be an issue although it still works fine on my machine with the redirect. Nevertheless, I have updated the referenced repository URL.

This post from StackOverflow might indicate that there is a problem with the underlying `cargo` registry:
https://stackoverflow.com/questions/63077718/cargo-add-command-failed-due-to-unhandled-error-reference-refs-remotes-origin

**Comment by LuisMi1245** [comment]
Or thank you very much for the explanation.  I am trying to run a Jupyterlab+Texlive+JupyterLSP+Texlab environment using fedora inside termux on an aarch64 (ARM) device running Android xD.  And I ran into the Rust dependencies problem.

**Comment by pfoerster** [comment]
> Or thank you very much for the explanation. I am trying to run a Jupyterlab+Texlive+JupyterLSP+Texlab environment using fedora inside termux on an aarch64 (ARM) device running Android xD. And I ran into the Rust dependencies problem.

Did 7f0a2ad4295be824b2576f0a1f9131cd61a8b3f6 help? If the issue still persists, you might want to report a issue at the `cargo` repository.
