### ISSUE TITLE
Autocomplete in \ref{} is empty when using colon.

### ISSUE THREAD

**Issue by WannabeSmith** [latex-lsp/texlab#599]
**OS/editor details:**

OS: macOS Monterey 12.3.1
Editor: Emacs 28.1
LaTeX: TeX Live 2022
texlab version: 3.3.2

**Description of the issue:**

When referring to a section, the autocomplete breaks if I enter a colon ":". 

It's a common convention to use colons in section/subsection/theorem/proposition/etc. labels. Thus, I might give my introduction the label `\label{section:introduction}`, but if I'd like to see an autocompleted list of all sections, it breaks as soon as I type the colon separating "section" and "introduction". This also means I cannot see all Theorems/Propositions at a glance. See the following screen capture.

https://user-images.githubusercontent.com/5490890/162868400-ce517788-bdd2-4e1a-a99d-e3fd0b4bed7a.mov

**Comment by clason** [comment]
I think this is an issue with Emacs; this is working fine on Neovim.

**Comment by WannabeSmith** [comment]
You're right, this doesn't seem to happen in VSCode either. Thanks!
