### ISSUE TITLE
Incorrect undefined reference warning (and Overfull \hbox) for multi-file documents.

### ISSUE THREAD

**Issue by WannabeSmith** [latex-lsp/texlab#600]
**OS/editor details:**

OS: macOS Monterey 12.3.1
Editor: Emacs 28.1
LaTeX: TeX Live 2022
texlab version: 3.3.2

**Description of the issue:**

If I have a document `main2.tex` that has two input files `introduction.tex` and `methods.tex`, then any references between `introduction.tex` and `methods.tex` are reported as "undefined" by texlab. 

Consider the following three-file setup.

### main2.tex
```latex
\documentclass{article}

\begin{document}

\input{introduction}

\input{methods}

\end{document}
```

### introduction.tex
```latex
\section{Introduction}
\label{section:introduction}
```

### methods.tex
```latex
\section{Methods}
\label{section:methods}

In Section~\ref{section:introduction}, we introduced things.
```

Then, texlab will generate a warning in `methods.tex` saying that the reference `section:introduction` is undefined (and there will also be Overfull \hbox warnings --- not sure where those are coming from).

See the following screen capture for a demo.

https://user-images.githubusercontent.com/5490890/162870734-118136aa-601b-45a3-92aa-65b35017876b.mov

**Comment by WannabeSmith** [comment]
Seems to persist in VSCode so it looks like this isn't an emacs-specific issue.

<img width="570" alt="Screen Shot 2022-04-12 at 8 48 40 AM" src="https://user-images.githubusercontent.com/5490890/162965879-b85daf6b-9d69-4d56-b56c-7225afc72eae.png">

**Comment by clason** [comment]
That's a LaTeX warning, though, that is just passed through via texlab. Are you sure the project is built fully (running `pdflatex` multiple times to generate all references)?

**Comment by clason** [comment]
Yes, of course. (I test with Neovim, but that should make no difference here.)

Again, these are warnings generated by LaTeX that are found in the `aux` file. How do you build the document?

**Comment by WannabeSmith** [comment]
I'm using the AUCTeX-latexmk command provided in emacs, but it's not transparent to me exactly what it's doing. Indeed, when I run latexmk from the command line, these issues do not arise. If I use vanilla AUCTeX with latexmk, these issues do not arise, so there's some collection of moving pieces (between AUCTeX, lsp-mode, and texlab) that do not play well together. 

Closing since it seems this is a client issue (not server).
