### ISSUE TITLE
UX feature request: do not autocomplete unless something has been typed.

### ISSUE THREAD

**Issue by WannabeSmith** [latex-lsp/texlab#601]
**OS/editor details:**

OS: macOS Monterey 12.3.1
Editor: Emacs 28.1
LaTeX: TeX Live 2022
texlab version: 3.3.2

**Description of the issue:**

Suppose I wish to start writing a new section in a tex document. If I type `\section{New Section}` and then hit enter, my cursor doesn't go to the next line. Instead, I will receive an autocompleted `\item`, but I am not even in an itemize/enumerate environment. 

Similarly, every time a space is typed, an autocomplete list will appear with `\item` as the top choice.

The desired behavior would be to never see an autocompleted list _unless a character has been typed_.

See the following screen capture that demonstrates this behavior.

https://user-images.githubusercontent.com/5490890/162873200-b7b3cd25-1881-4b1f-9219-f4ec973e9b69.mov

**Comment by clason** [comment]
This, too, is controlled by your LSP _client_ (Emacs in this case), not the server!

**Comment by WannabeSmith** [comment]
You're right, this doesn't seem to happen in VSCode either. Thanks!
