### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by motorto** [latex-lsp/texlab#602]
Hey guys the following code:

```latex
\newcommand{\CVSubHeadingListStart}{\begin{itemize}[leftmargin=0.5cm, label={}]}
\newcommand{\CVSubHeadingListEnd}{\end{itemize}}
\newcommand{\CVItemListStart}{\begin{itemize}}
\newcommand{\CVItemListEnd}{\end{itemize}\vspace{-5pt}}
```

Returns the following errors about missing parenthesis ?
![image](https://user-images.githubusercontent.com/52639805/163670929-e73a0e42-bbdf-479c-a3ad-a07739dc581a.png)

I don't know what else to provide, but to me it seems that is a parser error (or I am doing something stupid in my end)

Happy Easter !

**Comment by clason** [comment]
Works for me; but the diagnostics sometimes need a bit of time to "catch up". Try editing (or reloading) the buffer to force a sync.

**Comment by motorto** [comment]
hum weird ... 

<details> 
  <summary>here is a minimal tex file but it gives me the same error. </summary>
   
```latex
\documentclass[A4,11pt]{article}
\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage[english]{babel}
\usepackage{tabularx}
\usepackage{tikz}
\input{glyphtounicode}

\usepackage{palatino}

\addtolength{\oddsidemargin}{-1cm}
\addtolength{\evensidemargin}{-1cm}
\addtolength{\textwidth}{2cm}
\addtolength{\topmargin}{-1cm}
\addtolength{\textheight}{2cm}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0cm}

% Sections formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

% Ensure that .pdf is machine readable/ATS parsable
\pdfgentounicode=1

%-----CUSTOM COMMANDS FOR FORMATTING SECTIONS----------------------------------
\newcommand{\CVItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\CVSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \small#3 & \small #4 \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\CVSubSubheading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \text{\small#1} & \text{\small #2} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\CVSubItem}[1]{\CVItem{#1}\vspace{-4pt}}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\CVSubHeadingListStart}{\begin{itemize}[leftmargin=0.5cm, label={}]}
\newcommand{\CVSubHeadingListEnd}{\end{itemize}}
\newcommand{\CVItemListStart}{\begin{itemize}}
\newcommand{\CVItemListEnd}{\end{itemize}\vspace{-5pt}}

\begin{document}

\section{Education}
  \CVSubHeadingListStart
%    \CVSubheading % Example
%      {Degree Achieved}{Years of Study}
%      {Institution of Study}{Where it is located}
    \CVSubheading
      {{School $|$
				\emph{\small{Formation centered in Computer Science}}}}{2018-Ongoing}
      {University of Europe}{Europe}
  \CVSubHeadingListEnd

\section{Skills}
 \begin{itemize}[leftmargin=0.5cm, label={}]
    \small{\item{
        \textbf{Languages}{: Portuguese (Native), English (B1), Spanish (A2) } \\
        \textbf{Programming}{: C, Shell Scripting, Java, Assembly } \\
        \textbf{Document Creation}{: Microsoft Office Suite, LaTeX , Markdown} \\
        \textbf{Operating Systems}{: Unix based(Linux and BSD), Windows}
    }}

 \end{itemize}
\end{document}
```
</details>

![image](https://user-images.githubusercontent.com/52639805/163672000-fea3ea81-b2a9-4014-b2ba-b63aca502290.png)

**Comment by clason** [comment]
OK, in that context, I get the same errors.

(Ah, I see my error -- Neovim's LSP client _still_ doesn't fully work when opening an empty file and then setting the filetype... 😠 )

**Comment by pfoerster** [comment]
Thanks for the report. This happens with VSCode as well. This bug stems from the parser; it tries to complete the `itemize` environment, which causes the error about the unexpected `}`. I think we should handle this case the same way that we do in the `tree-sitter` grammar.

**Comment by motorto** [comment]
> This bug stems from the parser; it tries to complete the `itemize` environment, which causes the error about the unexpected `}`

Should I change the name of the issue then since it's not an error on the parser ?

**Comment by pfoerster** [comment]
> Should I change the name of the issue then since it's not an error on the parser ?

The title is fine. It is an error of the parser (we do not use the `tree-sitter` grammar in the server).

**Comment by pfoerster** [comment]
Can you give eec02390716fcf4fbf01de9afa975853e9267082 a try, please?

**Comment by motorto** [comment]
Sure, it seems to be working fine. In that use case the error seems to 
be fixed.

**Comment by motorto** [comment]
> Is that inside a math environment? (It's not legal outside.)

Yup my error. 

*Probably should close this issue, but I am not sure if there was a new  release since *

**Comment by pfoerster** [comment]
> Did find a new one I think \usepackage{amsmath} package

This error is actually reported by `latex` itself and not `texlab` ;)

>  but I am not sure if there was a new release since

`texlab 4.0.0` is now released 🚀
