### ISSUE TITLE
could texlab in neovim provide a tool recipe?

### ISSUE THREAD

**Issue by thedawnboy** [latex-lsp/texlab#606]
### Needs
I usually write a .tex file which consists of Chinese and citations . As the latex tutorial says , it needs a tool recipe `xelatex->bibtex->xelatex->xelatex` to perfectly show the pdf file. But int the settings of texlab , I could just see only one option : `xelatex` or `latexmk` or else. So I want to know whether texlab can work this out?

**Comment by clason** [comment]
latexmk can handle this it you create a `.latexmkrc`.

**Comment by thedawnboy** [comment]
Thanks for your help

**Comment by pfoerster** [comment]
> latexmk can handle this it you create a .latexmkrc.

Yeah, I agree. I do not think that `texlab` should try to make another build system as existing tools like `latexmk` already do a good job.
