### ISSUE TITLE
Update crossbeam-utils

### ISSUE THREAD

**Issue by niluxv** [latex-lsp/texlab#630]
The `Cargo.lock` in the repo contains `crossbeam-utils` version 0.8.6, which is yanked due to [a soundness issue](https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-qc84-gqf4-9926). It would therefore be good to update `crossbeam-utils`. A semver compatible (i.e. patch version bump) fixed version of `crossbeam-utils` is available (version 0.8.7 or 0.8.8), so running `cargo update` should be enough to fix the issue.

**Comment by pfoerster** [comment]
Thanks for the report! `cargo update` did the trick.
