### ISSUE TITLE
Forward search not working with outdir

### ISSUE THREAD

**Issue by tiagovla** [latex-lsp/texlab#635]
This is a duplicate of #147. I could not get it to work with zathura + neovim.
It works fine if the aux/output files are inside the current directory, i.e. `.`.
It does not if the aux/output files are in a subfolder, e.g. `./build`.

## Versions
Texlab: 4.0.0
Latexmk: 4.77
Nvim: v0.8.0-dev

## Settings
```lua
    settings = {
        texlab = {
            diagnosticsDelay = 50,
            build = {
                outputDirectory = "build",
                auxDirectory = "build",
                executable = "latexmk",
                args = {
                    "-pdf",
                    "-pdflatex=lualatex",
                    "-quiet",
                    "-interaction=nonstopmode",
                    "-synctex=1",
                    "-shell-escape",
                    "-pv",
                    "-f",
                    "-outdir=build",
                    "%f",
                },
            },
            forwardSearch = {
                args = { "--synctex-forward", "%l:1:%f", "%p" },
                executable = "zathura",
            },
            chktex = { onOpenAndSave = true, onEdit = false },
            formatterLineLength = 120,
        },
    }
```

## Debugging
I noticed that `zathura` is not called if the pdf file is not present in the current directory (`.`).
If it is present, forward search succeeds using the current directory file path.
No info on texlab's logs.
I suspect `texlab` searches for the pdf file in the current directory, doesn't find it and errors out without calling zathura.

**Comment by pfoerster** [comment]
Thanks for the detailed report. It looks like your configuration is not valid. The `auxDirectory` setting needs to be moved one level up: `texlab.auxDirectory`. The `texlab.build.outputDirectory` does not exist anymore so the value will be ignored.

**Comment by tiagovla** [comment]
@pfoerster I tried it with ``texlab.auxDirectory`` too. It isn't working for me. I still get `Search Error`.

**Comment by pfoerster** [comment]
@tiagovla From which directory are you calling `nvim`? 
`texlab` currently searches the following directories for PDF files:

- If `texlab.rootDirectory` is set: `<current working directory>/<texlab.rootDirectory>/<file_name>.pdf`
- If `texlab.auxDirectory` is set: `<current working directory>/<texlab.auxDirectory>/<file_name>.pdf`
- `<directory of TeX file>/<file_name>.pdf`

I think the problem is that the working directory cannot be relied on with this setup.

**Comment by tiagovla** [comment]
I was calling `nvim` within a sub directory inside my .git project. I tried to move it to my project's root and it also didn't work.
I think I found the cause. [Lspconfig](https://github.com/neovim/nvim-lspconfig/blob/80e101e7ec12835737f35452f07a94d9cc2e690d/lua/lspconfig/server_configurations/texlab.lua#L71) was setting the root directory to my home instead of the .git path.
Now if my current working directory is the root directory it works.
It would be nice if texlab could check `<current working directory>/<texlab.auxDirectory>/<file_name>.pdf` anyways.

**Comment by pfoerster** [comment]
> It would be nice if texlab could check <current working directory>/<texlab.auxDirectory>/<file_name>.pdf anyways.

This path is always checked even if `texlab.rootDirectory` is set. However, I added another set of paths to the search list, which should prevent this problem in the future:

```
<directory of TeX file>/<texlab.rootDirectory>/<file_name>.pdf
<directory of TeX file>/<texlab.auxDirectory>/<file_name>.pdf
```
