### ISSUE TITLE
Accept commands in `\includegraphics` argument

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/texlab#641]
![image](https://user-images.githubusercontent.com/40038251/171948574-a1fde098-7e98-4c01-8c47-1ea54805d0ec.png)

Even though there is no problem in using commands in `\includegraphics` argument, texlab indicates an error.

**Comment by pfoerster** [comment]
Thanks for the report. This should be fixed by a57735193f2f9eb4d3d392e552f4a1bdf31b07b0.

**Comment by pfoerster** [comment]
Released with `v4.1.0`
