### ISSUE TITLE
Change engine to xelatex in Neovim

### ISSUE THREAD

**Issue by Spaceface16518** [latex-lsp/texlab#651]
The solution presented in #263 makes sense but for some reason it is not working on neovim.

My configuration is as follows.

```lua
require'lspconfig'.texlab.setup{
    settings = {
        texlab = {
            build = {
                args = { "-pdf", "-pdflatex=xelatex", "-interaction=nonstopmode", "-synctex=1", "%f" }
            }
        }
    }
}
```

But diagnostics still show the same error and suggest that I switch to xelatex.

Is there something obvious I'm missing? Or is this just broken.

**Comment by pfoerster** [comment]
> But diagnostics still show the same error and suggest that I switch to xelatex.

Does your log file mention `xelatex`? `texlab` itself does not care about the TeX engine you are using (in fact, it does not need a TeX engine for most features) so these errors are originate from `latex`; `texlab` only forwards these errors from the build log to `neovim`.

**Comment by pfoerster** [comment]
> My configuration is as follows.

I have found one bug in `texlab` (there is an easy fix). The config does not apply if you do not specify the build `executable` as well. As a workaround you can set `texlab.build.executable` to `latexmk`.

**Comment by Spaceface16518** [comment]
Oh okay thank you so much!

**Comment by pfoerster** [comment]
bd85205f0da9811d45bd27136f61e5ecc0f769ee is part of the `4.2.0` release
