### ISSUE TITLE
chktexrc not working

### ISSUE THREAD

**Issue by j2kun** [latex-lsp/texlab#683]
I can't get texlab to recognize `chktexrc` or `.chktexrc` in the root of my project, even though I see in https://github.com/latex-lsp/texlab/issues/309 that support is supposed to be there for it.

Is there a command I can run to determine what texlab considers to be the root of my project? Maybe that will help me debug it a bit further.

**Comment by pfoerster** [comment]
Thanks for the report.

> Is there a command I can run to determine what texlab considers to be the root of my project?

Unfortunately not, however you could try setting `texlab.rootDirectory` to give `texlab` a hint. If the root directory is not specified, `texlab` uses the directory of the root file (basically a file that contains a `document` environment with some special handling for the `subfiles` package).

I have been thinking for a while now about a better mechanism to discover the project, the current method is definitely not perfect. To be 100% sure, we would need something like `compile_commands.json` or `Tectonic.toml` for general `latex` projects.

Btw. which client are you using? From which directory are you opening the document (`texlab` uses the current working directory to make paths absolute if needed)?

**Comment by j2kun** [comment]
I am using neovim 0.7.0 with settings

```
settings = {
  texlab = {
     chktex = {
        onEdit = true,
        onOpenAndSave = true
     }
   },
}
```

And I'm loading nvim from the same directory as the file that contains the `\begin{document}` environment (and vim's `pwd` is not being manipulated by any other plugin). Though I am opening a file which is included indirectly in that document by two layers of indirection (`main.tex` includes `chapters/foo.tex, which in turn includes `sections/bar.tex`, and I'm opening `sections/bar.tex`). My `.chktexrc` is in the same directory as `main.tex`, so I would not expect the layers of indirection to matter, if all we're doing is looking for `.chktexrc`.

I see the same effect when I cd to `sections/` and open a file from there. Both appear to not be able to find my `.chktexrc`, but when I run `chktex` manually from the base directory, it follows that configuration as expected.

Are you suggesting that adding a sentinel file like `Tectonic.toml` to my root directory would fix this issue? On trying that I see no change in behavior.

Is there a suitable place in the codebase I could write some print statements to get the debug info I need? And then maybe launch texlab with a flag that writes to a log file? I'm happy to patch in a local change to my installation.

**Comment by j2kun** [comment]
Another interesting tidbit, though the config above says "onOpenAndSave = true", I only see the incorrect linting on save, not on opening the file.

**Comment by pfoerster** [comment]
Thanks for the details. Can you try 170a854418221bfbfd958c288e95a21068e3b11f, please? Before that commit, `texlab` would use one your sub-directories to look for the `chktexrc` file, which is not correct. Also it adds a logging statement wit the working directory passed to `chktex`.

> Are you suggesting that adding a sentinel file like Tectonic.toml to my root directory would fix this issue?

Not yet, but it should help prevent issues like these where the wrong directory ends up being used (especially the `cwd` of the server process).

**Comment by j2kun** [comment]
I did this (very easy to set up, thanks!!) and now I see

`DEBUG - Calling ChkTeX from directory: /home/j2kun/pmfp-source/tips`

While the `.chktexrc` is in the parent directory (`pmfp-source`). I can confirm that invoking `chktex` manually from that directory reproduces what texlab reports. So it appears that this subdirectory is being marked as the project root. However, that directory only contains `.tex` files with no `documentclass` or `\begin{document}` in it.

**Comment by j2kun** [comment]
It is also perhaps interesting to note that the `pwd` of neovim during this process is indeed `/home/j2kun/pmfp-source/`. I had previously suspected that `neovim` was changing `pwd` and hence sending a different file path to the LSP, but I suppose it always sends the filepath of the file in the current buffer.

**Comment by pfoerster** [comment]
@j2kun Thanks for the feedback. Can you try d02b258b3cf1dbb937413176a3987eaf583c6dfa, please? I think it might use the wrong directory because it cannot link the file containing `\begin{document}` with the subdirectory. Nevertheless, it is better to use the `chktexrc` file if there is one located in one of the parent directories.

**Comment by j2kun** [comment]
After that commit, the debug statement in 170a854418221bfbfd958c288e95a21068e3b11f now prints the correct directory. However, the linter still ignores my `.chktexrc`

Reading through the code from that file, I believe the problem is that the filename in `lint` is assumed to be `chktexrc` (not `.chktexrc`) even though both are supported in the discovery mechanism. Compiling with the following patch makes it behave properly for me

```
diff --git a/src/diagnostics/chktex.rs b/src/diagnostics/chktex.rs
index ec7f6530..f1190784 100644
--- a/src/diagnostics/chktex.rs
+++ b/src/diagnostics/chktex.rs
@@ -79,8 +79,8 @@ fn lint(text: &str, current_dir: &Path) -> io::Result<Vec<Diagnostic>> {
     let directory = tempdir()?;
     fs::write(directory.path().join("file.tex"), text)?;
     drop(fs::copy(
-        current_dir.join("chktexrc"),
-        directory.path().join("chktexrc"),
+        current_dir.join(".chktexrc"),
+        directory.path().join(".chktexrc"),
     ));

     let output = Command::new("chktex")
```

However, if you want to support both filenames as options I don't know enough paradigmatic rust to say how best to discover the right filename and pass it along.

Hope that helps! Now at least in the worst case I can sit on my patch and stop bugging you :)

**Comment by pfoerster** [comment]
> However, if you want to support both filenames as options I don't know enough paradigmatic rust to say how best to discover the right filename and pass it along.

No problem, there is a now a copy operation for both files :)

> Offhand, I wonder if there's a specific reason one wouldn't want to run the chktex subprocess directly from the user's discovered project root, rather than copy things to a temporary file.

We had some problems in the past with that approach (especially with `latexindent`, see here https://github.com/latex-lsp/texlab/issues/437#issuecomment-853149264). I really want to avoid the temporary directory but I have not tracked down the source of the problem yet.

> Hope that helps!

Definitely 👍
