### ISSUE TITLE
Thread 'main' panicked at 'index out of bounds ...'

### ISSUE THREAD

**Issue by SunJukebox** [latex-lsp/texlab#724]
Whenever I save a latex (.tex) file in neovim (stable, 0.7.2) with texlab running, the texlab instance crashes.  The error message that it spits out when I set `RUST_BACKTRACE=full` is

>[ERROR] .../vim/lsp/rpc.lua:420	"rpc"	"texlab"	"stderr"	"thread 'main' panicked at 'index out of bounds: the len is 10 but the index is 10', src/line_index.rs:117:9\nstack backtrace:\n   0:     0x5570bf175944 - <unknown>\n   1:     0x5570bf0459ec - <unknown>\n   2:     0x5570bf171725 - <unknown>\n   3:     0x5570bf1774ba - <unknown>\n   4:     0x5570bf1771a9 - <unknown>\n   5:     0x5570bf177b0a - <unknown>\n   6:     0x5570bf1779e4 - <unknown>\n   7:     0x5570bf175e74 - <unknown>\n   8:     0x5570bf17774d - <unknown>\n   9:     0x5570befb43e3 - <unknown>\n  10:     0x5570befb4322 - <unknown>\n  11:     0x5570bf214f81 - <unknown>\n  12:     0x5570bf232ff7 - <unknown>\n  13:     0x5570bf1ab8ab - <unknown>\n  14:     0x5570bf2379f5 - <unknown>\n  15:     0x5570bf0d81c0 - <unknown>\n  16:     0x5570befcc7a3 - <unknown>\n  17:     0x5570befd17dd - <unknown>\n  18:     0x5570bf16a8ae - <unknown>\n  19:     0x5570bf0d9062 - <unknown>\n"
>[ERROR] .../vim/lsp/rpc.lua:420	"rpc"	"texlab"	"stderr"	"  20:     0x7f98b9b422d0 - <unknown>\n  21:     0x7f98b9b4238a - __libc_start_main\n  22:     0x5570befcae05 - <unknown>\n  23:                0x0 - <unknown>\nthread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: \"SendError(..)\"', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.6.0/src/stdio.rs:29:37\nstack backtrace:\n  "

For the sake of completeness, the source .tex file is

> \documentclass{article}
>
>\title{Test}
>
>\begin{document}
>
>\maketitle
>
>\end{document}

However, when I run `texlab -vvvv --log-file texlab.log` instead of `texlab`, this error no longer appears; texlab runs without any hitches.  I have no clue as to why this is the case.  Thank you for any help you can offer.

**Comment by clason** [comment]
can you share your Neovim configuration for texlab?

**Comment by SunJukebox** [comment]
```
cmd = { "texlab" },
settings = {
  texlab = {
    build = { onSave = true },
      forwardSearch = {
        executable = "zathura",
        args = { "--synctex-forward", "%l:1:%f", "%p" },
      },
    },
  },
}
```

**Comment by clason** [comment]
and what's your texlab version?

**Comment by clason** [comment]
try specifying the full set of `build` arguments (see documentation)

**Comment by SunJukebox** [comment]
I am running version 4.2.1 .  Thank you for the suggestion.  I just tried with
```
build = {
          executable = 'latexmk',
          args = { '-pdf', '-interaction=nonstopmode', '-synctex=1', '%f' },
          onSave = false,
          forwardSearchAfter = false,
},
```
(keeping everything else the same), and I still received the same error.

**Comment by pfoerster** [comment]
Thanks for the report!

This problem is likely not caused by the `build` feature. Instead, `texlab` likely receives another `textDocument/*` request, which causes a lookup in the `LineIndex` so that the server can map line/column UTF-16 positions to UTF-8 offsets, which are used internally. Afterwards, the UTF-8 offsets are converted back to the LSP representation.

@SunJukebox
Does the example document include a final newline? The `10` in the panic message is the line number.

**Comment by SunJukebox** [comment]
Thanks for the detailed reply.  There should be a final newline in the example that I did not add.  Also, I want to add that, after downgrading texlab to v. 4.1.0, I no longer have this issue.

**Comment by pfoerster** [comment]
I think I have found the issue. Can you try out https://github.com/latex-lsp/texlab/pull/730, please? The currently released version wrongly reloads the TeX file after saving, even if it still open in the editor. This can result in a text synchronization issue.

**Comment by SunJukebox** [comment]
Thank you @pfoerster for your help.  Using texlab compiled from the issue-724 branch fixed the issue.
