### ISSUE TITLE
Excessive RAM usage

### ISSUE THREAD

**Issue by Lrrrence** [latex-lsp/texlab#737]
I am experiencing excessive RAM usage (attributed to texlab by process explorer), which occurs after the running of a recipe. The RAM usage continues to build after each execution of the recipe. I assume this is supposed to be flushed after completion?

**Comment by Lrrrence** [comment]
Sorry I should have been more specific, a LaTeX workshop recipe. CPU usage continues after a pdf has been produced, for around a minute, and RAM usage builds up during this time. In my case (30 pages, 15 figures) RAM increases by around 800MB per run, but I think it increases each time.

**Comment by pfoerster** [comment]
@Lrrrence 

I was able to reproduce and fix the issue (released with `texlab 4.2.2`). There was a problem where the file watcher kept watching the same file multiple times (accumulating with each build).
