### ISSUE TITLE
Misplaced error marker

### ISSUE THREAD

**Issue by vigoux** [latex-lsp/texlab#738]
Hi, using the following file, the `Undefined control sequence` error is declared at the start of the line, while it happens a lot later.

Is it something to be expected ?

```tex
\documentclass{article}

\begin{document}

Foo \bleh{bar}. % Error reported at the start of this line
%    ^^^^ should be reported here.

\end{document}
```

**Comment by vigoux** [comment]
From what I see of the code, changing the `TEX_ERROR_REGEX` to the following:
```regex
(?m)^! ((?P<msg1>(.|\r|\n)*?)\r?\nl\.(?P<line>\d+)|(?P<msg2>[^\r\n]*)) (\.\.\.)?(?P<hint>.+)
```

This would allow to at least capture a `hint` group that show the placement of the context of the error.

I'll try to see if I can hack something in.

**Comment by pfoerster** [comment]
Thanks for the report.

> Is it something to be expected ?


Kind of at the moment. The current log parser is quite simple in this regard and only uses the `l.5` line to determine the error range.

> I'll try to see if I can hack something in.

Thanks! This would be a nice addition.
