### ISSUE TITLE
`window/progress/cancel` has been renamed to `window/workDoneProgress/cancel`

### ISSUE THREAD

**Issue by fannheyward** [latex-lsp/texlab#74]
diff: https://github.com/microsoft/vscode-languageserver-node/commit/cd6dcf0e1cf0f8e3b14b78b3322857f6f636ee7d#diff-040a285d08fc2f2369426d06c299ced3L131

doc: https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.progress.proposed.md#work-done-progress-cancel-notification-leftwards_arrow

**Comment by efoerster** [comment]
Thanks for the report. 3e829d8cd3f2c6709fc72d59404450d4cecc8d39 updates the LSP progress support to the latest version.
