### ISSUE TITLE
Compilation errors do not show up when file path contains spaces

### ISSUE THREAD

**Issue by Doltonius** [latex-lsp/texlab#754]
As in the title. If I have a file in a directory whose name contains spaces, the compilation errors do not show up. As soon as I remove the spaces, the errors appear upon each build.

**Comment by pfoerster** [comment]
Thanks for the report.

> If I have a file in a directory whose name contains spaces, the compilation errors do not show up

I think that the problem might be that `texlab` uses URL encoding when sending LSP messages. Maybe `Neovim` expects URIs without URL encoding so it treats `file:///foo%20bar` and `file:///foo bar` as different documents so the diagnostics are never shown in the client.

To be honest, I am not really sure which side is right. It looks like LSP does not specify whether URLs should be encoded or not (VSCode uses URL encoding but the spec does not mention it).

**Comment by pfoerster** [comment]
Thinking more about this, I have to say, that this is probably a Neovim issue or a general LSP issue rather than a `texlab` issue. Without URL encoding, you would be limited in the allowed file names that LSP can process.
