### ISSUE TITLE
Wrong file built in a directory with multiple main files

### ISSUE THREAD

**Issue by Doltonius** [latex-lsp/texlab#757]
As in the title. If there are many main files in the same directory, running `TexlabBuild` on one of the files could result in one or more different files being built; the file actually open may or may not get built. I know it's probably not good practice to keep multipole main files in the same directory, but still this doesn't seem to be the desired behavior.

**Comment by pfoerster** [comment]
Thanks for the report. This one is a bit difficult to diagnose. I have a few questions:
- Do you use the `subfiles` package?
- Does each main file have a `document` environment in the same file?
- Do you use `tectonic`?
- Do the main files (indirectly) share code?

**Comment by Doltonius** [comment]
- No `subfiles`
- Each main file has a `document` env
- Not using tectonic; I am just using `lualatex` from my TeX distro
- They share a single `.bib` file; nothing else is shared

**Comment by Doltonius** [comment]
I think the shared `.bib` file can be the problem. I tried building multiple main files in another directory where the files don't share a `.bib` file, nothing surprising happens.

**Comment by pfoerster** [comment]
> I think the shared .bib file can be the problem.

@Doltonius Yeah, this can definitely be a problem for `texlab`. Due to the way, the current algorithm works, all files are thrown together into one "project". That's why, the selection of the root file is arbitrary in this case.

I am currently working on a fix but this might take some more time.
