### ISSUE TITLE
Wrong Okular documentation about forward search with VSCode

### ISSUE THREAD

**Issue by kien-truong** [latex-lsp/texlab#768]
The current documentation is suggesting that you can setup Okular forward search in VSCode with these settings

```
{
  "texlab.forwardSearch.executable": "okular",
  "texlab.forwardSearch.args": ["--editor-cmd": "code -g \"%%f\":%%l", "--unique", "file:%p#src:%l%f"]
}
```

However, these settings break forward search when Okular is already opened, with the following error

```
You cannot set the editor command in an already running okular instance. Please disable the tabs and try again. Please note, that unique is also not supported when setting the editor command at the commandline.
```

The `---editor-cmd` argument should be removed.

**Comment by pfoerster** [comment]
Thanks for the hint, I have updated the `Okular` section in the documentation :+1:
