### ISSUE TITLE
Incorrect Unexpected "}" when using \graphicspath

### ISSUE THREAD

**Issue by HawkinsT** [latex-lsp/texlab#789]
This issues appears to be the same as #568, only for `\graphicspath` (from the `graphics`/`graphicsx` package).

Tested in neovim 0.8.0 on arch linux.

**Reproduce**
Create a blank .tex file with contents `\graphicspath{test}` (it doesn't occur if there is no content or only spaces in the curly brackets).

Adding square brackets, e.g. `\graphicspath[]{test}` gets rid of this issue.

**Comment by pfoerster** [comment]
Thanks for the report. This should be fixed by baf82d13cb0ab411d78e373b4f3565e12de6ee19.

**Comment by HawkinsT** [comment]
No problem and thanks for the quick fix.

Unfortunately in testing, that fixes the specific case I reported, but there are still fringe cases with false positives if you have a command inside of the curly brackets that also uses curly brackets, e.g. `\graphicspath{\test{}}` will still produce the error. This is relevant to specific use cases such as when using the `subfiles` package, e.g. `\graphicspath{{\subfix{./img/}}}`.

**Comment by pfoerster** [comment]
@HawkinsT Thanks for the quick response. Can you try the latest master again, please?

**Comment by HawkinsT** [comment]
Thanks, @pfoerster. This now appears to be fully working for me.
