### ISSUE TITLE
Error when trying to do forward search with zathura

### ISSUE THREAD

**Issue by onekk** [latex-lsp/texlab#791]
Texlab seems not to issue the correct synctex command when using zathura as pdf viewer.

I'm using lsp-latex and I have this issue:

[https://github.com/ROCKTAKEY/lsp-latex/issues/36](url)

lsp-latex developer has identified texlab as possible culprit basing on this error report.

```
DEBUG - < {"jsonrpc":"2.0","method":"textDocument/forwardSearch","params":{"textDocument":{"uri":"file:///home/common/Remote/Scripting_FreeCAD/It/cap/ba.tex"},"position":{"line":327,"character":19}},"id":4015}

DEBUG - > {"jsonrpc":"2.0","id":4015,"result":{"status":1}}
{"jsonrpc":"2.0","id":4015,"result":{"status":1}}
DEBUG - < {"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/common/Remote/Scripting_FreeCAD/It/cap/ba.tex"}},"id":4016}

DEBUG - < {"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///home/common/Remote/Scripting_FreeCAD/It/cap/ba.tex"},"position":{"line":327,"character":19}},"id":4017}

DEBUG - > {"jsonrpc":"2.0","id":4016,"result":[]}
DEBUG - > {"jsonrpc":"2.0","id":4017,"result":null}
DEBUG - < {"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/common/Remote/Scripting_FreeCAD/It/cap/ba.tex"}},"id":4018}

DEBUG - < {"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///home/common/Remote/Scripting_FreeCAD/It/cap/ba.tex"},"position":{"line":327,"character":19}},"id":4019}

DEBUG - > {"jsonrpc":"2.0","id":4018,"result":[]}
DEBUG - > {"jsonrpc":"2.0","id":4019,"result":null}
DEBUG - < {"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/common/Remote/Scripting_FreeCAD/It/cap/ba.tex"}},"id":4020}

DEBUG - < {"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///home/common/Remote/Scripting_FreeCAD/It/cap/ba.tex"},"position":{"line":323,"character":81}},"id":4021}

DEBUG - < {"jsonrpc":"2.0","method":"textDocument/hover","params":{"textDocument":{"uri":"file:///home/common/Remote/Scripting_FreeCAD/It/cap/ba.tex"},"position":{"line":323,"character":81}},"id":4022}

DEBUG - > {"jsonrpc":"2.0","id":4020,"result":[]}

```

He says that Zathura is exiting with an error when invoking it using lsp-latex.

I'm using texlab server downloaded from 

[https://github.com/latex-lsp/texlab/releases/tag/v4.3.0](url)

and installed in /usr/local

Regards

Carlo D.

**Comment by pfoerster** [comment]
Thanks for the report.

Looking at the log, I can tell that `texlab` is not actually calling `zathura` because it does not print the command line arguments before executing the PDF viewer. Otherwise, it would print a line starting with "Executing forward search".

So there are two remaining reasons on why the forward search can fail:
1. `texlab` is unable to detect the main document (relevant for multi-file projects)
2. `texlab` cannot find a PDF file

In the original issue, I noticed that you have set `texlab.rootDirectory` to `"."`.
Can you try removing this setting temporarily? It should only be set when absolutely necessary because it makes the server reliant on the editor's working directory.

**Comment by ROCKTAKEY** [comment]
So `lsp-latex.el` should not set any value by default as option, should it?
Then I will remove all default value.

**Comment by ROCKTAKEY** [comment]
@pfoerster I got it. I fix the default value to `nil`.

**Comment by ROCKTAKEY** [comment]
@onekk Is it resolved?

**Comment by onekk** [comment]
Yes now it is working as expected.

Sorry for the delay, I have update today 20221101 and everything is working now.

Many Thanks.

Regards

Carlo D.
