### ISSUE TITLE
[FR] Open the Wiki page for this Github repo

### ISSUE THREAD

**Issue by zhiyuanzhai** [latex-lsp/texlab#800]
Currently, every time I try to look up something in TexLab's docs, I have to dive into the `docs/` directory in this repo and search for the exact `.md` file that I'm looking for. It's really inconvenient.

GitHub provides a feature called "Wiki". It can be used to contain the documentaries in a better-looking way.

**Comment by zhiyuanzhai** [comment]
Related: [Adding or editing wiki pages](https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages)

**Comment by pfoerster** [comment]
Thanks for the suggestion. I have moved the documentation to the [wiki](https://github.com/latex-lsp/texlab/wiki) :+1:
