### ISSUE TITLE
LaTeX error: \usepackage before \documentclass

### ISSUE THREAD

**Issue by dpo** [latex-lsp/texlab#801]
When I open a `.sty` file with Neovim/Texlab, I get the error message
```tex
LaTeX error: \usepackage before \documentclass
```
next each `\usepackage{...}`. Of course, there is no `\documentclass` in style files. Those messages pollute the diagnostics significantly and make it difficult to sift through the messages.

**Comment by dpo** [comment]
Similarly, I have `\graphicspath{...}` in a `.sty` file, and I get the message `LaTeX Error: missing \begin{document}` next to it. There is no `\begin{document}` in style files.

**Comment by pfoerster** [comment]
Thanks for the report. It looks like the `.sty` file has been wrongly compiled. I added a check (29edf5ee9e1de88b0918141948cb198cfdce3ffb), which prevents compiling them.
