### ISSUE TITLE
expected Message::Notification, got: Notification

### ISSUE THREAD

**Issue by rezass** [latex-lsp/texlab#805]
Hi all,

Working with sample lsp_ws_proxy results in the following error in texlab.

`Oct 24 14:03:14.690  INFO Server::run{addr=0.0.0.0:3000}: warp::server: listening on http://0.0.0.0:3000
Oct 24 14:03:18.593  INFO lsp_ws_proxy::api::proxy: connected
Oct 24 14:03:18.594  INFO lsp_ws_proxy::api::proxy: starting texlab in file:///home/XXX/test/lsp-ws-proxy/
DEBUG - < {"jsonrpc":"2.0","method":"initialize","id":"0","params":{"processId":null,"rootUri":"file:///","capabilities":{"workspace":{"didChangeConfiguration":{"dynamicRegistration":true}},"textDocument":{"synchronization":{"dynamicRegistration":true,"willSave":false,"willSaveWaitUntil":false,"didSave":false},"completion":{"dynamicRegistration":true,"completionItem":{"snippetSupport":false,"commitCharactersSupport":true,"documentationFormat":["plaintext","markdown"],"deprecatedSupport":false,"preselectSupport":false},"contextSupport":false},"hover":{"dynamicRegistration":true,"contentFormat":["plaintext","markdown"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["plaintext","markdown"]}},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"moniker":{}}}}}

DEBUG - > {"jsonrpc":"2.0","id":"0","result":{"capabilities":{"completionProvider":{"resolveProvider":true,"triggerCharacters":["\\","{","}","@","/"," "]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentSymbolProvider":true,"executeCommandProvider":{"commands":["texlab.cleanAuxiliary","texlab.cleanArtifacts"]},"foldingRangeProvider":true,"hoverProvider":true,"inlayHintProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"textDocumentSync":{"change":2,"openClose":true,"save":{"includeText":false}},"workspaceSymbolProvider":true},"serverInfo":{"name":"TexLab","version":"4.3.0"}}}

DEBUG - < {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///test","languageId":"latex","version":0,"text":""}}}
Error: expected Message::Notification, got: Notification(Notification { method: "textDocument/didOpen", params: Object {"textDocument": Object {"languageId": String("latex"), "text": String(""), "uri": String("file:///test"), "version": Number(0)}} })
Oct 24 14:03:18.766 ERROR lsp_ws_proxy::api::proxy: server process exited unexpectedly`

**Comment by pfoerster** [comment]
@rezass It looks like your sample does not send a `initialized` notification, which is required by LSP. See here: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialized

**Comment by rezass** [comment]
@pfoerster You are correct. I just checked and the `initialized` notification was sent after the `textDocument/didOpen`.
