### ISSUE TITLE
Texlab quits with non-zero error code

### ISSUE THREAD

**Issue by AdityaRoot** [latex-lsp/texlab#825]
Heya, I'm currently using Mason, nvim-lspconfig, mason-lspconfig, and cmp-nvim-lsp and I'm having some issues with tex files. I currently load the copilot, ltex, and texlab LSPs for tex and while copilot and ltex attach fine - texlab crashes on startup with the notification `client 2 quit with exit code 0 and error code 1` (or any other client number). I tried reinstalling the server as well as ensuring all my packages and neovim are up to date (I'm on neovim 0.8.1).

I read up on the issues #405 #450 and unfortunately nothing mentioned there helped me as far as I could tell nor do their logs match mine, as with LspLogs I get:
```
[ERROR][2022-11-25 19:59:44] .../vim/lsp/rpc.lua:733	"rpc"	"texlab"	"stderr"	'Error: invalid type: string "utf-8", expected a sequence\n'
```

And with debug mode on the only additional information I get is 
`[INFO][2022-11-25 19:50:14] .../vim/lsp/rpc.lua:661	"Starting RPC client"	{  args = {},  cmd = "texlab",  extra = {    cwd = "/home/adi"  }}` 
which isn't too helpful if I'm not mistaken.

relevant config file: https://github.com/AdityaRoot/dotfiles/blob/master/.config/nvim/lua/adi/mason.lua

I get the same error regardless of whether the texlab lspconfig setup function override is completely commented out or uncommented.

Also, I read some comments about texlab finding the correct root directory, and according to :LspInfo texlab does locate the correct root directory, the results looking as follows:
![image](https://user-images.githubusercontent.com/66115252/203990443-20f0bc72-b00b-4b01-84d4-2485bead8de2.png)
(also where it says the texlab command is executable, :texlab is not recognized as a command when ran)

If relevant:
my node --version is 16.18.0, and there are no tex-relevant issues on :checkhealth
texlab version is 4.3.2 (no difference in error whether installed through package manager or cargo), and running texlab -vvvv --log-file gives no output in the file, instead I just get:
`Error: expected initialize request, got error: receiving on an empty and disconnected channel`

All the above errors just repeat themselves if I try to `:LspStart "texlab"` manually again.

I'd really appreciate any guidance with solving this issue! I've tried searching around for the past few hours but unfortunately nothing helped. I do believe that this error only came up after swapping to Mason, and that texlab worked fine with nvim-lsp-installer.

**Comment by pfoerster** [comment]
@AdityaRoot 
Thanks for the detailed report! It looks like `texlab` is failing to deserialize the `initialize` request. The problem is that you are passing `"utf-8"` as the offset encoding to `clangd` (and also to `texlab` due to reference semantics) but it actually needs to be `["utf-8"]` instead (see here: https://clangd.llvm.org/extensions.html#utf-8-offsets).

To quickly fix the issue, you can either change the `mason.lua` file such that it does not pass the `offsetEncoding` to `texlab` or you can change this [line](https://github.com/AdityaRoot/dotfiles/blob/master/.config/nvim/lua/adi/mason.lua#L40) to `{"utf-8"}` and both servers will be happy :)

**Comment by AdityaRoot** [comment]
> @AdityaRoot 
> Thanks for the detailed report! It looks like `texlab` is failing to deserialize the `initialize` request. The problem is that you are passing `"utf-8"` as the offset encoding to `clangd` (and also to `texlab` due to reference semantics) but it actually needs to be `["utf-8"]` instead (see here: https://clangd.llvm.org/extensions.html#utf-8-offsets).
> 
> To quickly fix the issue, you can either change the `mason.lua` file such that it does not pass the `offsetEncoding` to `texlab` or you can change this [line](https://github.com/AdityaRoot/dotfiles/blob/master/.config/nvim/lua/adi/mason.lua#L40) to `{"utf-8"}` and both servers will be happy :)

Thank you so much for the quick reply! Ahhh I see! I mistook the assignment hoping that it would only apply to clangd and there wouldn't be any reference shenanigans going on.

I hope this isn't out of bounds to ask, since I'm new to lua, might I ask how I would be able to modify offsetEncoding such that it passes the modified utf-8 flag only to clangd and not to every other server - since that's what I thought I was already doing (applying python logic ;;). Just so I don't have to lock myself down in case I want to change an option for another server.

If that's too off topic for the issue though - then can happily close it and I really appreciate your help!

**Comment by pfoerster** [comment]
@AdityaRoot 

> might I ask how I would be able to modify offsetEncoding such that it passes the modified utf-8 flag only to clangd and not to every other server 

You need to create a separate capabilities object for `clangd` (either through a deep copy of the existing object or by calling the method to generate the capabilities again).

However, I think it is easiest to just change this snippet
```
local clangd_capabilities = opts.capabilities
clangd_capabilities.offsetEncoding = "utf-8"
```

into
```
opts.capabilities.offsetEncoding = {"utf-8"}
```

and pass the same object to all servers.

> applying python logic

Actually, Python would behave the same in this situation ;)

**Comment by AdityaRoot** [comment]
That fixes it! Thank you so so much for the quick help! And thank you for maintaining texlab - it carries my terrible file and label naming conventions so hard. `\ref{fig:the_bluey_green_graph_thats_big_but_not_the_biggest_one}` is a pain to type out manually.

> Actually, Python would behave the same in this situation ;)

Pain. I have so much more to learn...
