### ISSUE TITLE
Customize citation commands

### ISSUE THREAD

**Issue by haoming-li-ling** [latex-lsp/texlab#832]
Is it possible to provide customized citation commands by the user? That way, citation key completion can be triggered on user-defined commands.

**Comment by pfoerster** [comment]
@Doltonius Not at the moment. In the past, I have post-poned the customization of the parsing rules  to allow breaking changes in the parser without affecting the user (https://github.com/latex-lsp/texlab/issues/21#issuecomment-505457399) but I think it is time to think again about this topic.

The question remains on how fine-grained the user should be able to tweak the custom commands. Just a plain list containing special commands for each category (labels/references, citations, ...) and `texlab` tries to make sense of it or let the user specify some kind of parser rule based on a set of pre-defined tokens/rules?

**Comment by Doltonius** [comment]
I guess for my (and I assume, most people's) purposes, the first, simpler option of supplying lists of custom commands for each category is enough.

**Comment by pfoerster** [comment]
There is now an experimental setting (`texlab.experimental.citationCommands`) to extend the list of citation commands. See here: https://github.com/latex-lsp/texlab/wiki/Configuration#texlabexperimentalcitationcommands
