### ISSUE TITLE
`TexlabBuild` error: unexpected message during shutdown

### ISSUE THREAD

**Issue by sbatial** [latex-lsp/texlab#833]
First off: Thanks for the great project. It's really useful for working with latex.

I have been using it for some time and it always worked as expected but since recently `TexlabBuild` won't work anymore.
The log shows the following:
```
[ERROR][2023-01-01 17:01:40] .../vim/lsp/rpc.lua:733	"rpc"	"texlab"	"stderr"	"thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: \"SendError(..)\"', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.6.0/src/stdio.rs:29:37\nstack backtrace:\nError: unexpected message during shutdown: Request(Request { id: RequestId(I32(8)), method: \"shutdown\", params: Null })\n"
```
Sometimes also just:
```
[ERROR][2023-01-01 17:14:15] .../vim/lsp/rpc.lua:733	"rpc"	"texlab"	"stderr"	'Error: unexpected message during shutdown: Request(Request { id: RequestId(I32(5)), method: "shutdown", params: Null })\n'
```

I already tried to find out what causes the error but was unable to.

I'm using `tectonic` and when I run `!tectonic -X build` as a command it compiles just fine.
I'm on fedora 37 using nvim 0.8.1 and texlab 5.0.0 (but if I'm not mistaken that error also occured on an earlier version)

I can't recall having changed my config since the last time it worked.
My config is the following:
```lua
local texlab_settings = {
    texlab = {
        build = {
            executable = "tectonic",
            args = {
                "-X",
                "build",
                --"%f",
                --"--synctex",
                "--keep-logs",
                "--keep-intermediates"
            },
            --onSave = true,
        },
        --chktex = {
            --onOpenAndSave = true,
        --},
        --auxDirectory = "./build/out"
    }
}

```

I have also turned on and off the currently commented options but it worked with nothing I tried.

The request id varies but as far as I understand that's normal because that's how the protocol works.

Has anyone experienced something similar? I will try and provide as much additional information as possible if needed.

**Comment by pfoerster** [comment]
> First off: Thanks for the great project. It's really useful for working with latex.

Thanks for the kind words :)

> The log shows the following:

Do you have a full log file including the messages sent before the error? Another useful info would be a server log file (you can use ```texlab -vvvv --log-file /tmp/texlab.log```). Also a backtrace would be nice (you can set the env variable `RUST_BACKTRACE=1`).

> [ERROR][2023-01-01 17:01:40] .../vim/lsp/rpc.lua:733	"rpc"	"texlab"	"stderr"	"thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: \"SendError(..)\"', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.6.0/src/stdio.rs:29:37\nstack backtrace:\nError: unexpected message during shutdown: Request(Request { id: RequestId(I32(8)), method: \"shutdown\", params: Null })\n"

This looks a bit odd considering that the server should not be shutting down during the build. The real error might be some message before this event. Maybe the server is panicking somewhere during the build.

**Comment by sbatial** [comment]
> Also a backtrace would be nice (you can set the env variable `RUST_BACKTRACE=1`

Where would I find the backtrace then? Because I did that already and just got the message as shown above.
Or does verbose logging need to be enabled for that?

**Comment by pfoerster** [comment]
@sbatial

My bad, it looks like it was already enabled. Without the `RUST_BACKTRACE=1`, the error message would not include "stack backtrace" part. The debug builds usually have longer backtraces because of the missing optimizer/inlining but in case the added lines would not help much.

I think the real error lies a few messages before this panic.

**Comment by sbatial** [comment]
Alright.
Verbose logging did the job.
I was missing an openssl package (openssl1.1).

Thanks for helping mate. 🙏

P.S.: There were no other messages before the error in the LspLog. No matter if I completely restarted nvim or just the server.
