### ISSUE TITLE
Diagnostics with chktex not showing exclusively on Windows since 5.0 release

### ISSUE THREAD

**Issue by krassowski** [latex-lsp/texlab#835]
Thank you for the recent 5.0 release :tada:

Downstream in jupyterlab-lsp we have a CI job which runs integration tests with chktex diagnostics. It works fine with 4.3.2 on Ubuntu/Mac/Windows and with 5.0.0 on Ubuntu/Mac but fails on Windows (related to https://github.com/jupyter-lsp/jupyterlab-lsp/issues/894).

I looked at the changelog but did not see anything Windows-specific. Would you have any suggestions what to look at to fix/debug this?

**Comment by pfoerster** [comment]
> It works fine with 4.3.2 on Ubuntu/Mac/Windows and with 5.0.0 on Ubuntu/Mac but fails on Windows (related to https://github.com/jupyter-lsp/jupyterlab-lsp/issues/894).

Does it always fail or only sometimes? When I tried debugging, I encountered a crash once in the parsing logic but I did not find out which line caused the error. Adding a log statement did not help to find the cause as it never crashed again. I could add a safe guard there to prevent this crash in the future but I am not sure if it is causing the issue.

> I looked at the changelog but did not see anything Windows-specific.

The only notable thing that has changed is the way we pass the file to `chktex`. `v4.3.2` uses a temp file, `v5.0.0` uses `stdin`.

> Would you have any suggestions what to look at to fix/debug this?

The `stderr` log of the server might be helpful to find out if a panic causes the issue.

**Comment by pfoerster** [comment]
@krassowski Is there an update on this issue?

> Would you have any suggestions what to look at to fix/debug this?

When are you updating the configuration during the test? Before or after opening the example file? If you are setting the configuration after opening the file, then the server won't run ChkTeX as the default config does not enable ChkTeX.

**Comment by krassowski** [comment]
Thanks for checking! Yes it is now working all right with version 5.4.0 (https://github.com/jupyter-lsp/jupyterlab-lsp/issues/894#issuecomment-1466985099). Looking at logs it was also working with 5.2.0.
