### ISSUE TITLE
Completion item details

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#84]
(Sorry for the vague title, couldn't think of a better one.)

Currently, texlab provides the formatted reference of labels in completion as a `Documentation`. Since these are rather short, I personally would prefer them as `Details` (since vim-lsp can show them in-line in the completion menu), at least additionally. (For floats such as `figure` environments, the caption text is indeed better put into a `Documentation`.)

Also, how is the formatted reference for bibtex items done in VS Code? I don't see a `Documentation` field in the log. (Having the output of `Hover` in there would be useful.) For reference, vimtex completion results for bibtex items include `Details` in the form of a simple string
`Authors (Year) , "Title"` (where authors are either `Author`, `Author1 & Author2`, or `Author1 et al.`). I find that this is sufficient (and helpful) to more quickly find the reference I want from a long list of similar keys.

Finally, while I'm at it, there's a small issue with the filter text of bib items. If you have something like 
```bibtex
@book{Adams:2003a,
    author = {Adams, Robert A. and Fournier, John J. F.},
    edition = {2},
    location = {Amsterdam},
    publisher = {Academic Press},
    title = {Sobolev {S}paces},
    year = {2003},
}
```
the title will show up as `Sobolev S paces`.

**Comment by pfoerster** [comment]
> Finally, while I'm at it, there's a small issue with the filter text of bib items. If you have something like

This one should be easy to fix. I have already identified the problem.

> Also, how is the formatted reference for bibtex items done in VS Code? I don't see a Documentation field in the log.

TexLab uses the `completionItem/resolve` request because it is fairly expensive to render a citation.

> Currently, texlab provides the formatted reference of labels in completion as a Documentation. Since these are rather short, I personally would prefer them as Details (since vim-lsp can show them in-line in the completion menu), at least additionally. (For floats such as figure environments, the caption text is indeed better put into a Documentation.)

This sounds like a good idea. For VS Code, it should be better too because you don't have to press the button to view the documentation.

**Comment by clason** [comment]
> TexLab uses the completionItem/resolve request because it is fairly expensive to render a citation.

Ah, right, that makes sense. Luckily, `completion/resolve` is on the menu for vim-lsp :)

Instead of rendering a full citation, would just grabbing the fields directly (which have to exist for all entries, I believe) and simply concatenating them be reasonable?

**Comment by pfoerster** [comment]
> Currently, texlab provides the formatted reference of labels in completion as a Documentation. Since these are rather short, I personally would prefer them as Details (since vim-lsp can show them in-line in the completion menu), at least additionally. (For floats such as figure environments, the caption text is indeed better put into a Documentation.)

Actuall,y I am thinking that it would be better to put everything inside the `detail` field.
Putting everything inside `detail` except for floating environments is inconsistent so I would prefer having everything at one place.

> Finally, while I'm at it, there's a small issue with the filter text of bib items. 

This one should be fixed with 3f34e8bea1eb00b9babbb36842222f347f51e5a7.

> which have to exist for all entries, I believe, so no big case distinction needed)

While this might be true for BibTeX, BibLaTeX does allow the omission of the `author` field (e. g. when using the `online` type).

**Comment by clason** [comment]
> Actually I am thinking that it would be better to put everything inside the `detail` field.
> Putting everything inside `detail` except for floating environments is inconsistent so I would prefer having everything at one place.

Sorry, that wasn't clear enough -- of course things should be consistent! My suggestion was that rather than have 
* `documentation`/`detail`: "Figure 1. <caption>"
to have instead
* `detail`: "Figure 1" 
`documentation`: "<caption>"
The rationale is that captions can get rather long ("This table shows the results of experiments. Column one lists... column 17 lists..."), and so it keeps the detail length more similar. 

(Of course, that is assuming that the caption is part of the documentation; I might be remembering this wrong, in which case the issue is moot, of course.)

> This one should be fixed with [3f34e8b](https://github.com/latex-lsp/texlab/commit/3f34e8bea1eb00b9babbb36842222f347f51e5a7).

Thanks!

> While this might be true for BibTeX, BibLaTeX does allow the omission of the `author` field (e. g. when using the `online` type).

Right, I keep forgetting BibLaTeX (which I'm even using myself...) Never mind then!

**Comment by clason** [comment]
I'd be happy to take a stab at moving the `label` documentation to details, but would appreciate a hint on how to go about it. (I had hoped that it'd be clear from comparing the respective implementations for commands and labels, but that is unfortunately not the case.)

**Comment by pfoerster** [comment]
> Currently, texlab provides the formatted reference of labels in completion as a Documentation. Since these are rather short, I personally would prefer them as Details (since vim-lsp can show them in-line in the completion menu), at least additionally. (For floats such as figure environments, the caption text is indeed better put into a Documentation.)

This should be fixed with 40900548c09206748757aff33a5f369fa153c4e6.
Everything is inside the detail field except the caption (if I understand you correctly).

**Comment by clason** [comment]
I _just now_ figured it out myself ;) (Your way is better, of course.)

**Comment by clason** [comment]
> Everything is inside the detail field except the caption (if I understand you correctly).

Yes, exactly -- that's perfect, thank you!
