### ISSUE TITLE
line number for undefined reference warnings

### ISSUE THREAD

**Issue by martinra** [latex-lsp/texlab#840]
Warnings at the moment are parsed without matching lines numbers. Undefined references are warnings and come with a line number. Could this be added?

I have played with a suitable, but specialized regex at https://github.com/martinra/texlab/tree/undef_ref . The \.[\r\n] that I put at its end might not be desired. My impression is that all warnings that come with line numbers end with "on input line". If that is correct, then I think one could merge this specialized regex with the current one.

**Comment by pfoerster** [comment]
@martinra Thanks for the suggestion! I have updated the warning regex to optionally extract the line number when available (d7386d0fb2b3063afcdc30e8246f924afa3fdb90).

**Comment by martinra** [comment]
Thank you, @pfoerster . If I may continue the issue, on the branch referenced above, that I have pushed to again, I noticed and fixed a problem with preparing the log, that impacts this very issue. At the moment only two lines of maximal size are concatenated.

As an example, this impacts a warning by the todo package on margins (warning is 4 lines long).

**Comment by pfoerster** [comment]
@martinra

> At the moment only two lines of maximal size are concatenated.

Thanks for catching this one! Do you mind sending a PR?

**Comment by pfoerster** [comment]
Released with `v5.2.0`
