### ISSUE TITLE
incorrect boundaries on label rename?

### ISSUE THREAD

**Issue by martinra** [latex-lsp/texlab#841]
I noticed that in src/features/rename/label.rs in the ReferenceRange the second name seems to be incorrect.
```
if let Some(name2) = label
  // FIXME: shouldn't this be to()?
  .from()
  .and_then(|name| name.key())
  .filter(|name| name.to_string() == name_text)
```

On a more stylistic note, I'd suggest that name1 and name2 are better called name_from and name_to, which fits the naming convention and makes the code a tiny bit more readable, I find.

I'm not sending a pull request, as the contributions.md asks not to do so. But I'd like to point out that I'm totally happy to make some, if that does help and you wish so.

**Comment by pfoerster** [comment]
Released with `v5.2.0`
