### ISSUE TITLE
No diagnostics shown if you \input{preamble} or use pre-compiled headers.

### ISSUE THREAD

**Issue by gi1242** [latex-lsp/texlab#845]
If you `\input` the preamble, or use a pre-compiled headers, then all diagnostics go away.

Here's a minimal working example:

    \documentclass{minimal}
    \begin{document}
    This is an \undefined command
    \end{document}

Now all diagnostics work. However if I create a file `preamble.tex` with

    \documentclass{minimal}

and then create a tex file with:

    \input{preamble}
    \begin{document}
    This is an \undefined command
    \end{document}

  Then no diagnostics are shown at all.

  The same happens if I use a file with a pre-compiled header:

    %& preamble
    \begin{document}
    This is an \undefined command
    \end{document}

Now you have to compile the preamble with:

    pdflatex -ini -jobname=preamble "&pdflatex preamble.tex \\dump"

and then compile the document as usual. All diagnostics  are  missing. As soon as I add a `\documentclass` line to the main document, the diagnostics come back. Is there any way around it?

Thanks in advance.

**Comment by pfoerster** [comment]
@gi1242 
Thanks for the report! This should be fixed by bd38d6f.

**Comment by gi1242** [comment]
THANK YOU SO MUCH!!!

As a workaround (until the next release) I realize I can trick texlab by using

    \iftrue\else\documentclass{minimal}\fi

(It doesn't work with `\iffalse`.)

**Comment by pfoerster** [comment]
Released with `v5.2.0`
