### ISSUE TITLE
Forward search with special characters in file names

### ISSUE THREAD

**Issue by swsnr** [latex-lsp/texlab#848]
Hello,

I'm trying to set up forward search with texlab, neovim, and zathura, and hit an error I don't understand entirely:

When trying to run a forward search for a document whose name contains whitespaces or special characters (e.g. umlauts) I get a "Search error" message in neovim, and the LSP log file shows the following error (I've slightly redacted the message to remove some sensitive names):

```
[ERROR][2023-02-04 14:36:53] .../vim/lsp/rpc.lua:733    "rpc"   "texlab"        "stderr"        "ERROR - Forward search failed: PDF document 'REDACTED/K%c3%bcndigung%20Foo.pdf' not found\n"
```

To me this looks as if texlab passes an URI-encoded name to zathura.  I'm not sure where this comes from; is this an issue in texlab, or a problem in my neovim configuration?

This is my texlab configuration in neovim, using lspconfig:

```lua
        require("lspconfig")[lsp].setup({
          capabilities = capabilities,
          on_attach = require("swsnr.lsp").lsp_attach,
          flags = {
            debounce_text_changes = 150,
          },
          settings = {
            texlab = {
              forwardSearch = {
                executable = "zathura",
                args = { "--synctex-forward", "%l:1:%f", "%p" },
              },
              build = {
                -- The rest of latexmk arguments get set in my latexmkrc
                args = { "%f" },
                executable = "latexmk",
                -- forwardSearchAfter = true,
                onSave = true,
              },
              chktex = {
                onOpenAndSave = true,
              },
            },
          },
        })
```

**Comment by pfoerster** [comment]
@swsnr Thanks for the report!

> To me this looks as if texlab passes an URI-encoded name to zathura. I'm not sure where this comes from; is this an issue in texlab

This is an issue in `texlab` which should be fixed with 178cba7eeb51a03175e101bffbb25f7090705311.
