### ISSUE TITLE
Very slow codeactions (going to next diagnostic msg with LspSaga)

### ISSUE THREAD

**Issue by ShinyZero0** [latex-lsp/texlab#850]
I installed a TexLab to NeoVim with Mason and i use LspSaga which provides commands to jump to next/previous diagnostics problem. When i use one of these, it freezes a couple of seconds showing error "method textDocument/codeAction is not supported by any of the servers registered for the current buffer" and only then it jumps and shows the problem. It shows problem on current line immediately, and it jumps to problems immediately with OmniSharp LSP and PyLSP

**Comment by pfoerster** [comment]
@ShinyZero0 This looks like an error within the `LspSaga` plugin. As the error message says, `texlab` does not provide code actions so it does not advertise the capability during initialization. If a client still queries the code actions, `texlab` returns a "method not found" error, which results in the error message. So the plugin should not try to query the code actions in this case.

**Comment by pfoerster** [comment]
@ShinyZero0 With the latest release, `texlab` returns an empty array when prompted for code actions so this issue should not happen anymore.
