### ISSUE TITLE
Is there a config to filter down the emitted symbols?

### ISSUE THREAD

**Issue by codeshocks** [latex-lsp/texlab#851]
Whenever I switch to the symbol picker in order to move around my document, I have a lot of "Enumerate" and "Item" entries, together with the section and subsections in the documents. I would like to filter the "Enumerate" and "Item" entries out, but didn't find any way to do it in the config file.

I found `texlab.diagnostics.allowedPatterns` and `ignoredPatters` which applies a similar behaviour to the diagnostics. 

Something like `texlab.symbols.allowedPatterns` and `textlab.symbols.ignoredPatterns` could be used so that `textlab.symbols.ignoredPatters = ["Item", "Enumerate"]` would have the effect illustrated above.

**Comment by pfoerster** [comment]
@codeshocks Thanks for the suggestion! The next version of `texlab` will include `texlab.symbols.allowedPatterns` and `textlab.symbols.ignoredPatterns` options to filter the document symbols (see f9f6a38bb7c511215ea525f4bb5cd7958fb80817).
