### ISSUE TITLE
Error parsing  nested `\iffalse` 

### ISSUE THREAD

**Issue by gi1242** [latex-lsp/texlab#853]
Consider the following (valid) LaTeX:

    \documentclass{minimal}
    \begin{document}
    This is an asdf undefined command
    \iffalse
      \iffalse\fi
      \end{enumerate} 
    \fi
    \end{document}

LaTex complies it cleanly. But `texlab` reports a mismatched environment at `\begin{document}`.

If I remove the `\iffalse\fi` line, then texlab reports no error. So presumably something about a nested `\ifflase` confuses it...

**Comment by pfoerster** [comment]
Thanks for the report, this should be fixed now with 1377241.
