### ISSUE TITLE
Duplicate information in inlay hints, e.g. label hint repeats entire figure caption

### ISSUE THREAD

**Issue by meliache** [latex-lsp/texlab#858]
I use TeXLab in Emacs via Eglot, one of the two major LSP clients in Emacs and which has been merged into the Emacs development branch. Recently Eglot added optional support for inlay hints and I was glad to see that TeXLab supports them. As far as I understand this LSP feature is supposed to enhance readability.  I find it very useful that they add the final section/equation/figure numbers next to the labels.

But e.g. for figures, I found that the hints for figure labels print the entire figure caption text, see the screenshot below (the inlay hint is the grey text, added by the LSP client, it's not part of the source):
![image](https://user-images.githubusercontent.com/5121824/222107451-0f087d6b-1ca1-4a04-afc5-d6f571873c83.png)
Since the label is usually put near the caption in the LaTeX source code, this is duplicate information, in that I see the caption twice. I wouldn't mind if this were visible when hovering the mouse/point over the label, but it's not necessary to have this as an always visible hint. This is not the only case of duplicate information in inlay hints, e.g. section labels print the section name and I think this is not necessary because we can see the section name just above anyway:
![image](https://user-images.githubusercontent.com/5121824/222109476-9a2890e5-4e1c-4e6d-9e7e-96f5410705c0.png)
This is something I would find useful only in section references, to see the section name of the references section. Luckily section names are usually short so I don't mind this too much.

I'm not sure if this is an issue with the Eglot implementation of inlay hints, which is new on the development branch and not part of the release yet, or an issue for TeXLab. Maybe this information isn't supposed to be shown inside the text and only on hover?

One good solution would be to add configuration options for inlay hints in the TeXLab server configuration. In the meantime, I turned this feature of in Emacs for LaTeX.

I compile TeXLab via the Archlinux AUR, in the screenshots above the latest revision 2bc4d636 was used.

**Comment by pfoerster** [comment]
@meliache Thanks for the very detailed report.

> Since the label is usually put near the caption in the LaTeX source code, this is duplicate information, in that I see the caption twice.

Yeah, I agree with you that adding the section right next to the label definition is redundant. I think we can remove that and only show the number instead (if any).

> I'm not sure if this is an issue with the Eglot implementation of inlay hints, which is new on the development branch and not part of the release yet, or an issue for TeXLab. Maybe this information isn't supposed to be shown inside the text and only on hover?

No, inlay hints and hover are separate requests so this is not an issue with Emacs/Eglot.

> One good solution would be to add configuration options for inlay hints in the TeXLab server configuration.

I think it is best to let the client handle the general configuration or feature toggles of a specific request.

**Comment by pfoerster** [comment]
@meliache With dd85dce, `texlab` will not show the caption or section name in the inlay hint. Your example will now produce `Section 4.9` instead of `Section 4.9 (Analysis software)`.

**Comment by meliache** [comment]
Thanks for addressing this, awesome!
