### ISSUE TITLE
[Feature Request] Add DocTeX support (`.dtx`)

### ISSUE THREAD

**Issue by nvlang** [latex-lsp/texlab#859]
Suppose I have the following `test.tex` file:

```latex
% test.tex
\documentclass{l3doc}
\theCodelineNo
```

As I typed e.g. `\theCode...`, I got the auto-complete suggestion for `\theCodelineNo`, with the description `l3doc.cls`.

If I do the same inside a `test.dtx` file, that suggestion does not show up.

Support for DocTeX files (i.e., files with the `.dtx` extension) would be much appreciated. Thank you for reading this!

**Comment by clason** [comment]
Just tell your client to use texlab for `dtx` files; this is not something the server decides!

**Comment by nvlang** [comment]
> Just tell your client to use texlab for `dtx` files; this is not something the server decides!

Really sorry, you're 100% right of course, I should've posted this to the [texlab-vscode](https://github.com/latex-lsp/texlab-vscode) repository instead.
