### ISSUE TITLE
IEEEeqnarray is not recognized as math environment

### ISSUE THREAD

**Issue by NineBeans2** [latex-lsp/texlab#860]
For multiline equations, I usually use the IEEEeqnarray environment from the IEEEtrantools package, for example as follows
```
\usepackage{IEEEtrantools}

\begin{IEEEeqnarray}
   a &=& b . \label{eq:test}
\end{IEEEeqnarray}
```
The problem is when using \eqref{}, the label 'eq:test' in the example will not appear in the auto-completion list, while it can be called by \ref{}. So it seems that texlab is not able to treat IEEEeqnarray correctly as a math environment. 

Is there a way to tell texlab that an environment should be recognized as a math environment? Or more generally, can we assign an environment type to a given environment manually (didn't expect this can be done automatically as there could always be some self-defined environments)?

**Comment by pfoerster** [comment]
@NineBeans2 With the next release, the list of "special" environments will be configurable (`experimental` for now). See https://github.com/latex-lsp/texlab/wiki/Configuration#texlabexperimentalmathenvironments and 8f1ae1d.
