### ISSUE TITLE
Wrong suggestions/errors when using non-standard/Unicode (`[^a-zA-Z]`) macro names

### ISSUE THREAD

**Issue by Andrew15-5** [latex-lsp/texlab#864]
This is a copy of the issue https://github.com/fannheyward/coc-texlab/issues/250 because the issue is not with `coc-texlab` extension but with the `texlab` server itself. (I guess I will be updating both comments.)

---

Issue https://github.com/latex-lsp/texlab/issues/857 (https://github.com/fannheyward/coc-texlab/issues/249) has been resolved and server now provides suggestions with any macro names, hurray! But now there are some bugs with coc-texlab (I'm pretty sure). Below I paste Neovim config, LaTeX file/document and some tests. Only the 3rd test is passed because macro/command name consists of non-special characters (`[a-z]`). But of course ideally all 7 must be passed (support of 99% any name).

There are some notes:

- tests were conducted using `lualatex` command (it tolerates/supports a lot more macro names than `pdflatex`)
- if more than 1 macro has the same digit (`[0-9]`) as a 1st character, then the compiler error will occur if one of them is used and won't occur if none of them is used
- adding `{}` to the 1st argument of `\newcommand` macro (the correct form) will trigger an extension error for some Unicode macro names (I don't know what are the rules for triggering the error)
- I see that default Neovim syntax highlighting also doesn't support some macro names (probably should open an issue there too)
- **[New]** tests include prior activation of suggestions (automatically or by pressing `<C-Space>`), without it tests that require pasting from clipboard wouldn't work (see https://github.com/neoclide/coc.nvim/issues/4568)
- **[New]** if `suggest.asciiMatch` (`:CocCofig`) isn't set to `false` then tests for which you have to paste non-ASCII text from clipboard wouldn't work

<details><summary>init.vim</summary>

```vim
call plug#begin($HOME . '/.config/nvim/autoload/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'joshdick/onedark.vim'
  Plug 'tpope/vim-commentary'
call plug#end()

colorscheme onedark

" Comment lines
noremap <silent> <C-/> :Commentary<CR>
inoremap <silent> <C-/> <Esc>:Commentary<CR>

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" coc-texlab
let g:tex_flavor = 'latex'

" Select auto completion option
inoremap <silent><expr> <C-j>
  \ coc#pum#visible() ? coc#pum#next(1) :
  \ CheckBackspace() ? "\<Tab>" :
  \ coc#refresh()
inoremap <expr><C-k> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
```

</details>

<details><summary>bug.tex</summary>

```latex
\documentclass{article}
% \newcommand{\ö}{} % No error
% \newcommand{\öö}{} % Error: Unexpected "}" (texlab 1)
% \newcommand{\ööabc}{} % Error: Unexpected "}" (texlab 1)
\newcommand\ööabc{}
\def\öabc{}
\def\123{123}
\def\abc{}
\begin{document}
\end{document}
```

</details>

<details><summary>Tests</summary>

Step 0:
`\`, `<C-Space>`
![image](https://user-images.githubusercontent.com/37143421/224181824-7e05bb39-51c6-4d74-99dd-782f6085c8f4.png)

<table>
<thead>
<tr>
<th>Test #</th><th>Step 1</th><th>Step 2</th>
</tr>
</thead>
<tbody>
<tr>
<td>1🔴</td>
<td>

`1`
![image](https://user-images.githubusercontent.com/37143421/224181110-eef0f733-c087-44d4-a57d-fe2fae853062.png)
(macro `\1` is undefined, shown otherwise)
</td>
<td>

`<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224181231-49af3a1d-1daa-46df-a82d-ad3f744ed8ec.png)
</td>
</tr>
<tr>
<td>2🔴</td>
<td>

`123`, `<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224181315-d04c67e7-a2a3-4fa9-a437-328b7a44171a.png)
(macro `\123` is defined, shown otherwise)
</td>
<td></td>
</tr>
<tr>
<td>3🟢</td>
<td>

`abc`, `<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224181450-8d51e698-8711-49b6-9481-7e9d637af66d.png)
(macro `\abc` is defined, the same is shown)
</td>
<td></td>
</tr>
<tr>
<td>4🔴</td>
<td>

`ö`, `<C-Space>`
![image](https://user-images.githubusercontent.com/37143421/224181578-ca44ec82-7a5e-4d73-b8c6-e0c801a9a81b.png)
(macro `\ö` is undefined, shown otherwise)
</td>
<td>

`<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224181609-218d22e9-150f-4377-bdaf-81156b3a761f.png)
</td>
</tr>
<tr>
<td>5🔴</td>
<td>

`öabc`, `<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224184414-0db0907b-59ef-4edc-8798-2a5d4d905007.png)
(macro `\öabc` is defined, shown otherwise)
</td>
<td></td>
</tr>
<tr>
<td>6🔴</td>
<td>

`öö`
![image](https://user-images.githubusercontent.com/37143421/224184732-badb8a47-feeb-4b30-ba4d-8e857da6b5ae.png)
(macro `\ööabc` is defined, but no suggestions are shown unless `<C-Space>` is pressed again)
</td>
<td>

`abc`, `<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224184901-ab23ec91-9cd1-47b4-8fbe-af9adc799237.png)
(macro `\ööabc` is defined, shown otherwise)
</td>
</tr>
<tr>
<td>7🔴</td>
<td>

`öö`,  `<C-Space>`
![image](https://user-images.githubusercontent.com/37143421/224185116-a35d3b4b-4636-42b3-ba1c-892def7be885.png)
\*Uncommented 1 line with the extension error*
(macros `\ööabc` and `\öö` are defined, but only **word** and **not a macro** `ööabc` is suggested)
</td>
<td></td>
</tr>
</tbody>
</table>

</details>

<details><summary>\newcommand{}</summary>

Meaningless errors are shown which say that the `}` character is inserted in the unexpected/wrong place, but the syntax is correct. Maybe it's only shown when the macro's name have anything appended after the Unicode character (a hunch from just looking at the places where the errors occur).

![image](https://user-images.githubusercontent.com/37143421/224190462-2e6af06c-2ba3-4408-892b-af9218b9b29d.png)
![image](https://user-images.githubusercontent.com/37143421/224190515-5d36cf47-00c1-40da-8a97-64281a5124a4.png)

Output (from `lualatex bug.tex`):
![image](https://user-images.githubusercontent.com/37143421/224190741-8098910b-3ac1-4654-adcd-6f5ad55f59a6.png)

Source code:

```latex
\documentclass{article}
\newcommand{\ö}{ö} % No error
\newcommand{\öö}{öö} % Error: Unexpected "}" (texlab 1)
\newcommand{\ööabc}{ööabc} % Error: Unexpected "}" (texlab 1)
\renewcommand\ööabc{ööabc} % No error
\def\öabc{öabc}
\def\123{123}
\def\abc{abc}
\def\a0{a0}
\def\0a{0a}
% \def\1a{1a} % OK if no macro starting with \1 is used
\begin{document}
\ö, \öö, \ööabc, \öabc, \123, \abc, \a0, \0a
\end{document}
```

</details>

---

Updated test results (checked means no issues):

- [x] test 1 (fixed)
- [x] test 2 (fixed)
- [x] test 3 (was working)
- [x] test 4 (fixed)
- [x] test 5 (fixed)
- [x] test 6 (fixed)
- [x] test 7 (fixed)
- [x] `\newcommand{...}` (fixed)
- [x] ["ultimate" test](https://github.com/latex-lsp/texlab/issues/864#issuecomment-1464560856) (fixed)

**Comment by Andrew15-5** [comment]
Additional "ultimate" test:

<details><summary>ultimate_test.tex</summary>

```latex
\documentclass{article}

\usepackage{luacode}
\begin{luacode*}
luaotfload.add_fallback("FallbackFonts", {
  "Noto Color Emoji:mode=harf",
  "Noto Serif CJK JP:"
})
\end{luacode*}
\usepackage{fontspec}
\setmainfont{Liberation Serif}[RawFeature={fallback=FallbackFonts}]

% \newcommand{\123}{123} % Compiler error
\def\123{123}
\newcommand{\abc}{abc}
\newcommand{\ö}{ö}
\newcommand{\öö}{öö}
% \newcommand{\ööabc123}{ööabc} % Compiler error
\def\ööabc123{ööabc123}
\newcommand{\русский}{русский}
\newcommand{\にほんご}{にほんご}
\newcommand{\日本語}{日本語}
\newcommand{\💚}{💚}
\newcommand{\🔥}{🔥}
% \newcommand{\👨‍💻}{👨‍💻} % Compiler error
\def\👨‍💻{👨‍💻} % Technician
% Can't start with the same atomic Unicode character (another hunch)
% \def\👨‍👩‍👦‍👦{👨‍👩‍👦‍👦}
\begin{document}
\123, \abc, \ö, \öö, \ööabc123, \русский, \にほんご, \日本語, \💚, \🔥,
\👨‍💻.
\end{document}
```

</details>

<details><summary>ultimate_test.tex (Neovim screenshot)</summary>

![image](https://user-images.githubusercontent.com/37143421/224438273-1752558c-3e70-4cc2-b9b9-de514ad226d2.png)

</details>

<details><summary>Output</summary>

(Maybe PDF 1.5 can't combine complex Unicode or something else is off for the `👨‍💻`.)

![image](https://user-images.githubusercontent.com/37143421/224439204-2e9dc41e-84f7-4ea3-8ab9-7270949ccb92.png)![image](https://user-images.githubusercontent.com/37143421/224439103-a4da1243-332f-4300-b867-bc3a24f682dc.png)

(emojis don't look very nice with inverted colors: ![image](https://user-images.githubusercontent.com/37143421/224439505-78d1b212-f3de-4e4d-a040-57d76c74b202.png))

</details>

If I put `\` and the first character of any macro and then press `<C-Space>` then it will show a correct suggestion of the existing macro. But for the `👨‍💻` character, it didn't suggest anything (maybe Neovim is to blame). So for me (until Unicode is fully supported by Neovim) this is another pass.

**Comment by Andrew15-5** [comment]
@pfoerster, I want to discuss something. It's related to the remaining tasks 4 and 6.

Some characters for testing are inserted from the clipboard because not always you can type anything out directly from your keyboard (well maybe with the composer key, but this is not the point).

If I insert/type a character from the keyboard directly, it will update the suggestion entries. But if I insert a character from the clipboard via `Ctrl+Shift+V` (or by using any custom keymapping in kitty) then the suggestions will disappear. The previous sentence is true at least for `ö`, Russian and Hiragana, but not true for digits and Latin/English letters.

So what I want to ask is if this is the fix for texlab or something else. Since for some characters suggestions (autocompletion) are automatically updated after pasting from clipboard and for the others — not, then _I think_ it is something to do with the server (or of course with the `coc-texlab` extension).

I've tested this in `kitty` as well as in the `gnome-terminal` — same behavior (so it's not terminal's fault).

<details><summary>Example</summary>

To help you understand, here is a quick example:

Type `\` and then `<C-Space>`
![image](https://user-images.githubusercontent.com/37143421/224444947-b1501b7c-3e5a-4076-a0ac-49783c30bb37.png)

Now just paste every character from the clipboard (only 2 out of 5 keep showing suggestions + the suggestions have changed):
![image](https://user-images.githubusercontent.com/37143421/224445025-872f8c34-55bc-4bd8-bf34-ffc4aa17b12b.png)
![image](https://user-images.githubusercontent.com/37143421/224445101-8ebdbaee-3c15-4730-8320-55c309f39f11.png)
![image](https://user-images.githubusercontent.com/37143421/224445183-96d1f7de-fa73-4e5b-8ba8-0c39f1989e86.png)
![image](https://user-images.githubusercontent.com/37143421/224445248-0772d29c-7957-49b0-86b5-93dc02984724.png)
![image](https://user-images.githubusercontent.com/37143421/224445284-11e38b50-93ac-45db-bc1f-ed468a75dfb9.png)

```latex
\documentclass{article}
\def\abc{}
\def\123{}
\def\öö{}
\def\рус{}
\def\あいうえお{}
\begin{document}
\a
\1
\ö
\р
\あ
\end{document}
```

</details>

**Comment by pfoerster** [comment]
@Andrew15-5 Thank you for the very detailed test cases.

> Since for some characters suggestions (autocompletion) are automatically updated after pasting from clipboard and for the others 

I think the problem is that the client does not actually trigger the completion request after pasting the special characters. If you trigger the completion manually, then the items show up (see the test case in ce4c02411cdd44de4f4ad6012f83140eed2472df). 

Note that it is the client's reponsibility to determine whether to trigger the completion (the server can only specify additional characters; `texlab` uses `\\` for example).

```
LSP Spec:

Most tools trigger a completion request automatically without explicitly
requesting it using a keyboard shortcut (e.g. Ctrl+Space). Typically they
do so when the user starts to type an identifier. For example if the user
types `c` in a JavaScript file code complete will automatically pop up
present `console` besides others as a completion item. Characters that
make up identifiers don't need to be listed here. 
```

So the root cause for tests 4 and 6 should be that `ö`, `р` and `あ` are not considered "identifier characters" by the client.

**Comment by Andrew15-5** [comment]
The client is the coc-texlab extension, right?

**Comment by pfoerster** [comment]
@Andrew15-5

> The client is the coc-texlab extension, right?

Yes, I also repeated the tests with VSCode which yields the same result.

**Comment by Andrew15-5** [comment]
Ok, I opened a new issue: https://github.com/fannheyward/coc-texlab/issues/251.

**Comment by Andrew15-5** [comment]
Here is what I want to do. If [the `coc-texlab` issue](https://github.com/fannheyward/coc-texlab/issues/251) will/can be resolved in the near future, then I will check the tests again and probably close this issue. But if the issue will take a lot of time, then I will close this issue and then make an update after `coc-texlab` will be updated.

The reason is that these two issues are connected through 4th and 6th tests because in them after pasting Unicode character from clipboard the dropdown menu disappear instead of providing suggestions of the existing macros. Right now, these 2 tests can be considered as "pass with a bronze medal" because in them, I have to trigger autocompletion action in order to see correct suggestions. The "ultimate" test doesn't really test this but is also affected by this problem. When `coc-texlab` will be updated and suggestions will be shown automatically after pasting (first character of a macro) from clipboard, then the remaining tests can have their "pass with a gold medal".
