### ISSUE TITLE
Doesn't recognize file as being included

### ISSUE THREAD

**Issue by gustafla** [latex-lsp/texlab#865]
I'm running texlab 5.3.0 in Helix 22.12 and I cannot get it to recognize that a chapter file is `\include`:d from a main .tex file. I'm getting errors like `LaTeX Error: Missing \begin{document}.` in other files than the main file. I tried setting `config.texlab.rootDirectory to "."` but that did not help. Strangely, some few times after cleanup it does work for a while, but not for all files and the behavior is flaky.

My project directory structure is flat, containing main.tex, Ch.10_Intro.tex, Ch.20_Topic1.tex etc. similarly named files.

**Comment by gustafla** [comment]
This issue seems to be caused by build.onSave. I assume that texlab tries to build the `Ch.*` file instead of main.tex, and breaks the project.

**Comment by pfoerster** [comment]
@gustafla It looks like `texlab` has trouble detecting the root directory. Can you try setting `texlab.rootDirectory` to `null` and add an empty `texlabroot` file to the directory containing the TeX files?

> I assume that texlab tries to build the Ch.* file instead of main.tex, and breaks the project.

Yes, this assumption is correct. It seems that `texlab` does not detect the main file correctly and builds the chapter files as a fallback.

**Comment by gustafla** [comment]
Thank you for your reply! I ran `touch texlabroot` and tried to comment out `config.texlab.rootDirectory`, set it to `{}` and set it to `""` but none of these worked. TOML doesn't really have a null value it seems.

For now a reasonable workaround for me is to not use build.onSave.

**Comment by pfoerster** [comment]
@gustafla

> TOML doesn't really have a null value it seems.

Usually, leaving out the value signifies `null`.

You can also try the new workspace command `texlab.showDependencyGraph` in `5.4.0` (see wiki for more info) to help debug the issue.

**Comment by gustafla** [comment]
This issue seems to be resolved. I don't know why and how, but I can't reproduce the problem any more. Thank you for helping!
