### ISSUE TITLE
texlab in crates.io is old 

### ISSUE THREAD

**Issue by ROCKTAKEY** [latex-lsp/texlab#866]
Hi, thanks for your maintenance!!

Texlab-5.4.0 is published a few days ago, but [texlab in crates.io](https://crates.io/crates/texlab) is on v4.3.2.
Is there any problem to update crates.io's one?

Thanks.

**Comment by pfoerster** [comment]
@ROCKTAKEY Starting with `v5.0.0`, the server uses the `salsa-2022` crate, which is not on crates.io (yet). All dependencies of a crate on crates.io need to be published as well so `texlab` cannot be published, too. I think using the crate provides a much better value than publishing on crates.io.

In the long term, I am not sure if it is desirable to keep `texlab` on crates.io updated. The server itself is not really specific to Rust and is very unlikely to be referenced by other crates. Also, publishing on crates.io prevents crate splitting (which can be used to improve compile times).

**Comment by ROCKTAKEY** [comment]
> @ROCKTAKEY Starting with v5.0.0, the server uses the salsa-2022 crate, which is not on crates.io (yet). All dependencies of a crate on crates.io need to be published as well so texlab cannot be published, too. I think using the crate provides a much better value than publishing on crates.io.

I see, thanks.

> In the long term, I am not sure if it is desirable to keep texlab on crates.io updated. The server itself is not really specific to Rust and is very unlikely to be referenced by other crates. Also, publishing on crates.io prevents crate splitting (which can be used to improve compile times).

In my opinion, I think installing from crates.io is useful, but it is not absolutely necessary, as long as the process to build texlab is clear (of course it is clear now bacause of Cargo.toml). If building process would become unclear in the future, registration to package manager might be needed as a sample of building process.

**Comment by cgahr** [comment]
In this case, the Readme should be updated to reflect the fact, that `cargo install texlab` is not the intended way of installing `texlab`.

**Comment by pfoerster** [comment]
@cgahr Thanks, I have updated the README 👍
