### ISSUE TITLE
No support for Fedora Linux

### ISSUE THREAD

**Issue by Gurmukh-Singh-4253** [latex-lsp/texlab#878]
When i tried to install the texlab server for LaTeX on my machine, Mason declined the installation saying "the current platform is not supported."
Please guide on how to install the server via the binary distribution or make the server work for Fedora as well.

{
  machine = "aarch64",
  release = "6.0.7-301.fc37.aarch64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Fri Nov 4 18:13:35 UTC 2022"
}

**Comment by pfoerster** [comment]
@Gurmukh-Singh-4253 This needs to be reported at the `Mason` repository, `texlab` works fine on `aarch64-linux` so you need to install the server yourself.

You can compile the server from source using ```cargo install --git https://github.com/latex-lsp/texlab --tag v5.4.1 --locked``` or download a binary from the [releases](https://github.com/latex-lsp/texlab/releases).
