### ISSUE TITLE
Spurious completion result in environment

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#883]
Since https://github.com/latex-lsp/texlab/commit/0d7b21440d604ed80d801ce34ca7f9e4e18ca598, I get spurious completion results for environments (only). It's reproducible with an empty file and just triggering completion on, say,
```tex
\begin{doc|
```
<img width="221" alt="Screenshot 2023-04-21 at 14 08 43" src="https://user-images.githubusercontent.com/2361214/233631743-ceb5712c-6f10-4e6d-bb04-e9b4aa3c37a9.png">

It looks like the matcher doesn't handle newlines correctly, as seen by the variant
```tex
\begin{doc|
%%%%%%%%%%
```
<img width="311" alt="Screenshot 2023-04-21 at 14 11 06" src="https://user-images.githubusercontent.com/2361214/233632121-ce86662a-4ad0-4144-8704-cc905ed478d5.png">

**Comment by pfoerster** [comment]
@clason Thanks for catching this one! This should be fixed by 4cc0b20a563a367b5cb1215abcfe3abab5e72575.

**Comment by clason** [comment]
Indeed it is, thank you!
