### ISSUE TITLE
Adding flalign to math environments. 

### ISSUE THREAD

**Issue by LuisA92** [latex-lsp/texlab#884]
Hello, 

Is there anyway to add `flalign` and `flalign*` to the list of math environments? 

I mainly use texlab on neovim, and I cannot not figure out how to configure the math environment list. 

Thanks!

**Comment by pfoerster** [comment]
@LuisA92 You can use the [`texlab.experimental.mathEnvironments`](https://github.com/latex-lsp/texlab/wiki/Configuration#texlabexperimentalmathenvironments) setting:

```jsonc
"texlab.experimental.mathEnvironments": ["flalign", "flalign*"]
```

**Comment by LuisA92** [comment]
@pfoerster sorry for the noob question (first time configuring texlab), but where is the config file for texlab located? Do I need to create a new one? 

I was using texlab through nvim lspconfig, but I just downloaded texlab locally using `cargo install texlab`.

**Comment by pfoerster** [comment]
@LuisA92 There is no config file, instead you need to pass the configuration to the server through the client (Neovim). In your case, it might look like this (actual syntax might be wrong as I don't use Neovim):

```lua
lspconfig.texlab.setup {
  settings = {
    texlab = {
      experimental = {
        mathEnvironments = { 'flalign', 'flalign*' },
      },
    },
  },
}

```

See [here](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#texlab) for more information.

**Comment by LuisA92** [comment]
Thank you! This solved my issue.
