### ISSUE TITLE
No (recursive) diagnostic for nested files using `subimport`

### ISSUE THREAD

**Issue by GTM52** [latex-lsp/texlab#885]
Hello, I am currently using texlab in neovim and it works well, but when I use `import` package to nest my files, I cannot get completion for `\ref` command. Here is a minimal example ([download here](https://github.com/latex-lsp/texlab/files/11414025/example.zip)):
```
.
├── main.tex
├── part 1
│   ├── chapter 1
│   │   ├── main.tex
│   │   └── section 1.tex
│   └── main.tex
└── part 2
    ├── chapter 2
    │   ├── main.tex
    │   └── section 2.tex
    └── main.tex
```
I use `import` package to input files in `part 1`, and `input` for `part 2`. 
```latex
% main.tex
\documentclass{book}
\usepackage{import}
\begin{document}
\subincludefrom{part 1}{main}
\include{part 2/main}
\end{document}
% part 1/main.tex
\part{1}
\label{part 1}
\subimport{chapter 1}{main}
% part 1/chapter 1/main.tex
\chapter{1}
\label{chapter 1}
\subimport{./}{section 1}
%\subimport{}{section 1}
% part 1/chapter 1/section 1.tex
\section{1}
\label{section 1}
% part 2/main.tex
\part{2}
\label{part 2}
\input{part 2/chapter 2/main}
% part 2/chapter 2/main.tex
\chapter{2}
\label{chapter 2}
\input{part 2/chapter 2/section 2}
% part 2/chapter 2/section 2.tex
\section{2}
\label{section 2}
```
There are two problems:
1. I cannot get completion for (deeper) labels in `part 1` when I use `\ref`:
![image](https://user-images.githubusercontent.com/102008190/236659667-745a764b-0ca7-4028-827e-9d36a19391dc.png)
![image](https://user-images.githubusercontent.com/102008190/236659883-c088481e-8726-4f9f-b4da-ad51372d1021.png)
2. In `part 1/chapter 1/main.tex`, the command `\subimport{./}{section 1}` gives a completion for `\ref`, 
![image](https://user-images.githubusercontent.com/102008190/236659732-f21c7da5-f550-4d21-bddd-f34202637dbb.png)
while `\subimport{}{section 1}` does not:
![image](https://user-images.githubusercontent.com/102008190/236659757-40cabbe5-6220-4b8c-980a-b36c3b8e541f.png)

Thanks for your help!

**Comment by pfoerster** [comment]
@GTM52 Thanks for the very detailed report! 321fa26 should fix this issue.
