### ISSUE TITLE
Feature: Retrieving environment information

### ISSUE THREAD

**Issue by LeoSchae** [latex-lsp/texlab#892]
I was experimenting with automatically replacing surrounding environments, mainly automatically toggling a star in the surrounding environment and changing between equation and align.
Right now this is kind of possible by searching for begin / end in the open document but it is really hacky.

Doing so automatically seems only possible if one can retrieve the name of the current environment.
The feature I have in mind would return the stack of environments given a specific position.

```
request("workspace/executeCommand", {
  command: "texlab.findEnvironments",
  arguments: {
    textDocument: ...,
    position: ...,
  },
}) -> {
  name: ...,
  range: ...,
}[]
```
Given the output of this function it would be easy to make use of the "texlab.changeEnvironment" feature more effectively. For this purpose, the name of the innermost environment would already be sufficient.

Example:
```
\begin{a}
  \begin{b}
    \begin{c}
      *
    \end{c}
    **
  \end{b}
  ***
  \begin{d}
    ****
  \end{d}
\end{a}
```
Here when giving a position marked by the stars, I would hope for the following outputs:
* *: ["a", "b", "c"]
* **: ["a", "b"]
* ***: ["a"]
* ****: ["a", "d"]

Including the location in the result would also be great. So an array of {name: "...", range: {...}}.

**Comment by pfoerster** [comment]
@LeoSchae Thanks for the suggestion! Can you try out #896, please? It adds the `texlab.findEnvironments` command.

**Comment by LeoSchae** [comment]
@pfoerster Thank you! That was pretty quick. I tested the command on nixos-23.05 in neovim with lspconfig. I attached the modified derivation for the commit as well. The feature seems to work fine and produce the expected output.

<details>
  <summary>Vim config</summary>

```lua
local lsp = require "lspconfig"
lsp.texlab.setup{ filetypes = {"tex", "sty"}, }

local test = function()
  local params = vim.lsp.util.make_position_params()
  local client = lsp.util.get_active_client_by_name(0, "texlab")
  client.request("workspace/executeCommand", {
    command = "texlab.findEnvironments",
    arguments = {params},
  }, function(a, b, c)
    print(vim.inspect(a))
    print(vim.inspect(b)) -- this is the returned list
    print(vim.inspect(c))
  end)
end

map("n", "<leader>fe", test, { noremap = true })
```
</details>

<details>
  <summary>Nix derivation</summary>

```nix
{ lib
, stdenv
, rustPlatform
, fetchFromGitHub
, help2man
, installShellFiles
, nix-update-script
}:

let
  isCross = stdenv.hostPlatform != stdenv.buildPlatform;
in
rustPlatform.buildRustPackage rec {
  pname = "texlab";
  version = "5.6.0-test";

  src = fetchFromGitHub {
    owner = "latex-lsp";
    repo = "texlab";
    rev = "32ea2f36319d0596fd494eebe18514b3f72c426e";
    hash = "sha256-AjBEMpmlx9CrbL2wkSWnd+nThSFn4TSjcOtrA1NFn5o=";
  };

  cargoHash = "sha256-XsRHF/Hg++x5jz2GiP/5OnlU/ozRSwnOA1/oelq/pcw=";

  outputs = [ "out" ] ++ lib.optional (!isCross) "man";

  nativeBuildInputs = [ installShellFiles ]
    ++ lib.optional (!isCross) help2man;

  # When we cross compile we cannot run the output executable to
  # generate the man page
  postInstall = lib.optionalString (!isCross) ''
    # TexLab builds man page separately in CI:
    # https://github.com/latex-lsp/texlab/blob/v5.5.1/.github/workflows/publish.yml#L127-L131
    help2man --no-info "$out/bin/texlab" > texlab.1
    installManPage texlab.1
  '';

  passthru.updateScript = nix-update-script { };

  meta = with lib; {
    description = "An implementation of the Language Server Protocol for LaTeX";
    homepage = "https://github.com/latex-lsp/texlab";
    license = licenses.mit;
    maintainers = with maintainers; [ doronbehar kira-bruneau ];
    platforms = platforms.all;
  };
}
```
</details>

**Comment by LeoSchae** [comment]
In case someone wants keybinds for the features I was interested in.
It has a keybind `Alt-+` to toggle a * on the closest environment.
Also `Alt-6` toggles equation <-> align and the same for *ed versions.

<details>
<summary>Vim config</summary>

```lua
local map = vim.keymap.set
local lsp = require "lspconfig"
lsp.texlab.setup{ filetypes = {"tex", "sty"}, }

local add_star = function()
  local params = vim.lsp.util.make_position_params()
  local client = lsp.util.get_active_client_by_name(0, "texlab")
  client.request("workspace/executeCommand", {
    command = "texlab.findEnvironments",
    arguments = { params },
  }, function(_, envs, _)
    if #(envs) == 0 then
      print("No environment found")
      return
    end
    local name = envs[#envs].name
    if name:sub(#(name)) == "*" then
      name = name:sub(1, #(name) - 1)
    else
      name = name .. "*"
    end
    params.newName = name
    client.request("workspace/executeCommand", {
      command = "texlab.changeEnvironment",
      arguments = { params, },
    }, function() end)
  end)
end

local cycle_envs = function()
  local env_mappings = {
    ["equation"] = "align",
    ["align"] = "equation",
    ["equation*"] = "align*",
    ["align*"] = "equation*",
  }
  local params = vim.lsp.util.make_position_params()
  local client = lsp.util.get_active_client_by_name(0, "texlab")
  client.request("workspace/executeCommand", {
    command = "texlab.findEnvironments",
    arguments = { params },
  }, function(_, envs, _)
    if #(envs) == 0 then
      print("No environment found")
      return
    end
    local name = envs[#envs].name
    if env_mappings[name] == nil then
      print("No mapping for '" .. name .. "'")
      return
    end
    params.newName = env_mappings[name]
    client.request("workspace/executeCommand", {
      command = "texlab.changeEnvironment",
      arguments = { params, },
    }, function() end)
  end)
end


map("n", "<A-+>", add_star, { noremap = true })
map("n", "<A-6>", cycle_envs, { noremap = true })
```
</details>

**Comment by LeoSchae** [comment]
@pfoerster I did manage to find a small bug. The position at which the document is sampled is not the same as the position where a rename is applied.

Problem cases:

[Screencast_20230604_151907.webm](https://github.com/latex-lsp/texlab/assets/16176913/726cb712-4a06-4cce-bb0f-ee97296caaf0)

So there is an issue when hovering the first letter of / after and environment in those cases the innermost environment found does not match the environment that is renamed. Offsetting the sample position for either findEnvironment or changeEnvironment should fix things.

**Comment by pfoerster** [comment]
@LeoSchae Thanks for catching this one! I changed #896, so that it returns both the range of the environment (`fullRange`) and the range of the name (`name.range`). For `changeEnvironment`, we can use `name.range`.

**Comment by LeoSchae** [comment]
@pfoerster That was not quite the issue I meant. The changeEnvironment seems to be right biased, while findEnvironment is left biased.
So in this case
```
\begin{a}
  |\begin{b}
  \end{b}
\end{a}
```
where the cursor is before the `\begin{b}` findEnvironment will include "b" in the list but changeEnvironment will edit "a".
The same happens in reverse if the cursor is behind `\end{b}`.

I was able to get consistent behaviour by reusing the changeEnvironment code:
```rs
pub fn find_environments(document: &Document, position: TextSize) -> Vec<EnvironmentMatch> {
    let DocumentData::Tex(data) = &document.data else { return Vec::new() };

    let mut results = Vec::new();
    let root = latex::SyntaxNode::new_root(data.green.clone());

    let Some(ancestors) = root
    .token_at_offset(position)
    .right_biased().and_then(|token| Some(token.parent_ancestors())) else { return results };


    for environment in ancestors.filter_map(latex::Environment::cast)
    {
        let Some(name) = environment
            .begin()
            .and_then(|begin| begin.name())
            .and_then(|group| group.key())
            .map(|name| Span::from(&name)) else { continue };

        let full_range = latex::small_range(&environment);
        results.push(EnvironmentMatch { name, full_range });
    }

    results.reverse();
    results
}
```

**Comment by pfoerster** [comment]
@LeoSchae Thanks, should be fixed now :)
