### ISSUE TITLE
feature request : pass options to chktex

### ISSUE THREAD

**Issue by UGL1** [latex-lsp/texlab#900]
Hi, it would be great if a fied like
`"chktex options" : "-l chktexrc.local"`
could be added to the settings.

**Comment by pfoerster** [comment]
@UGL1 Thanks for the request! Where is your `chktexrc` file located? Inside the project directory? If yes, then this _should_ already work out of the box. Usually, `chktex` will pick up a `chktexrc` file if it is located in the project folder.

**Comment by UGL1** [comment]
Nevermind, was I was asking for is indded achievable by means of a simple config file.
Thanks for your interest.
