### ISSUE TITLE
Is there a way to disable image preview in completion?

### ISSUE THREAD

**Issue by a-torgovitsky** [latex-lsp/texlab#902]
Apologies for the simple question, but I poured over the documentation and was not able to find an option to change this.

In VS-Code, after `\beta` I get an autocompletion window.
The window shows  a rendered image of the beta symbol.
All I want is a way to disable the image.

I find it mildly annoying in VS-Code, but the real issue is when I try to use texlab in vim.
In that case, instead of an image I just see a long string of letters and numbers starting with `data:image/png;base64, ....` (is it the binary repesentation of the png file?)

**Comment by clason** [comment]
Your LSP client should set its capabilities properly (only text, no markdown), then you won't see it (as with 
Neovim's built-in client).

**Comment by a-torgovitsky** [comment]
Makes sense. I am seeing this in Neovim's built-in LSP client, but I am using a distro (LunarVim) that may have changed something away from its default. (I have opened an issue on the LunarVim repo about this, since this seems to be a poor default behavior.) Do you happen to know what one would do to change this behavior in Neovim's built-in LSP client?

**Comment by clason** [comment]
I can only say that I don't see it with Neovim's built-in client. LunarVim is a different project which is not supported by the Neovim team.

**Comment by a-torgovitsky** [comment]
Thanks, that's helpful to know

**Comment by yunusey** [comment]
Just quickly wanted to write this comment for those that might come here later. In your `lsp` config for `texlab`, you can make the following changes to disable the markdown support in your client `capabilities` - this will disable `base64` image support.

```lua
require('lspconfig').texlab.setup {
    on_attach = on_attach,
    capabilities = vim.tbl_extend('force', vim.lsp.protocol.make_client_capabilities(), ({
        textDocument = {
            hover = {
                contentFormat = { "plaintext" } -- to disable markdown on hover window (it is `{ "markdown", "plaintext" }` by default)
            },
            completion = {
                completionItem = {
                    documentationFormat = { "plaintext" } -- to disable markdown on completion window (it is `{ "markdown", "plaintext" }` by default)
                }
            }
        }
    })),
    filetypes = { "tex", "plaintex", "bib" },
    cmd = { "texlab" },
    settings = {
        texlab = {
            ... -- your settings
        }
    }
}
```
