### ISSUE TITLE
Bug: quit with exit code 101 and signal 0

### ISSUE THREAD

**Issue by Fireond** [latex-lsp/texlab#905]
I use neovim as editor and use mason to install texlab.
When open a tex file, texlab server quit unexpectedly.
LspLog:
```
[START][2023-07-20 19:21:06] LSP logging initiated
[ERROR][2023-07-20 19:21:06] .../vim/lsp/rpc.lua:676	"rpc"	"/Users/hanyu_yan/.local/share/nvim/mason/bin/texlab"	"stderr"	"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/syntax/src/latex/cst.rs:261:19\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

**Comment by clason** [comment]
You should share your `texlab` config.

**Comment by clason** [comment]
Impossible to tell without more detail. This is almost certainly a configuration error (either on your part, or whatever "distribution" configured this for you).

**Comment by Fireond** [comment]
Sorry, I now manually install texlab instead of use mason to organize, and now it works, thanks
