### ISSUE TITLE
Setup `auxDirectory` accroding to the `.latexmkrc`

### ISSUE THREAD

**Issue by jdujava** [latex-lsp/texlab#907]
**Feature request**: support parsing of  `.latexmkrc` (and/or other similar files) to automatically setup corresponding `auxDirectory`.
It would enable seamless transition between different "projects", without the need to manually change `texlab` LSP configuration.

**Comment by pfoerster** [comment]
> Would this be reasonable? Or should precedence be set the other way around?

I think I would do it the other way around because then you still have the possibility to override the inferred value (especially if it is wrong somehow).

**Comment by pfoerster** [comment]
@gnull Thanks for sharing a way on how to extract the variables from the latexmkrc file. I have created a PR that implements this approach: #968.

> The main thing which this issue seems to bring out for me is that we can't have project-specific settings of {aux,log,pdf}Directory. Or can we?

Technically yes, but this depends on the client. The server only asks for the current configuration so the client is free to return a different config for each workspace (like VSCode does with `.vscode/settings.json`).

> If a user has set {aux,log,pdf}Directory in her texlab config, she can also add -outdir=… and -auxdir=… with the same values to build.args on the next line.

Yes, but `texlab` does not look at `-outdir` and `-auxdir`, it will only look at `texlab.build.{aux,log,pdf}Directory`. With #968, the local `latexmkrc` file will take precedence over the `texlab.build.{aux,log,pdf}Directory.
