### ISSUE TITLE
Integration with LanguageClient-neovim 

### ISSUE THREAD

**Issue by linusheinz** [latex-lsp/texlab#92]
I try use this language server with a   [language client for neovim](https://github.com/autozimu/LanguageClient-neovim)
But it doesn't seem to work.
I'm starting the server without any argument 
   \ 'tex': ['~/bin/texlab'],

**Comment by clason** [comment]
What happens if you put the full path (without `~`) in the config? (I tested `LanguageClient` a while back, and it worked; I didn't spend much time with it since I settled on `vim-lsp` -- I'd be happy to share my config for that, if you wish.)

**Comment by linusheinz** [comment]
I tried it with full path, no success,
could you share your config would be super great

**Comment by clason** [comment]
(Also make sure it's executable -- can you call it from the commandline (`texlab --version`?) Can you move it somewhere in the `PATH`, e.g., `/usr/local/bin` (which is where I put it)?

My current `vim-lsp` config is
```vimL
" plugins via vim-plug
call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
call plug#end()
set hidden " needed for rename
if executable('texlab')
    au User lsp_setup call lsp#register_server({
                \ 'name': 'texlab',   
                \ 'cmd': {server_info->['texlab']},
                \ 'config': {
                \     'hover_conceal': 0,
                \     'filter': {'name': 'contains'}
                \ },
                \ 'whitelist': ['bib','tex'],
                \ })
endif
let g:lsp_peek_alignment='top'
let g:lsp_preview_max_width = 80
nmap <silent> K          <plug>(lsp-hover)
nmap <silent> <c-t>      <plug>(lsp-workspace-symbol)
nmap <silent> <leader>sd <plug>(lsp-definition)
nmap <silent> <leader>sp <plug>(lsp-peek-definition)
nmap <silent> <leader>sr <plug>(lsp-references)
nmap <silent> <leader>sn <plug>(lsp-rename)
nmap <silent> <leader>ss <plug>(lsp-document-symbol)
```
(adjust mappings to taste).

**Comment by linusheinz** [comment]
Im stupid i forgot +x :-1:  so greatful for your  kind help :+1: and this awesome project
