### ISSUE TITLE
Error: Support Multiple Independent Files

### ISSUE THREAD

**Issue by xuestrange** [latex-lsp/texlab#921]
I am preparing a paper revision. There are three indepent files `new.tex`, `old.tex`, `diff.tex` which are the main tex files to be compiled while the `build` folder saves all of the auxiliary files in stage of compiling. 

If I opened `new.tex` and then press `F5`, then `new.tex`, `old.tex`, `diff.tex` will be compiled together. I also find some weird things: the `diff.pdf` file will not be updated if I have changed and re-compiled the `diff.tex`, and be updated only if I delete `diff.pdf` followed by compiling.

I guess there is a lack of logics of handling multiple independent files.
```
Windows 10
Vscode 1.81.1
Vscode-Texlab latest version
```

```
├─ build
│  ├─ diff.aux
│  ├─ diff.bbl
│  ├─ diff.bcf
│  ├─ diff.fdb_latexmk
│  ├─ diff.fls
│  ├─ diff.log
│  ├─ diff.out
│  ├─ diff.pdf
│  ├─ diff.run.xml
│  ├─ diff.synctex.gz
│  ├─ diff.xdv
│  ├─ new.aux
│  ├─ new.bbl
│  ├─ new.bcf
│  ├─ new.blg
│  ├─ new.fdb_latexmk
│  ├─ new.fls
│  ├─ new.log
│  ├─ new.out
│  ├─ new.pdf
│  ├─ new.run.xml
│  ├─ new.synctex.gz
│  ├─ new.xdv
│  ├─ old.aux
│  ├─ old.bbl
│  ├─ old.bcf
│  ├─ old.blg
│  ├─ old.fdb_latexmk
│  ├─ old.fls
│  ├─ old.log
│  ├─ old.out
│  ├─ old.pdf
│  ├─ old.run.xml
│  ├─ old.synctex.gz
│  └─ old.xdv
├─ table
│  ├─ table.tex
├─ figure
│  ├─ figure.pdf
├─ template.cls
├─ new.tex
├─ old.tex
├─ diff.tex
```

**Comment by pfoerster** [comment]
@xuestrange What LSP client are you using?

> If I opened new.tex and then press F5, then new.tex, old.tex, diff.tex will be compiled together.

This sounds very weird. When a build request is sent to `texlab`, it tries to determine which file is the root file from the given document. However, this search only yields only one document. Then, `latexmk` (or the configured build tool) is called with the root file. So, usually compilation should only start from a single file.

Do you have any other plugins enabled or do you use `texlab.buildOnSave`?

**Comment by xuestrange** [comment]
@pfoerster Thanks for your help. I am a layman in this area, what is a LSP client or how can I find the information of LSP client? 😢 

I guess I forgot to mention that, `new.tex`, `old.tex` and `diff.tex` all use `table/table.tex` and `figure/figure.pdf` by `\input{table/table.tex}` and `\input{figure/figure.tex}`

My texlab configuration in vscode is shown below:
```json
  "texlab.build.executable": "latexmk",
  "texlab.build.args": [
    "-pdf",
    "-interaction=nonstopmode",
    "-synctex=1",
    "-file-line-error",
    "-output-directory=./build/",
    "-xelatex",
  ],
```
`texlab.buildOnSave` is disabled.
all extensions I installed:
```txt
cameronbieganek.julia-color-themes
codezombiech.gitignore
efoerster.texlab
emmanuelbeziat.vscode-great-icons
Gruntfuggly.todo-tree
IgorSbitnev.error-gutters
ionutvmi.path-autocomplete
jduponchelle.rainbow-end
jsaulou.theme-by-language
julialang.language-julia
mhutchie.git-graph
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.remote-repositories
mutantdino.resourcemonitor
naumovs.color-highlight
oderwat.indent-rainbow
redhat.vscode-yaml
REditorSupport.r
spmeesseman.vscode-taskexplorer
stackbreak.comment-divider
usernamehw.errorlens
usernamehw.remove-empty-lines
valentjn.vscode-ltex
vscodevim.vim
XuangeAha.print-divider
zhucy.project-tree
znck.grammarly
```

**Comment by pfoerster** [comment]
@xuestrange Thanks for the info. Can you run the dependency graph command, and post it here, please?
To visualize the graph, you need the `tintinweb.graphviz-interactive-preview` extension.

Dependency graph command:
https://github.com/latex-lsp/texlab/wiki/Workspace-commands#texlabshowdependencygraph

**Comment by xuestrange** [comment]
@pfoerster 
<img src="https://raw.githubusercontent.com/xuestrange/picGoUploader/main/img/20230829110722.png">

**Comment by pfoerster** [comment]
@xuestrange Thanks for the example. Actually, it is a very simple issue: `texlab.build.args` is missing the placeholder for the file to compile. That's why `latexmk` is compiling every file in the directory.

```jsonc
 "texlab.build.args": [
    "-pdf",
    "-interaction=nonstopmode",
    "-synctex=1",
    "-file-line-error",
    "-output-directory=./build/",
    "-xelatex",
    "%f"
  ],
```

**Comment by xuestrange** [comment]
> @xuestrange Thanks for the example. Actually, it is a very simple issue: `texlab.build.args` is missing the placeholder for the file to compile. That's why `latexmk` is compiling every file in the directory.
> 
> ```js
>  "texlab.build.args": [
>     "-pdf",
>     "-interaction=nonstopmode",
>     "-synctex=1",
>     "-file-line-error",
>     "-output-directory=./build/",
>     "-xelatex",
>     "%f"
>   ],
> ```

Thanks. This is right the answer.
