### ISSUE TITLE
Double goto definition reference

### ISSUE THREAD

**Issue by xyegithub** [latex-lsp/texlab#924]
![2023-09-02_21-11](https://github.com/latex-lsp/texlab/assets/46625185/7f320cc6-9c40-4082-9754-411aae58e9e3)
As shown by the picture, the source file Chapter/Chapter_enabstract.tex showed twice when I use press gd to go to definition.

**Comment by pfoerster** [comment]
@xyegithub I have a suspicion that it might be related to the LSP client. Does it also happen with other LSP clients such as the built-in Neovim LSP client or VSCode? Maybe Mason is grouping the results of goto definition and the document links together into one list. This would explain the issue.

**Comment by naibaf0** [comment]
I have the same issue in Neovim with the builtin LSP client.
