### ISSUE TITLE
modifying chktxt to not pass some warning messages

### ISSUE THREAD

**Issue by pfoerster** [latex-lsp/texlab#927]
### Discussed in https://github.com/latex-lsp/texlab/discussions/886

<div type='discussions-op-text'>

<sup>Originally posted by **madecunningly** May  7, 2023</sup>
I'm using the texlab setting to run chktex on open and save. However, I'd really like to modify the chktex to ignore a couple warnings. If I was using chktex directly, I would call chktex with something like 
`chktex --localrc myrcfile mytexfile.tex`  (myrcfile being the resource file modifying the chktex warnings)
However, as chktex is being called by texlab, how do I configure texlab to call chktex with the flag for the local resource file?</div>

**Comment by ROCKTAKEY** [comment]
@pfoerster Hi, I would like to add `texlab.chktex.additionalArgs` as configuration to [lsp-latex](https://github.com/ROCKTAKEY/lsp-latex), but there is no section on [Wiki](https://github.com/latex-lsp/texlab/wiki/Configuration#texlabchktexonopenandsave). Could you add one about it?

**Comment by pfoerster** [comment]
@ROCKTAKEY Sure 👍 
https://github.com/latex-lsp/texlab/wiki/Configuration#texlabchktexadditionalargs
