### ISSUE TITLE
Documentation elaboration for workspace/executeCommand

### ISSUE THREAD

**Issue by sdbuch** [latex-lsp/texlab#929]
Hi,

I wanted to suggest a clarification to the [wiki page on workspace commands](https://github.com/latex-lsp/texlab/wiki/Workspace-commands) which would have retroactively saved me several hours of time had I seen it initially. At the same time, I am an extreme neophyte with respect to both Rust and LSP, so please feel free to disregard or close this if it's solely my lack of understanding that's caused my issues!

### Some background + my issue

I was trying to implement a `TexlabClean` command analogous to `TexlabBuild` etc., following [this issue](https://github.com/latex-lsp/texlab/issues/607) and [this closed issue](https://github.com/neovim/nvim-lspconfig/issues/1935) in the `nvim-lspconfig` repo which suggests how to do this. It seemed to me the texlab [wiki page on workspace commands](https://github.com/latex-lsp/texlab/wiki/Workspace-commands) suggests a params interface for `texlab.cleanAuxiliary` (etc.) which is analogous to that of the build request (c.f. [here](https://github.com/latex-lsp/texlab/wiki/LSP-Internals#build-request)), so I was constructing the request in the following way:

```
local util = require 'lspconfig.util'
  -- Texlab supports a clean command.
  -- Patch in a function that implements this, and add it to config below
  local function buf_clean(bufnr)
      bufnr = util.validate_bufnr(bufnr)
      local texlab_client = util.get_active_client_by_name(bufnr, 'texlab')
      local params = {
          command = 'texlab.cleanArtifacts',
          arguments = {
                document = { uri = vim.uri_from_bufnr(bufnr)},
           },
      }
      if texlab_client then
          texlab_client.request('workspace/executeCommand', params)
          print 'Clean Success'
      end
  end
```
 
This was not working for me, though, and the request was failing silently (it seems that this corresponds to code [here](https://github.com/latex-lsp/texlab/blob/3b305df5867dd53a3cc9ac5563bc85b3a29332bf/crates/texlab/src/server/dispatch.rs#L53), which doesn't log any warnings). The code that eventually works for me is to prepare the request like this:
```
      local params = {
          command = 'texlab.cleanArtifacts',
          arguments = {{ uri = vim.uri_from_bufnr(bufnr)}, },
      }
```

If I had understood LSP better from the outset, it seems that I could have inferred this more straightforwardly from the documentation in the Microsoft spec [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#executeCommandParams).

### Suggestion?

Would it make sense here to update the [wiki page on workspace commands](https://github.com/latex-lsp/texlab/wiki/Workspace-commands) to be more informative of this issue? For example, I think the page with information on build and forward search commands [here](https://github.com/latex-lsp/texlab/wiki/LSP-Internals) is helpful in that it writes out the interface for the request -- something similar could be done for the workspace commands page.

Thanks!

**Comment by pfoerster** [comment]
@sdbuch Sorry for the confusion! The current documentation was indeed misleading with the parameter names that do not actually exist. The new [wiki page](https://github.com/latex-lsp/texlab/wiki/Workspace-commands) should hopefully clear things up :)

**Comment by sdbuch** [comment]
It looks great! Thanks for your work on this nice project -- I'm finding it to be a significant upgrade over pure vimtex :-)
