### ISSUE TITLE
Project-wide sorting of workspace symbols

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#93]
(followup to #31)

It would be nice to have the global list of `workspaceSymbols` sorted by project order rather than alphabetically by file name: At the moment, if I have main.tex that includes -- in this order -- b.tex and a.tex, a `workspaceSymbols` request gives the (correctly sorted) symbols in a.tex before those in b.tex before those in main.tex, while the other way around would be more natural.

**Comment by pfoerster** [comment]
@clason  Can you try the latest commit on the master branch?

**Comment by clason** [comment]
@pfoerster Yes, that seems to work nicely, thank you very much!
