### ISSUE TITLE
Custom notification for reparsing aux files

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#94]
(followup to #31, but also relevant for completion and hover)

For hover, completion, documentSymbols, and workspaceSymbols, texlab extracts the label numbers from the aux files. If the document is changed and (re)built, this is then not picked up. Since for multi-file projects, the client may not be aware of all (especially aux) files while texlab has a project tree, it would be good if texlab didn't rely on `workspace/didChangeWatchedFiles` notifications from the client.

Instead, I would propose a custom notification (e.g., `workspace/projectBuilt`) that the client can send whenever it thinks that one (and thus, in almost all cases, all) aux files in the project have changed. This would then trigger reparsing _all_ aux files in the current project. (Naturally, `texlab`s custom `textDocument/build` command can do this internally.)

**Comment by pfoerster** [comment]
With the latest commit on the master branch, TexLab no longer relies on the `workspace/didChangedWatchedFiles` notification. A custom notification is not needed. Instead, TexLab uses the `modified` time of the files in order to determine whether to reparse an AUX file.

**Comment by clason** [comment]
Nice! There's just one small hiccup: The files aren't reparsed for `documentSymbols` or `workspaceSymbols`, only for completion (at least with vim-lsp, can't test with VS Code at the moment). Try the following for any project:

1. clean the project `latexmk -c`
2. open the project, trigger `workspaceSymbols` -> no numbers
3. build the project
4. trigger `workspaceSymbols` -> no numbers
5. trigger completion -> numbers
6. trigger `workspaceSymbols` -> numbers

**Comment by pfoerster** [comment]
> The files aren't reparsed for documentSymbols or workspaceSymbols, only for completion

Thanks, this one should be fixed with 3513a68f68ca71454e9ad1726b9f153a48473b08.

**Comment by clason** [comment]
Indeed, works like a charm! Thank you, that's really a nice improvement.

(Might make sense to make another release soon? Lots of features added since 1.5.0 -- enough for 2.0.0 (if you don't follow semver).)
