### ISSUE TITLE
luatex support

### ISSUE THREAD

**Issue by ElCbo** [latex-lsp/texlab#949]
Hi I'm heavily using lua code inside my documents and I get numerous errors. Does texlab work with luatex?

**Comment by pfoerster** [comment]
@ElCbo Yes, the server should work with `luatex` just fine. You won't get completion but it should not report any errors. Can you share a snippet where texlab reports errors? Maybe the list of verbatim environments needs to be updated.

**Comment by ElCbo** [comment]
Hi, sorry for the inconvenience, I found my fault. There was an error in one of my own packages.
It's working with luatex like a charm.
