### ISSUE TITLE
Distinguish BibTeX completions and documentSymbols

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#95]
(also split off from #31)

Would it make sense (and be possible) to use different `kind`s for BibTeX completions and `documentSymbols` to distinguish `article`, `book`, `inproceedings`, `misc` etc.? (Assuming there are enough left?)

BibTeX itself only knows 13 *entries*:

* article
* book
* booklet
* inbook
* incollection
* inproceedings
* manual
* mastersthesis
* misc
* phdthesis
* proceedings
* techreport
* unpublished

and I would group some of them (`book`/`booklet`/`proceedings`, `inbook`/`incollection`/`inproceedings`, `mastersthesis`/`phdthesis`, 
`unpublished`/`techreport`/`manual`/`misc`). 

BibLaTeX knows many more entries, though, but most of them could either be grouped into one of the above equivalence classes or just left as plain `reference`.

(I would definitely not go down the list of *fields*: `author`, `title`, etc.)

**Comment by pfoerster** [comment]
@clason Can you try f5eb665c07957351abc958e47f278a2d0e6244eb, please?

**Comment by clason** [comment]
Yep, that works (it looks kinda weird if the kinds are just printed rather than shown as symbols...) What do you think?

(Also, how about for completion items? I noticed that I didn't mention this in the issue.)

**Comment by pfoerster** [comment]
> (Also, how about for completion items? I noticed that I didn't mention this in the issue.)

Completion items should use different kinds too with this commit. Could it be that they are still shown as `text` like it has been some time ago?

> Yep, that works (it looks kinda weird if the kinds are just printed rather than shown as symbols...) What do you think?

Does `vim-lsp` not use icons for the symbols?

**Comment by clason** [comment]
> Completion items should use different kinds too with this commit. Could it be that they are still shown as text like it has been some time ago?

Yes, it only shows `field`.

> Does vim-lsp not use icons for the symbols?

No, vim is pure text :) 

(Allowing overriding them with custom text -- or Unicode symbols -- by server is on my todo list. Long-term, it might make sense to write a custom texlab LSP client -- `texlab-nvim` -- that uses the base LSP functionality to be merged in 0.5.0, where the actual names could be hardcoded. The idea that a single client can handle all servers is neat, but leads to exponential complexity in treating all edge cases.)

**Comment by clason** [comment]
Actually, in VS Code I also see only a single icon for `\cite` completions!

**Comment by pfoerster** [comment]
> Actually, in VS Code I also see the same icon for all \cite completion candidates!

Oh, I totally forgot this one. 58633bf5a46579451459cf0e39ba09ecd3365062 should fix it.

**Comment by pfoerster** [comment]
> (Allowing overriding them with custom text -- or Unicode symbols -- by server is on my todo list. Long-term, it might make sense to write a custom texlab LSP client -- texlab-nvim -- that uses the base LSP functionality to be merged in 0.5.0, where the actual names ("book" etc.) could be hardcoded. The idea that a single client can handle all servers is neat, but leads to exponential complexity in treating all edge cases.)

This would probably be a good idea. At the moment, the `data` field of the completion items contains basic information about the object that gets completed. Maybe, we could include even more information for the client in order to support this use case.

**Comment by clason** [comment]
Yes, now it works! (By the way, I noticed that citeproc fails to parse a bibitem with an author whose first name is `Ha{\"\i}m` (Haïm) due to the double vowel modifier.)

>  Maybe, we could include even more information for the client in order to support this use case.

Interesting, like what? Maybe the bib file the item is from (in case you have included multiple files, and biblatex is set up to put them in different bibliography according to the file)? Or the contents of the `keywords` field?

**Comment by pfoerster** [comment]
> (By the way, I noticed that citeproc fails to parse a bibitem with an author whose first name is Ha{\"\i}m (Haïm) due to the double vowel modifier.)

This one is pretty difficult to fix because the parsing is done by an external library (which I would love to replace with something else, see https://github.com/latex-lsp/texlab/issues/87 and https://github.com/latex-lsp/texlab/issues/16), but I will try to look into that one. 

> Interesting, like what? Maybe the bib file the item is from (in case you have included multiple files, and biblatex is set up to put them in different bibliography according to the file)? Or the contents of the keywords field?

Actually, the `data` field already contains the bib file the item is from. I am not sure yet which additional information could be useful. At the moment, the `data` field has the following type:

```rust
pub enum CompletionItemData {
    Command,
    CommandSnippet,
    Environment,
    Label,
    Folder,
    File,
    PgfLibrary,
    TikzLibrary,
    Color,
    ColorModel,
    Package,
    Class,
    EntryType,
    FieldName,
    Citation { uri: Uri, key: String },
    Argument,
}
```

**Comment by clason** [comment]
> This one is pretty difficult to fix because the parsing is done by an external library (which I would love to replace with something else, see #87 and #16), but I will try to look into that one.

Oh no, don't worry about that (at least on my account), just thought I'd pass it on; maybe can be reported upstream. (The only possible alternative I'm aware of is pandoc -- for which Rust bindings are available -- but that is hardly lightweight or portable...)

> Actually, the data field already contains the bib file the item is from. I am not sure yet which additional information could be useful.

Me neither -- another question is what the client would be able to do with any such information? (Besides showing it, but if I read the specification right, the main purpose is passing information any subsequent `resolve` request -- not sure what would be useful for that?)

In any case, I consider this issue solved; feel free to close it!

**Comment by clason** [comment]
Just for (my) later reference, I'm copying here the mapping of BibTeX entries to kinds:

```Rust
impl BibtexEntryTypeCategory {
    pub fn completion_kind(&self) -> CompletionItemKind {
        match self {
            Self::Misc => CompletionItemKind::Interface,
            Self::String => CompletionItemKind::Text,
            Self::Article => CompletionItemKind::Event,
            Self::Book => CompletionItemKind::Struct,
            Self::Collection => CompletionItemKind::TypeParameter,
            Self::Part => CompletionItemKind::Operator,
            Self::Thesis => CompletionItemKind::Property,
        }
    }

    pub fn symbol_kind(&self) -> SymbolKind {
        match self {
            Self::Misc => SymbolKind::Interface,
            Self::String => SymbolKind::String,
            Self::Article => SymbolKind::Event,
            Self::Book => SymbolKind::Struct,
            Self::Collection => SymbolKind::TypeParameter,
            Self::Part => SymbolKind::Operator,
            Self::Thesis => SymbolKind::Property,
        }
    }
}
```

**Comment by pfoerster** [comment]
> (The only possible alternative I'm aware of is pandoc -- for which Rust bindings are available -- but that is hardly lightweight or portable...)

Yeah, including pandoc-citeproc is possible but then we lose the ability to produce a single self-contained executable (I could not get static linking working on Windows) and the exectuable becomes huge (> 100 MB).

> Me neither -- another question is what the client would be able to do with any such information? (Besides showing it, but if I read the specification right, the main purpose is passing information any subsequent resolve request -- not sure what would be useful for that?)

One use case, I could imagine is that a client could use the `data` field instead of the `kind` field to display `article` instead of `event`.

**Comment by clason** [comment]
> Yeah, including pandoc-citeproc is possible but then we lose the ability to produce a single self-contained executable

No, that only makes sense if pandoc is added as an optional runtime dependency. The current implementation is definitely preferable, though.

> 

> One use case, I could imagine is that a client could use the data field instead of the kind field to display article instead of event.

Interesting idea; I'll keep this in mind for vim-lsp!
