### ISSUE TITLE
Completion item clash

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#96]
I think there's an unwanted clash for `completionItemKinds`: Both `environment` and `item` are assigned to `enumMember`:

https://github.com/latex-lsp/texlab/blob/58633bf5a46579451459cf0e39ba09ecd3365062/src/completion/factory.rs#L120

I assume that the former should be `enum` (as it is for `symbolKind`)?

There's also `theorem`, `package`, and `class` that are all assigned to `class` (7).

Also, both `item` and `book` are assigned to `struct`. 

These clashes prevent overriding the LSP kinds with the proper names (`package` and `class` can share a -- separate -- kind; since I don't need to distinguish them, I'll probably assign them an empty label anyway.)

(It would be helpful for that to have a list of correspondences between LaTeX structures and LSP kinds (completion and symbol) somewhere on the texlab website or the wiki here.)

**Comment by clason** [comment]
(Actually, playing around with this a bit, I think I'll just set every `completionItemKind` but the BibTeX ones to empty -- now that the `detail`s are in the completion menu, printing the text labels is somewhat redundant. For `symbols`, they can still be useful.) 

On a related note, would it make sense to prefix the sectioning commands as well (`Part I Background`, `Chapter 2 ...`, `Section 3.2 ...`)?

**Comment by pfoerster** [comment]
> I think there's an unwanted clash for completionItemKinds: Both environment and item are assigned to enumMember:

There is indeed something wrong with that one.

> (It would be helpful for that to have a list of correspondences between LaTeX structures and LSP kinds (completion and symbol) somewhere on the texlab website or the wiki here.)

This sounds like a good idea. The first step would be to centralize all the mapping between LaTeX structures and LSP kinds into a single file. Afterwards, we can create an extra section on the TexLab website and keep it up-to-date. I will work on that once #94 is done (it is almost done and there won't be a need for a custom notification nor will TexLab depend on the `workspce/didChangeWatchedFiles` notification. Instead of file watching, TexLab will look at the `modified` time of the project files in order to determine if reparsing is needed. This solution is actually way easier to implement, too).

**Comment by pfoerster** [comment]
> On a related note, would it make sense to prefix the sectioning commands as well (Part I Background, Chapter 2 ..., Section 3.2 ...)?

In this case, I think it would make sense to put the section text (e. g. "Background") in the `documentation` field.

**Comment by clason** [comment]
> This sounds like a good idea. The first step would be to centralize all the mapping between LaTeX structures and LSP kinds into a single file. Afterwards, we can create an extra section on the TexLab website and keep it up-to-date.

Yes, that is a good idea. How descriptive are the kind icons that VS Code (or others) provide? If not very, I'd suggest not trying to try to map to `kind`s that fit best but just to separate the number range into blocks (one for labels, one for class/package/command/file, one for BibTeX,...)

> I will work on that once #94 is done (it is almost done and there won't be a need for a custom notification nor will TexLab depend on the workspce/didChangeWatchedFiles notification. Instead of file watching, TexLab will look at the modified time of the project files in order to determine if reparsing is needed. This solution is actually way easier to implement, too).

That's great! Really looking forward to it.

> In this case, I think it would make sense to put the section text (e. g. "Background") in the documentation field.

True, similar to the float captions. This would keep the `detail` length in completion items somewhat similar (and shorter). Although I do like the title there... I don't have a strong preference either way. (I'd like to keep them in the symbols, though.)

**Comment by clason** [comment]
By the way, I'd be happy to share my `vim` config for the website if you think that would be helpful.

**Comment by clason** [comment]
> In this case, I think it would make sense to put the section text (e. g. "Background") in the documentation field.

Actually, while I see the rationale for that, I'd actually prefer to keep the section text (just like the theorem names) in the details -- they're helpful for picking the right item out of the completion list quicker, and vim-lsp doesn't show documentation (yet). Just my personal preference, though.

**Comment by pfoerster** [comment]
> For consistency, maybe the sectioning items could then be styled similarly (Chapter 1 (Background), Section 2.1 (Existence of solutions))? Not sure if that looks good, though.

If the sections are styled similarly, then this would break the sorting in the outline of VSCode.

![image](https://user-images.githubusercontent.com/13584622/65835198-c0b43580-e2e3-11e9-9028-627126dbb561.png)

Another way to look at this, is to say, that the current way is consistent with the way LaTeX renders the referenced objects.

> I think there's an unwanted clash for completionItemKinds

This should be fixed with bf988e02d113efb5abffcc5e4ce806b96e5754f1. The current mapping LaTeX/BibTeX structures to LSP kinds can be found here: https://github.com/latex-lsp/texlab/blob/master/src/lsp_kind.rs. I will put this information on the website, too.

**Comment by clason** [comment]
> If the sections are styled similarly, then this would break the sorting in the outline of VSCode.

That's indeed a good argument to leave it as is.

> Another way to look at this, is to say, that the current way is consistent with the way LaTeX renders the referenced objects.

That's not _quite_ true -- `\cref` would render them as `Chapter 1`, `Section 1.1` etc. (which the other labels are indeed styled consistently with). 

But I agree that sectioning symbols are somewhat of a special case.

For completion item details, however, I would still vote for consistency with the other labels. Is this possible (to render symbols and completion item details differently)?

> The current mapping LaTeX/BibTeX structures to LSP kinds can be found here: https://github.com/latex-lsp/texlab/blob/master/src/lsp_kind.rs. I will put this information on the website, too.

Nice! The PR for vim-lsp that allows overriding them is done as well: https://github.com/prabirshrestha/vim-lsp/pull/524

**Comment by pfoerster** [comment]
> For completion item details, however, I would still vote for consistency with the other labels. Is this possible (to render symbols and completion item details differently)?

17025f729413eba624ea9361ca2b40f3a4db4b2e should change the way section labels are rendered.

**Comment by clason** [comment]
Perfect! I'll shut up now 😉

**Comment by pfoerster** [comment]
The website has been updated: https://texlab.netlify.com/docs/reference/lsp-kinds
