### ISSUE TITLE
Documentation gives incorrect name for `texlab.auxDirectory` option

### ISSUE THREAD

**Issue by gnull** [latex-lsp/texlab#962]
https://github.com/latex-lsp/texlab/issues/635#issuecomment-1139557706

This comment mentions that the correct name of the option is `texlab.auxDirectory`, but the [wiki](https://github.com/latex-lsp/texlab/wiki/Configuration#texlabbuildauxdirectory) calls it `texlab.build.auxDirectory`. The former seems to be what my texlab installation 5.6.0 undestands.

I tried to make a PR to Wiki, but couldn't figure out how. Could someone please fix the incorrect name in the docs?

And also check that the adjacent `texlab.build.*Directory` options are documented correctly?

**Comment by pfoerster** [comment]
@gnull The names have changed with [5.8.0](https://github.com/latex-lsp/texlab/blob/master/CHANGELOG.md#580---2023-07-30). `texlab.auxDirectory` is deprecated (it will still work as long as you do not set `texlab.build.auxDirectory`).

With the latest versions, `texlab.build.auxDirectory`, `texlab.build.logDirectory` and `texlab.build.pdfDirectory` are used to configure the output paths so the wiki page is correct here.
