### ISSUE TITLE
Escaped percentage in some context is still highlihgted as a comment.

### ISSUE THREAD

**Issue by TomLebeda** [latex-lsp/texlab#965]
Hello, 

I noticed that in some context (in this case inside `xlabel` when using pgfplots) escaped percentage `\%` is still highlighted as a comment. 

In normal text it works fine and it doesn't affect other functionality, just the highlighting is off for that single line. 

I'm not sure how much work would it take to fix, since it seems like it's context-dependent and it's very specific, so I assume it's low priority issue. 

Here is an image of what I'm talking about:
![image](https://github.com/latex-lsp/texlab/assets/8739583/ac979b60-791f-4292-a93e-371b31f1c03a)

**Comment by pfoerster** [comment]
@TomLebeda Which client do you use? The server itself does not provide (semantic) highlighting.

**Comment by TomLebeda** [comment]
Sorry, I'm not sure what do you mean by client, but here is what I use: 
Neovim with Vimtex and Texlab, TreeSitter's highlighting turned off for latex files. I compile with Tectonic. 

But now that you mentioned it, it's possible that it's a Vimtex thing and not Texlab.

**Comment by pfoerster** [comment]
> it's possible that it's a Vimtex thing and not Texlab.

I think so too because the editor (= LSP client) is responsible for syntax highlighting (unless the server implements semantic highlighting, which texlab does not).

**Comment by TomLebeda** [comment]
Okay, thanks. I will take this issue to Vimtex and close this one then.
