### ISSUE TITLE
build error: async blocks are unstable

### ISSUE THREAD

**Issue by doronbehar** [latex-lsp/texlab#97]
I'm sorry if this comes out as a noob's question because I not really experienced in building Rust projects.

I'm trying to build from source a v1.5.0 Git checkout of this repo and I get the following error when building:

```
error[E0658]: async blocks are unstable
  --> /home/doron/.cargo/registry/src/github.com-1ecc6299db9ec823/runtime-raw-0.3.0-alpha.5/src/lib.rs:65:15
   |
65 |       let fut = async move {
   |  _______________^
66 | |         let t = fut.await;
67 | |         let _ = tx.send(t);
68 | |     };
   | |_____^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/50547

error[E0658]: async/await is unstable
  --> /home/doron/.cargo/registry/src/github.com-1ecc6299db9ec823/runtime-raw-0.3.0-alpha.5/src/lib.rs:66:17
   |
66 |         let t = fut.await;
   |                 ^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/50547

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `runtime-raw`.
```

I use rustup and I have the `rust-toolchain` needed installed. All of the following `cargo build` commands failed the same way:

- `cargo build`
- `$(rustup which cargo) build`
- `rustup toolchain default $(cat rust-toolchain) && cargo build`

I understand that this is exactly why you use a specific rust toolchain but I don't understand why  non of the above worked.

**Comment by efoerster** [comment]
You are trying to build the project with the stable version of the Rust compiler, which does not include the async/await syntax yet. To build the project, you currently need Rust Nightly. However, we plan to move to stable once [Rust 1.39](https://forge.rust-lang.org/) is released.

**Comment by doronbehar** [comment]
Thanks for insisting on that, I've found the problem using `where cargo`. I've messed up my rustup installation a little bit.

On a different topic: Continuing from https://github.com/latex-lsp/citeproc/pull/1, would you suggest to wait for the next release for our package? I'm just wondering how long would that take and whether it'd be worth it to patch the 1.5.0 version on our end for the sake of packaging.
