### ISSUE TITLE
Cannot get autocomplete with files in `graphicspath`

### ISSUE THREAD

**Issue by danilka4** [latex-lsp/texlab#997]
I am currently using Neovim v0.9.5 to make presentations using LaTeX and use texlab v5.12.1 through the native neovim lsp. I use nvim cmp for autocompletion and mason.nvim for language server management.

I have a `\graphicspath{{absolute_path}}` to a directory of images. However, the list of images in that path does not show up in the autocompletion options (although I did find #590 where the feature was added). The options that do appear are a list of png, jpg, and pdf files and subdirectories in the directory the tex file resides in. Moreover, the autocompletion does not update with the files of a subdirectory of images once I select that subdirectory. I am unsure if these two issues are linked.

The relevant parts of my nvim configuration are:
```lua
require('mason').setup({})
require('mason-lspconfig').setup({
    -- Replace the language servers listed here
    -- with the ones you want to install
    ensure_installed = {'texlab'},
})
require 'lspconfig'.texlab.setup {}
```

**Comment by pfoerster** [comment]
@danilka4 Thanks for the report! This is fixed with 80b34e4.
